- pkg/cloudprovider/provider/openstack/helper.go
> Fix check for available Openstack floating IPs

- pkg/userdata/ubuntu/userdata.go
> fix error when no install candidate can be found for the requested cri-o version

- Dockerfile
- Makefile
- examples/machine-controller.yaml
Fixes the build chain
Why i removed upx:
https://github.com/kubernetes/kubernetes/pull/28265#issuecomment-230124309
> Fix build chain

- cmd/controller/main.go
We need to wait until the informers are synced before starting the controller.
This pr adds a wait to the cmd/controller
> add missing informer sync

- Makefile
- README.md
Improve developer getting started experience
> Add target for vendor

- test/tools/verify/README.md
- test/tools/verify/cmd/main.go
- test/tools/verify/manifests/machine-digitalocean.yaml
this PR introduces the initial scaffolding of the test tool app. At the moment it reads command line arguments and modifies the given manifest accordingly. 
**Which issue(s) this PR fixes** : see more: #47
> initial scaffolding of the test tool app.

- test/tools/verify/cmd/main.go
wires packages that are required in order to verify if the current state of the cluster matches the desired one.
**Which issue(s) this PR fixes** : see also #47
> adds required kubernetes packages

- Gopkg.lock
- Gopkg.toml
- cmd/controller/main.go
- examples/machine-controller.yaml
- pkg/controller/kubeconfig.go
- pkg/controller/machine.go
- pkg/health/readiness.go
- pkg/machines/register.go
> add readiness checks

- .circleci/config.yml
- Gopkg.lock
- Gopkg.toml
- Makefile
- cmd/controller/main.go
- cmd/controller/metrics.go
- examples/machine-controller.yaml
- pkg/controller/machine.go
It adds basic metrics
Fixes #46, #61
> add metrics

- test/tools/verify/cmd/main.go
- test/tools/verify/manifests/machine-digitalocean.yaml
implements verify method, at the moment this includes checking the cluster state before and after a new machine has been created.
**Which issue(s) this PR fixes** : see more #47
> implements verify method

- test/tools/verify/cmd/main.go
**What this PR does / why we need it**: this PR makes sure that the mess we have made will be cleaned up.
**Which issue(s) this PR fixes**: #47
> implements clean-up logic

- test/tools/verify/cmd/main.go
**What this PR does / why we need it**: prints out statuses to facilitate troubleshooting
**Which issue(s) this PR fixes**: #47
> print out statuses to facilitate troubleshooting

- test/tools/verify/cmd/main.go
> sort imports

- Gopkg.lock
- Gopkg.toml
- README.md
- docs/cloud-provider.md
- docs/operating-system.md
- examples/machine-hetzner.yaml
- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/providerconfig/types.go
This adds hetzner cloud as provider.
Though we need to wait until they increased the size for the user-data from 4096 to 16384
> add hetzner cloud

- cmd/controller/main.go
- examples/machine-controller.yaml
- pkg/controller/machine.go
- pkg/health/readiness.go
> fix rbac related issues

- .gitignore
- Dockerfile
- Makefile
- README.md
- examples/machine-controller.yaml
- test/Makefile
- test/tools/integration/Dockerfile
- test/tools/integration/Makefile
- test/tools/integration/README.md
- test/tools/integration/hetzner.tf
- test/tools/integration/provision_master.sh
- test/tools/integration/variables.tf
- test/tools/verify/Makefile
- test/tools/verify/README.md
- test/tools/verify/cmd/main.go
Adds some code to allow for integration testing by creating a single-node-kubernetes cluster and deploying the `machine-controller` onto it.
Fixes #70 
> Add some basic integrationtests

- pkg/controller/machine.go
> Make machine<->node matching happen ASAP

- Makefile
- README.md
- pkg/userdata/ubuntu/crio.go
- pkg/userdata/ubuntu/crio_test.go
- pkg/userdata/ubuntu/userdata_test.go
- test/tools/integration/Makefile
> Fix cri-o deployment

- pkg/cloudprovider/provider/digitalocean/provider.go
We already mention this field in the examples, but didn't actually implemented it
> add missing digitalocean monitoring flag

- examples/machine-digitalocean.yaml
- examples/machine-openstack.yaml
> fix examples

- pkg/cloudprovider/provider/aws/provider.go
Currently the node creation on aws is broken when the ssh pubic key cannot be found.
Because we pass the wront key into ssh.NewPublic().
Also the lock which prevents multiple worker routines to create a ssh-key at the same time, was used at a completely wrong place
> fix aws publickey creation

- pkg/cloudprovider/provider/openstack/provider.go
make default securitygroup creation a fallback when none is set
Fixes #85
> make default securitygroup creation a fallback when none is set

- examples/machine-controller.yaml
> Add rbac rules to work with leader election

- cmd/controller/main.go
- pkg/controller/machine.go
Lets you specify a specific controller to process the machine via annotation `machine.k8s.io/controller: "foo"`. The matching controller needs to be started with `-name=foo`
Fixes #103
> add annotation based processing

- .circleci/config.yml
- .gitignore
- Makefile
- test/tools/verify/Makefile
- test/tools/verify/cmd/main.go
Adjust build and test process to use go 1.10. The speed improvement when using cached builds is astonishing :)
Fixes #
> Feature/go 1.10

- Gopkg.lock
- cmd/controller/main.go
**What this PR does / why we need it**: adds graceful shutdown capability and addresses review comments.
Fixes #101
**Special notes for your reviewer**: see also https://github.com/kubermatic/machine-controller/pull/110
> Review add graceful shutdown

- pkg/userdata/coreos/userdata.go
- pkg/userdata/coreos/userdata_test.go
> Set hostname to nodename in Container Linux machines

- cmd/controller/main.go
**What this PR does / why we need it**: removes additional group for synchronisation.
> no need to use additional group for synchronisation.

- .github/CODEOWNERS
> remove other codeowners

- .circleci/config.yml
**What this PR does / why we need it**: this PR adds functionality that will trigger a deployment when a tag with "release-" prefix has been added.
Fixes #
> trigger deployment when a tag with "release-" prefix has been added.

- examples/machine-controller.yaml
> Add rbac rule to allow all operations on machine crd

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
**What this PR does / why we need it**: this pull changes aws provider so that it will return terminal errors.
Fixes #
> AWS provider returns terminal errors

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/openstack/helper.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/controller/machine.go
**What this PR does / why we need it**: add terminal errors for openstack provider
Fixes #
> add terminal errors for openstack provider

- pkg/controller/machine.go
> Clear noderef on machine before creating a new instance at the cloud provider

- pkg/cloudprovider/provider/hetzner/provider.go
**What this PR does / why we need it**: adds terminal errors to hetzner provider.
Fixes #
> add terminal errors to hetzner provider

- Gopkg.lock
- pkg/controller/machine.go
- vendor/k8s.io/apimachinery/pkg/api/equality/semantic.go
**What this PR does / why we need it**: improves the way we clear node ref on the machine
> improves the way we clear node ref on the machine

- test/tools/verify/cmd/main.go
**What this PR does / why we need it**: verify tool checks ownerReferences to determine if a node for a machine has been created. This allows for running the verify tool multiple times.
Fixes #
**Special notes for your reviewer**: see also #129
> verify tool checks ownerReferences

- .github/CODEOWNERS
> Remove @mrIncompetent as codeowner

- pkg/controller/machine.go
When creating more than 3 machines at once, we run into rate-limits by aws.
As it does not make sense to validate a machine which has already been validated, this introduces a simple key-value cache for validation.
The machine-UID+machine-Revision will be used for identification. A key will get invalidated if the further processing fails.
> add simple validation cache

- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/controller/machine.go
Fixes the general deletion logic
Fixes #154
> fix instance deletion for AWS

- examples/machine-vsphere.yaml
- test/tools/integration/create-and-destroy-machine.sh
> Set distinct names for machines in e2e test

- pkg/controller/machine.go
accept status deleted from the provider for finalizer removal
Fixes kubermatic/kubermatic#903
> accept status deleted from the provider for finalizer removal

- test/e2e/provisioning/testdata/machine-aws.yaml
- test/e2e/provisioning/testdata/machine-digitalocean.yaml
- test/e2e/provisioning/testdata/machine-hetzner.yaml
- test/e2e/provisioning/testdata/machine-vsphere.yaml
> read credentials directly from values

- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
> Use an exclude selector for e2e tests

- examples/machine-controller.yaml
- pkg/controller/machine.go
Publishes events for machines which makes debugging and status checking much easier as we do not have to grep logs anymore.
Fixes #152 
> Publish events for machines

- examples/machine-openstack.yaml
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/controller/machine.go
**What this PR does / why we need it**: this pr adds tags to an instance for openstack provider. The tags can be set in the machine specification and will be attached to an instance at cloud provider.
Fixes #169
> adds tags to an instance for openstack provider

- examples/machine-digitalocean.yaml
- pkg/controller/machine.go
- pkg/userdata/centos/testdata/docker-1.13-aws.golden
- pkg/userdata/centos/userdata.go
- pkg/userdata/coreos/testdata/docker-1.12.6-auto-update-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/coreos/testdata/docker-1.12.6-auto-update-openstack-multiple-dns.golden
- pkg/userdata/coreos/testdata/docker-1.12.6-disable-auto-update-aws.golden
- pkg/userdata/coreos/userdata.go
- pkg/userdata/coreos/userdata_test.go
- pkg/userdata/ubuntu/testdata/cri-o-1.9-digitalocean.golden
- pkg/userdata/ubuntu/testdata/docker-1.13-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/userdata.go
> Disable ssh password auth

- examples/machine-vsphere.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machine-vsphere.yaml
- test/tools/integration/README.md
- test/tools/integration/provision_master.sh
> Make vsphere cluster configurable

- pkg/controller/kubeconfig.go
fix refreshing of the bootstrap token in case of a retry
> fix refreshing of the bootstrap token in case of a retry

- pkg/cloudprovider/provider/vsphere/provider.go
> fix cloud-config and provider setting on CoreOS

- test/e2e/provisioning/verify.go
For some reason there are cases where the node vanishes
after deleting the machine but the machine still stays.
We work around this by waiting for both the machine and the
node to disappear.
Resolves #232
Fixes #
> Ensure both the machine and gone are node in e2e test

- cmd/controller/main.go
- pkg/health/readiness.go
log failed healthcheck
Fixes #199
> log failed healthcheck

- pkg/controller/machine.go
> Expose instance addresses via event

- pkg/userdata/ubuntu/userdata.go
- test/tools/integration/provision_master.sh
> Fix creation of kube 1.8 machines

- .circleci/config.yml
> Fix circleci image publishing

- pkg/containerruntime/crio/supported_versions.go
- pkg/userdata/centos/testdata/docker-1.13-aws.golden
- pkg/userdata/centos/userdata.go
- pkg/userdata/ubuntu/testdata/cri-o-1.9-digitalocean.golden
- pkg/userdata/ubuntu/testdata/docker-1.13-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/userdata.go
> Disable read only port on the Kubelet

- examples/machine-vsphere.yaml
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/providerconfig/types.go
> Allow configuring vsphere connection settings via env vars

- pkg/providerconfig/types.go
- pkg/userdata/centos/userdata.go
- pkg/userdata/coreos/testdata/docker-1.12.6-vsphere-overwrite-cloudconfig.golden
- pkg/userdata/coreos/userdata.go
- pkg/userdata/coreos/userdata_test.go
- pkg/userdata/ubuntu/testdata/docker-1.13-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
Allows to overwrite the built-in cloud-config generation with a custom one on machine level
Fixes #
> Add optional OverwriteCloudConfig to providerconfig

- pkg/controller/machine.go
- pkg/userdata/ubuntu/testdata/docker-1.13-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-1.13-kubelet-1.11-aws.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/userdata.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machine-openstack-upgrade.yml
> Fix ubuntu dist-upgrade to be noninteractive

- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/kubernetes/helper.go
> azure: use finalizers for resource cleanup

- .circleci/config.yml
- Gopkg.lock
- cmd/controller/main.go
- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/get_client.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine/machine.go
- test/tools/integration/provision_master.sh
* Adds Validation for Azure Network & Subnet
* Moves the finalizer assignment after successful resource creation to avoid deadlocks
* Increases the e2e cleanup timeout as Azure may take quite some time there
Fixes e2e tests
> Fix Azure Validation & Finalizer assignment

- pkg/cloudprovider/provider/azure/provider.go
Add support for azure availability set
> add support for azure availability set

- cmd/controller/main.go
- pkg/controller/machine/machine.go
> process only machines with a matching worker name

- pkg/cloudprovider/provider/openstack/helper.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machine-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machine-openstack.yaml
> fix openstack e2e test configuration

- pkg/cloudprovider/provider/vsphere/provider.go
Fixes the inability to delete a machine, that due to a race condition is created but not powered on, resulting in message:
`failed to poweroff vm MACHINE_NAME: The attempted operation cannot be performed in the current state (Powered off).`
> vsphere: only power off a machine if it's on or suspended

- pkg/userdata/centos/testdata/docker-1.13-kubelet-v1.11-aws.golden
- pkg/userdata/centos/testdata/docker-1.13-kubelet-v1.8-aws.golden
- pkg/userdata/centos/testdata/docker-1.13-kubelet-v1.9-aws.golden
- pkg/userdata/centos/userdata.go
- pkg/userdata/coreos/testdata/docker-1.12.6-auto-update-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/coreos/testdata/docker-1.12.6-auto-update-openstack-multiple-dns.golden
- pkg/userdata/coreos/testdata/docker-1.12.6-disable-auto-update-aws.golden
- pkg/userdata/coreos/testdata/docker-1.12.6-vsphere-overwrite-cloudconfig.golden
- pkg/userdata/coreos/testdata/docker-1.12.6-vsphere-static-ipconfig.golden
- pkg/userdata/coreos/userdata.go
- pkg/userdata/helper/helper.go
- pkg/userdata/ubuntu/testdata/docker-1.13-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-1.13-kubelet-1.11-aws.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/userdata.go
> userdata: limit journald disk usage to 10G

- docs/container_runtime.md
- pkg/containerruntime/docker/supported_versions.go
- pkg/controller/machine/machine_test.go
- pkg/userdata/ubuntu/docker.go
- pkg/userdata/ubuntu/docker_test.go
- pkg/userdata/ubuntu/testdata/docker-17.12-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-17.12-kubelet-1.11-aws.golden
- pkg/userdata/ubuntu/testdata/docker-18.06-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-18.06-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/testdata/docker-18.06-openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
We migrated to Ubuntu Bionic, but that has a different set of Docker versions available.
**Release note**:
```release-note
NONE
```
> Fix ubuntu bionic

- pkg/cloudprovider/provider/azure/provider.go
> Azure: update Ubuntu SKU to bionic

- pkg/cloudprovider/provider/openstack/helper.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machine-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machine-openstack.yaml
cherry picked from commit 0e4ecae25c80d8730da9310f59263b2c8bac38d8
PR for master: https://github.com/kubermatic/machine-controller/pull/300
```release-note
NONE
```
> fix openstack e2e test configuration (#300)

- pkg/cloudprovider/provider/openstack/helper.go
Specify port id on FloatingIP creation.
Follow up on https://github.com/kubermatic/machine-controller/pull/316#discussion_r217648949
> openstack: specify port id on floating ip creation

- pkg/apis/cluster/v1alpha1/migrations/migrations.go
> Fix migration

- .circleci/config.yml
- hack/verify-type-revision-annotation-const.sh
- pkg/apis/cluster/v1alpha1/conversions/conversions.go
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/azure.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/digitalocean.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/hetzner.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/openstack.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere-static-ip.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere.yaml
- pkg/controller/machine/machine.go
> Add annotation containing machine type revision to machines

- pkg/apis/cluster/v1alpha1/migrations/migrations.go
- test/tools/integration/provision_master.sh
> Add logging to cluster api migration

- pkg/cloudprovider/provider/vsphere/helper.go
Fixes the vsphere cloning of the template, instead of cloning at dc level and relocating then, we'll directly clone to the target path.
Allows users to completly strip out permissions on datacenter level.
> Fixed vsphere template cloning

- examples/machine-controller.yaml
- pkg/controller/machine/machine.go
> Put instance addresses into machine status

- Makefile
- hack/update-fixtures.sh
> Cleanup machines before destroying dev test cluster

- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
> Cherry-pick Add more context to vsphere errors #354

- OWNERS
- OWNERS_ALIASES
> Add OWNERS

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #
```release-note
NONE
```
> Add release-note block to PR template

- pkg/cloudprovider/provider/openstack/provider.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Fixes #
```release-note
NONE
```
> Fix Openstack Delete err return

- cmd/controller/main.go
- pkg/apis/cluster/v1alpha1/migrations/migrations.go
- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine/machine.go
Fixes #
```release-note
Fix a bug in the migration to the cluster-api types that resulted in orphaned resources at cloud providers
```
> Migrate machine UIDs

- .circleci/config.yml
- pkg/cloudprovider/provider/vsphere/provider.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/migrateuidscenario.go
Fixes #
```release-note
NONE
```
> Test cloudproviders MigrateUID

- pkg/apis/cluster/v1alpha1/migrations/migrations.go
- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
- test/e2e/provisioning/migrateuidscenario.go
Fixes #
```release-note
NONE
```
> Make MigrateUID scenario concurrency-safe

- examples/machine-controller.yaml
- pkg/cloudprovider/provider/vsphere/provider.go
Fixes #394 
Fixes #356
```release-note
NONE
```
> Avoid deleting PV-backing vsphere volumes on instance delete

- examples/openstack-machinedeployment.yaml
- pkg/cloudprovider/provider/openstack/provider.go
enhance doc and clarify tag/metadata
Fixes #
```release-note
NONE
```
> Enhance doc and clarify openstack tag/metadata

- test/e2e/provisioning/all_e2e_test.go
Fixes #
```release-note
NONE
```
> Disable vsphere e2e tests

- examples/aws-machinedeployment.yaml
- pkg/cloudprovider/provider/aws/provider.go
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Remove creation of Instance profile & Role if not specified.
The `instanceProfile` field in the aws providerConfig is now a required field.
```release-note
NONE
```
> Remove creation of Instance profile & Role if not specified

- Makefile
Fixes #
```release-note
NONE
```
> Default GIT_TAG variable in Makefile

- pkg/admission/machines.go
- test/tools/integration/provision_master.sh
Fixes #
```release-note
none
```
> Allow machineSpec mutation when there is an initializer

- test/e2e/provisioning/helper.go
- test/tools/integration/provision_master.sh
Fixes #
```release-note
```
/release-note-none
> Replace 1.9 e2e tests with 1.13

- pkg/cloudprovider/provider/azure/cloudconfig.go
- pkg/cloudprovider/provider/openstack/cloudconfig.go
- pkg/cloudprovider/provider/openstack/cloudconfig_test.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
- pkg/cloudprovider/provider/vsphere/cloudconfig.go
- pkg/cloudprovider/provider/vsphere/testdata/2-virtual-centers.golden
- pkg/cloudprovider/provider/vsphere/testdata/simple-config.golden
Fixes #
```release-note
none
```
/hold
Until we know if this includes all required changes
> Update cloud-config structs

- pkg/cloudprovider/provider/aws/provider.go
Fixes #
```release-note
NONE
```
> Improve AWS defaulting and validation

- hack/ci-e2e-test.sh
- pkg/cloudprovider/provider/openstack/helper.go
- pkg/cloudprovider/provider/openstack/provider.go
Fixes #344 
```release-note
When the machine creation allocated a new floating ip to the project, it will now de-allocate that floating ip on machine-deletion
```
> Release Openstack Floating IP on deletion if it was newly allocated

- .golangci.yml
- pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec.go
- pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec_test.go
- pkg/apis/cluster/v1alpha1/conversions/testdata/clusterv1alpha1machineDeploymentWithProviderConfig/hetzner.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/clusterv1alpha1machineSetWithProviderConfig/hetzner.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineDeploymentWithProviderConfig/hetzner.yaml.golden
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineSetWithProviderConfig/hetzner.yaml.golden
- pkg/apis/cluster/v1alpha1/migrations/migrations.go
Fixes #
```release-note
none
```
> Migrate MachineSets and MachineDeployments ProviderConfig

- hack/ci-e2e-test.sh
Fixes #
```release-note
none
```
> Make e2e testcase configurable for CI

- test/e2e/provisioning/helper.go
- test/tools/integration/provision_master.sh
Fixes #
```release-note
none
```
/assign @kdomanski
> Remove Kubernetes 1.10 from e2e tests

- pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
- pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
- pkg/userdata/coreos/userdata.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/testdata/openstack.golden
- pkg/userdata/ubuntu/testdata/version-1.10.10.golden
- pkg/userdata/ubuntu/testdata/version-1.11.3.golden
- pkg/userdata/ubuntu/testdata/version-1.12.1.golden
- pkg/userdata/ubuntu/testdata/version-1.9.10.golden
- pkg/userdata/ubuntu/testdata/vsphere.golden
- pkg/userdata/ubuntu/userdata.go
* Fix CVE-2019-573 for Ubuntu
* Fix CVE-2019-573 for CoreOS
Fixes #
```release-note
Fix CVE-2019-573 for Ubuntu and CoreOS
```
> [release/v0.10] Fix CVE-2019-573 for Ubuntu and CoreOS (#453)

- hack/ci-e2e-test.sh
Properly cleans up ssh keys after e2e tests
Fixes #
```release-note
none
```
> Clean up ssh key during e2e test

- .golangci.yml
- pkg/cloudprovider/provider/openstack/cloudconfig.go
- pkg/cloudprovider/provider/openstack/cloudconfig_test.go
- pkg/cloudprovider/provider/openstack/testdata/config-with-special-chars.golden
- pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
- pkg/ini/duration.go
- pkg/ini/escape.go
Expand openstack cloud config.
```release-note
NONE
```
> expand openstack cloud config

- docs/howto-provider.md
Documentation on how to add a new cloud provider.
Fixes #
```release-note
NONE
```
> Add how-to for adding a new cloud provider

- cmd/controller/main.go
- pkg/controller/machine/machine.go
- pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
- pkg/userdata/centos/userdata.go
- pkg/userdata/centos/userdata_test.go
- pkg/userdata/convert/ignition-converter.go
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.golden
- pkg/userdata/coreos/userdata.go
- pkg/userdata/coreos/userdata_test.go
- pkg/userdata/helper/kubelet.go
- pkg/userdata/helper/kubelet_test.go
- pkg/userdata/helper/template_functions.go
- pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
- pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
- pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
- pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
- pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
- pkg/userdata/userdata.go
Fixes #440 
```release-note
new flag `-external-cloud-provider` which will initialize `kubelet --cloud-provider=external`
```
> --cloud-provider=external

- pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
- pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
- pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
- pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
- pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.golden
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
- pkg/userdata/helper/helper.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/testdata/openstack.golden
- pkg/userdata/ubuntu/testdata/version-1.10.10.golden
- pkg/userdata/ubuntu/testdata/version-1.11.3.golden
- pkg/userdata/ubuntu/testdata/version-1.12.1.golden
- pkg/userdata/ubuntu/testdata/version-1.9.10.golden
- pkg/userdata/ubuntu/testdata/vsphere.golden
- test/tools/integration/provision_master.sh
Based on several issues with reaching the inotify limit (~8k) this PR increases the limit for all nodes.
Upstream issues: 
- https://github.com/kubernetes/kubernetes/issues/7815
- https://github.com/kubernetes/kubernetes/issues/10421
- https://github.com/kubernetes/kubernetes/issues/74669
```release-note
Increase the inotify limit to 1048576
```
> Increase inotify limit

- README.md
- docs/e2e-infra.md
- docs/openstack-images.md
- docs/operating-system.md
- hack/e2e-setup-openstack-images.sh
- hack/setup-openstack-images.sh
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
This adds a script to automatically download & update the images on OpenStack
Also this adds some documentation on how to use the script
```release-note
NONE
```
> Fix openstack images and add documentation

- test/e2e/provisioning/verify.go
Fixes #
```release-note
none
```
> Dont drain during e2e tests

- hack/ci-e2e-test.sh
- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
Fixes #
```release-note
none
```
> Re-Check on joinClusterTimeout candidates

- Makefile
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
Fixes the code to pass Go 1.12s `go vet`
Fixes #
```release-note
none
```
> Fix go vet for go 1.12

- examples/gce-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider.go
```release-note
Preemptible flag for GCE
```
> Preemptible flag for GCE

- OWNERS
Fixes #
```release-note
none
```
> Add team/lifecycle label to all PRs

- test/e2e/provisioning/verify.go
Fixes #
```release-note
none
```
> Be more verbose when e2e tests time out waiting for a Node

- .golangci.yml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/deploymentscenario.go
- test/e2e/provisioning/verify.go
Fixes #
```release-note
none
```
> Use ctrlruntime client for e2e test

- pkg/cloudprovider/provider/openstack/provider.go
Ref: https://github.com/kubermatic/kubermatic/issues/3110
```release-note
NONE
```
/cc @alvaroaleman
> Use trust-device-path for Openstack config

- cmd/userdata/centos/main.go
- cmd/userdata/coreos/main.go
- cmd/userdata/ubuntu/main.go
- hack/e2e-setup-openstack-images.sh
- hack/setup-openstack-images.sh
- pkg/admission/machines_test.go
- pkg/apis/plugin/plugin.go
- pkg/cloudprovider/provider/packet/provider.go
- pkg/userdata/centos/centos.go
- pkg/userdata/coreos/coreos.go
- pkg/userdata/manager/manager.go
- pkg/userdata/manager/plugin.go
- pkg/userdata/plugin/plugin.go
- pkg/userdata/ubuntu/ubuntu.go
Fixes #
```release-note
none
```
> Fixup header boilerplate

- pkg/providerconfig/types.go
/shrug
```release-note
NONE
```
> Fix typo in error message

- pkg/controller/machine/machine.go
Currently we sometimes swallow errors, depending on where they happened and if we thought of adding an event there. This PR changes that to create an event for all errors that happened during reconciliation and removes the individual error events.
Fixes #
```release-note
none
```
> Create an event and error log for all reconciliaton errors

- pkg/controller/machine/machine.go
Fixes a bug in the finalizer handling ans simplifies `updateMachine`. Also makes `updateMachine` able to handle updates without changes, which can happen during finalizer handling
Fixes #
```release-note
none
```
> Simplify updateMachine and fix finalizer handling

- pkg/cloudprovider/provider/gce/cloudconfig.go
- pkg/cloudprovider/provider/gce/cloudconfig_test.go
- pkg/cloudprovider/provider/gce/provider.go
For https://github.com/kubermatic/kubermatic/pull/3350
```release-note
NONE
```
> Make CloudConfig for GCE public

- Gopkg.lock
- Gopkg.toml
- pkg/cloudprovider/provider/aws/provider.go
- vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/dep_service_ids.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
- vendor/github.com/aws/aws-sdk-go/service/iam/api.go
- vendor/github.com/aws/aws-sdk-go/service/iam/waiters.go
- vendor/github.com/aws/aws-sdk-go/service/sts/api.go
- vendor/github.com/aws/aws-sdk-go/service/sts/doc.go
- vendor/github.com/aws/aws-sdk-go/service/sts/errors.go
Fixes #
```release-note
Fixed an issue with the image discovery for CentOS on AWS
```
> Fix aws filters to include productCode for CentOS

- pkg/controller/machine/machine.go
Fixes #
```release-note
none
```
> Add machine delete finalizer only after successful creation

- pkg/cloudprovider/provider/packet/provider.go
> Allow to specify projectID using PACKET_PROJECT_ID

- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/packet/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/types/types.go
- pkg/cloudprovider/validationwrapper.go
- pkg/controller/machine/machine.go
- test/e2e/provisioning/migrateuidscenario.go
Fixes #
```release-note
none
```
> Rename cloud package to types

- OWNERS_ALIASES
Fixes #
```release-note
none
```
> Make nikhita and frank maintainers

- examples/aws-machinedeployment.yaml
Signed-off-by: Babatunde Olu-Isa <babatundeoluisa@gmail.com>
Fixes #
```release-note
```
> added > to access key ID field

- docs/operating-system.md
fix os support matrix in `docs/operating-system.md`
Fixes #549 
```release-note
NONE
```
> Fix OS docs

- pkg/controller/machine/machine.go
Fixes #
Ref: https://github.com/kubernetes/autoscaler/pull/1866/files#diff-014132aa5b0a6326019dc53062408944R36
```release-note
none
```
> Set cluster-autoscaler annotation on nodes

- examples/vsphere-machinedeployment.yaml
Signed-off-by: Artiom Diomin <kron82@gmail.com>
Example didn't reflected all the possible config option accessible in vSphere
Fixes #
```release-note
vSphere: add missing fields in example
```
> vSphere: add missing fields in example

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/packet/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
Fixes #
```release-note
none
```
> Use omitempty for providerConfigs

- pkg/userdata/coreos/provider_test.go
- pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
- pkg/userdata/helper/kubelet.go
- test/e2e/provisioning/helper.go
Fixes #
```release-note
none
```
/assign @nikhita
> Dont set --allow-privileged on kubernetes > 1.14 as it got removed

- pkg/cloudprovider/errors/errors.go
- pkg/cloudprovider/provider/vsphere/provider.go
Fixes #379
```release-note
none
```
/assign  @mrIncompetent
> VSphere: Use the machine UID for identification instead of name

- pkg/controller/machine/machine.go
- pkg/node/eviction/eviction.go
Currently, if an eviciton doesn't complete within the 60s timeout, we
return an error and go into the exponential backoff. This doesn't make
sense, because:
* We block a worker routine for up to 60s
* For some applications, the eviction of all replicas simply takes more
time, because the new replicas need some time to cope up. Instead of
going into the exponential backoff, we should try to create subsequent
evictions as soon as possible to speed up the whole process
Fixes #
```release-note
none
```
> Requeue machines after evictions were created instead of blocking

- README.md
Make the `howto-provider` visible on the README
```release-note
none
```
> Add the howto-provider to the README

- README.md
Fixes #
```release-note
none
```
> Fix rendering of TOC in readme

- pkg/controller/machine/machine.go
To be sure we don't orphan instances
Fixes #581 
```release-note
none
```
/assign @nikhita
> Always add instance delete finalizer initially

- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/ubuntu/testdata/openstack.yaml
- pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
- pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
- pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
- pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
- pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
- pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
- pkg/userdata/ubuntu/testdata/vsphere.yaml
Fixes #
```release-note
none
```
> Ubuntu: Disable ufw

- examples/azure-machinedeployment.yaml
- pkg/cloudprovider/provider/azure/create_delete_resources.go
Fixes #
```release-note
none
```
> Azure: Assign security group to instances

- pkg/controller/machine/machine.go
Fixes #
```release-note
none
```
> [release/v1.4] Correctly return sync errors

- pkg/cloudprovider/provider/vsphere/client.go
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
> Simplify the vCenter client creation

- examples/vsphere-machinedeployment.yaml
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/network.go
- pkg/cloudprovider/provider/vsphere/provider.go
This makes the machine-controller work with distributed switches in vCenter.
Also it simplifies the logic to handle network adapters. 
```release-note
NONE
```
> Make the vSphere work with distributed switches

- examples/kubevirt-machinedeployment.yaml
- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Signed-off-by: Moath Qasim <moad.qassem@gmail.com>
> change the name of the kubevirt config

- pkg/cloudprovider/provider/vsphere/provider.go
```release-note
vSphere: Remove the CPU limit
```
> vSphere: remove CPU limit

- pkg/providerconfig/types.go
> remove duplicate import

- Gopkg.lock
- pkg/cloudprovider/provider/alibaba/provider.go
Fixes #
```release-note
NONE
```
> some cleanup of alibaba cloud

- pkg/userdata/coreos/provider.go
- pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
- pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
- pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
- pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
- pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
- pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
- pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
Fixes #
```release-note
none
```
> Coreos: Inherit env into kubelet

- pkg/controller/machinedeployment/machinedeployment_controller.go
- pkg/controller/machineset/machineset_controller.go
This PR changes the MachineDeployment and MachineSet controller to not try anymore to match a MachineDeployment or MachineSet to a cluster, as that will never succeed in our case.
Fixes #
```release-note
none
```
> Stop trying to match Machine{Deployment,Set} to a cluster

- examples/machine-controller.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/tools/integration/provision_master.sh
We use some very outdated versions of Kubernetes during e2e tests, this PR fixes that.
Fixes #
```release-note
none
```
> Update the kubernetes versions for e2e tests

- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/util/util.go
- pkg/cloudprovider/util/util_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/migrateuidscenario.go
- test/e2e/provisioning/verify.go
This PR fixes the finalizers updating when machines are being cleaned up.
Fixes #4637
```release-note
None
```
> Fix the cleanup condition in azure cloud provider 

- cmd/controller/main.go
> say "machine controller has been successfully stopped" on shutdown, not startup

- pkg/userdata/coreos/provider.go
- pkg/userdata/coreos/provider_test.go
- pkg/userdata/coreos/testdata/v1.17.0.yaml
- test/e2e/provisioning/helper.go
- test/tools/integration/provision_master.sh
Fixes #
```release-note
Fixed a bug in Kubernetes 1.17 on CoreOS that prevented the Kubelet from starting
```
> Add support for Kubernetes 1.17 on CoreOS

- pkg/clusterinfo/configmap_test.go
- pkg/userdata/centos/provider_test.go
> use subtests in some table-tests to spot failures easier

- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/ubuntu/testdata/openstack.yaml
- pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
- pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
- pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
- pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
- pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
- pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
- pkg/userdata/ubuntu/testdata/vsphere.yaml
Enable swap accounting for ubuntu deployments
Fixes #597
```release-note
NONE
```
> Enable swap accounting for ubuntu deployments

- examples/openstack-machinedeployment.yaml
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/types/types.go
- pkg/cloudprovider/provider/vsphere/provider.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Adding support for RHEL os in openstack cloud provider
Fixes #5009
```release-note
None
```
> Support rhel in Openstack cloud provider

- .prow.yaml
This PR is to move the machine-controller Prow jobs from our centralised infra repository to the configuration file located in this repository.
Fixes #
```release-note
NONE
```
> Move machine-controller prow jobs in machine-controller repository

- pkg/cloudprovider/provider/aws/provider.go
Previously an instance on AWS was always created without specifying
a security group immediately followed by an API call to attach
the security group. This will not work in certain vpc-sharing
scenarios as there is no access to the default security group.
Also: this reduces AWS API usage.
```release-note
NONE
```
> AWS: Use security group on instance creation.

- pkg/cloudprovider/provider/digitalocean/provider.go
The DO provider used a nonsensical upper limit (1000), which is waaay above the actual DO hard limit. And the code would break if someone really had more than 1000 droplets in their account.
This PR implements very basic paging support for listing droplets.
```release-note
Fix Digitalocean if there are more than 200 droplets in the same account.
```
> Use pagination when listing Digitalocean droplets

- OWNERS_ALIASES
This PR is to update the machine-controller maintainers list.
Fixes #
```release-note
None
```
> Update maintainers list

- examples/azure-machinedeployment.yaml
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
- test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Add support for configurable Azure disk sizes
Fixes #
```release-note
NONE
```
> Add support for configurable Azure disk sizes

- pkg/cloudprovider/rhsm/subscription_manager.go
- pkg/cloudprovider/rhsm/subscription_manager_test.go
- test/e2e/provisioning/all_e2e_test.go
Support getting red hat subscriptions paginations for rhsm. 
Fixes kubermatic/kubermatic#5200
```release-note
None
```
> Enable redhat subscriptions pagination

- pkg/controller/nodecsrapprover/node_csr_approver.go
- pkg/controller/nodecsrapprover/node_csr_approver_test.go
This PR adds additional validations in the NodeCSRApprover controller.
Fixes https://github.com/kubermatic/kubermatic/issues/5177
```release-note
NONE
```
> Add additional validations in NodeCSRApprover controller

- Makefile
> fix build script regression from #680

- Makefile
> fix tag build regression from #680

- OWNERS_ALIASES
:cry: 
/assign @moadqassem 
```release-note
NONE
```
> Remove nikhita from OWNERS_ALIASES

- docs/rhel-custom-image.md
Add the path for the supported operating systems.
@irozzo-1A all the notes that you mentioned earlier are solved in this PR https://github.com/kubermatic/machine-controller/pull/733, if you see something wrong please add it here as a comment. 
```release-note
None
```
> Adjust the rhel documentation to refer to the supported OS file

- .prow.yaml
- pkg/cloudprovider/provider/vsphere/helper_test.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
This PR adds some test coverage on the resource pool support introduced by #726.
Fixes #
```release-note
NONE
```
> vSphere resource pool test

- pkg/cloudprovider/provider/azure/provider.go
- test/e2e/provisioning/all_e2e_test.go
Adding support for Flatcar linux to Azure cloud provider.
Fixes kubermatic/machine-controller#717
```release-note
None
```
> adding support for flatcar in azure

- pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
Fixes #
```release-note
None
```
> revert add datastore-cluster to GlobalOpts (#752)

- .prow.yaml
> [release/v1.8] copy .prow.yaml from infra repo

- pkg/cloudprovider/provider/azure/types/types.go
Fix the json tag for the ImagePlan field in azure cloud provider.
```release-note
None
```
> fix json tag for ImagePlan azure

- .gitignore
- Makefile
- cmd/machine-controller/main.go
- docs/network-restrictions.md
- pkg/apis/plugin/plugin.go
- pkg/controller/machine/machine.go
- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/provider_test.go
- pkg/userdata/flatcar/testdata/v1.18.0.yaml
Attempt to replace hyperkube image
Fixes #800
Heavily inspired by the https://github.com/kinvolk/lokomotive/blob/master/assets/lokomotive-kubernetes/bootkube/resources/charts/kubelet/templates/kubelet-ds.yaml
```release-note
on flatcar linux hyperkube image is partially replaced by the quay.io/poseidon/kubelet
```
> New -node-kubelet-repository flag

- docs/operating-system.md
> add Flatcar to OS/provider matrix

- OWNERS_ALIASES
Fixes #
```release-note
NONE
```
> update owners file

- examples/hetzner-machinedeployment.yaml
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/hetzner/types/types.go
```release-note
new hetzner field "image"
```
> new hetzner field "image"

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Backport of #826 (plus #822 and #794 to fix e2e tests)
Fixes #
```release-note
Fix docker installation for CentOS/RHEL 8
```
> [v1.14] Fix releasever to 7 for RHEL and CentOS in yum docker repository (#826)

- Makefile
- README.md
- examples/webhook-certificate.cnf
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/tools/integration/Makefile
- test/tools/integration/master_install_script.sh
- test/tools/integration/provision_master.sh
This updates the e2e tests to run all supported versions.
Fixes #
```release-note
NONE
```
> Update e2e tests to run all the currently supported k8s versions

- .prow.yaml
- docs/cloud-provider.md
- examples/scaleway-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/cloudprovider/provider/scaleway/types/types.go
- pkg/providerconfig/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-scaleway.yaml
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
Add Scaleway as a provider
Relates to https://github.com/kubermatic/kubeone/issues/1136
Not sure how to add E2E since a Scaleway account is needed
```release-note
Add Scaleway as a provider
```
> feat: add Scaleway as a provider

- docs/kubevirt.md
Adding more documentation about KubeVirt installation. 
Fixes #
This PR should fix kubermatic/docs#269
```release-note
None
```
> Document kubevirt installation

- cmd/machine-controller/main.go
- docs/cloud-provider.md
- docs/howto-provider.md
- docs/kubevirt.md
- docs/rhel-custom-image.md
- docs/vsphere.md
- examples/kubevirt-machinedeployment.yaml
- examples/machine-controller.yaml
- hack/ci-e2e-test.sh
- image-builder/build.sh
- pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec_test.go
- pkg/apis/cluster/v1alpha1/migrations/migrations.go
- pkg/cloudprovider/cache/cloudprovidercache_test.go
- pkg/cloudprovider/common/ssh/ssh.go
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/types/types.go
- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
- pkg/controller/machine/metrics.go
- pkg/machines/v1alpha1/types.go
- pkg/node/eviction/eviction.go
- pkg/rhsm/subscription_manager.go
- pkg/userdata/plugin/plugin.go
- pkg/userdata/scripts/health-monitor.sh
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/verify.go
No code changes, just typos.
```release-note
NONE
```
> Fix various typos

- test/e2e/provisioning/verify.go
The comment in the source code says it all.
```release-note
NONE
```
> Retry MachineDeployment creation during tests

- pkg/cloudprovider/provider/vsphere/helper.go
Fixes #
```release-note
Fix hostname for RHEL subscription
```
> Remove defective tab from cloud-init metadata

- pkg/containerruntime/containerd.go
- pkg/userdata/ubuntu/provider_test.go
- pkg/userdata/ubuntu/testdata/containerd.yaml
* Fix containerd install on ubuntu
* Add unit-test
Fixes #
```release-note
Fix containerd install on ubuntu
```
> Fix containerd install on ubuntu

- pkg/userdata/centos/provider.go
- pkg/userdata/helper/kubelet.go
- pkg/userdata/helper/kubelet_test.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/sles/provider.go
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/containerd.yaml
Fixes #
```release-note
Fix kubelet systemd unit service dependency on the correct container runtime
```
> Fix kubelet systemd unit service dependency on the correct container runtime

- Makefile
- cmd/machine-controller/main.go
- cmd/webhook/main.go
- pkg/admission/admission.go
- pkg/admission/machines.go
- pkg/apis/cluster/common/consts.go
- pkg/controller/machine/machine_controller.go
- pkg/node/flags.go
Save important settings (kubelet feature gates / external cloud provider) into annotation for consumption by other components.
Fixes #897
```release-note
* Machine settings in annotations
* -external-cloud-provider -node-kubelet-feature-gates flags moved from controller to the webhook
```
> Machine settings in annotations

- pkg/userdata/scripts/health-monitor.sh
Fixes #918
```release-note
Fix health-monitor WRT docker restarts
```
> Fix health-monitor WRT docker restarts

- pkg/admission/machines.go
In #924 it should have been machine.Spec, not just machine.
Fixes #
```release-note
Set OS label on machine.Spec
```
> Set OS label on machine.Spec

- pkg/containerruntime/containerd.go
- pkg/userdata/ubuntu/testdata/containerd.yaml
Fixes #927
```release-note
Fix environment sourcing when containerd is chosen
```
> Fix environment sourcing when containerd is chosen

- .prow.yaml
- .wwhrd.yml
- hack/verify-licenses.sh
Hopefully prevents #913 in the future.
```release-note
NONE
```
> add license check presubmit

- cmd/machine-controller/main.go
- pkg/cloudprovider/provider/baremetal/metadata/nautobot/client.go
- pkg/cloudprovider/provider/baremetal/plugins/driver.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/common.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/hardware.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/hardware.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/template.go
- pkg/cloudprovider/provider/baremetal/provider.go
- pkg/cloudprovider/provider/baremetal/types/types.go
- pkg/nautobot/client.go
- pkg/nautobot/device.go
Integrate Nautobot client in the baremetal provider so that we can use it as a metadata server.
Fixes #
```release-note
Baremetal cluster provisioning 
```
> Integrate nautobot client in baremetal provider

- pkg/cloudprovider/provider/aws/provider.go
- test/tools/integration/Makefile
- test/tools/integration/versions.tf
Backport of the original #886 
```release-note
Retry getting AWS instance (#886)
```
> [release/v1.19] Retry getting AWS instance (#886)

- cmd/machine-controller/main.go
- pkg/apis/cluster/v1alpha1/migrations/migrations.go
- pkg/controller/nodecsrapprover/node_csr_approver.go
- pkg/controller/nodecsrapprover/node_csr_approver_test.go
- pkg/machines/register.go
Fixes #905
```release-note
* update certificates.k8s.io to v1 
* upgrade apiextensions.k8s.io to v1
```
> API upgrades

- .prow.yaml
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/aws/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
Implement EC2 spot instances market options.
Fixes kubermatic/kubermatic#7227
```release-note
AWS spot instances market options 
```
> implement aws spot instance market options

- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
Introduce a new field in the azure machine deployment in order to fix the compatibility between VMs in AvailabilitySets and AvailabilityZones
Fixes #
```release-note
None
```
> Add assignAvailabilitySet to azure machine deployment 

- pkg/admission/machinedeployments_validation.go
Original error message is misleading.
```release-note
Fix copypaste typo in error message
```
> Fix copypaste typo in error message

- pkg/cloudprovider/provider/openstack/helper.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/controller/nodecsrapprover/node_csr_approver_v1beta1.go
Fixes #1022
```release-note
Don't delete openstack instances on creation timeout
```
> Don't delete openstack instances on creation timeout

- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/all_e2e_test.go
Support flatcar os in KubeVirt cloud provider.
Fixes #
```release-note
Support Flatcar os in KubeVirt 
```
> support flatcar in KubeVirt cloud provider

- pkg/cloudprovider/provider/aws/provider.go
Cleaning up the spot instance request when machines are deleted, otherwise, once the instance is deleted and the request isn't cleaned up, the instance will reappear again. 
Fixes kubermatic/kubermatic#7247
```release-note
Cleanup persistent spot Instance requests when a machine is deleted.
```
> cleanup persistent spot instances when machine is deleted

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/types/cloudconfig.go
- pkg/providerconfig/types/types.go
Adds KubeVirt cloud config
Fixes #7480
```release-note
Add KubeVirt CCM cloud config
```
> Refactor KubeVirt options parser and add KubeVirt cloud config

- pkg/admission/machines.go
- pkg/providerconfig/types.go
- pkg/providerconfig/types/types.go
- pkg/providerconfig/types_test.go
- pkg/userdata/amzn2/amzn.go
- pkg/userdata/centos/centos.go
- pkg/userdata/flatcar/flatcar.go
- pkg/userdata/rhel/rhel.go
- pkg/userdata/sles/sles.go
- pkg/userdata/ubuntu/ubuntu.go
Fixes #1028
```release-note
Add defauting of OperatingSystemSpec
```
> Add defauting of OperatingSystemSpec

- test/e2e/provisioning/helper.go
Currently we are using the auto-updated image for flatcar that we have in Openstack. Problem is, this image is changing all consistently due too upgrading from one release to another, thus we need to have our own custom image. The old image that we used, didn't support containerd cri thus we need to find an alternative. 
Fixes #
```release-note
None
```
> change flatcar image

- OWNERS_ALIASES
Adds Marvin (myself) to the OWNERS_ALIASES file so I can approve PRs.
Fixes #
```release-note
NONE
```
> Add Marvin to OWNERS_ALIASES

- OWNERS_ALIASES
Adding ahmedwaleedmalik(waleed@kubermatic.com) as project owner
Fixes #
```release-note
NONE
```
> Add Waleed as project owner

- pkg/controller/machine/bootstrap.go
- pkg/controller/machine/machine_controller.go
The bootstrapping scripts support only ubuntu and flatcar, this pr supports centos as well. 
Fixes #
```release-note
None
```
> Support centos bootstrapping

- pkg/controller/machine/bootstrap.go
Adjust the yum template that is used for bootstrapping CentOS to be used with amzn linux as well.  
Fixes #
```release-note
Amazon Linux support 
```
> Adjust yum bootstrapping script for amazon linux 

- pkg/controller/machine/bootstrap.go
Bootstrapping script for rhel.
Fixes #
```release-note
None
```
> adjust rhel bootstrapping script

- pkg/controller/machine/bootstrap.go
Add bootstrap script for SLES
Fixes #
```release-note
NONE
```
xref https://github.com/kubermatic/operating-system-manager/issues/80
> Add bootstrapping support for SLES

- cmd/machine-controller/custom_flags.go
- cmd/machine-controller/main.go
- pkg/containerruntime/containerd.go
- pkg/containerruntime/containerruntime.go
- pkg/containerruntime/docker.go
- pkg/userdata/amzn2/provider_test.go
- pkg/userdata/centos/provider_test.go
- pkg/userdata/flatcar/provider_test.go
- pkg/userdata/helper/helper.go
- pkg/userdata/helper/template_functions.go
- pkg/userdata/rhel/provider_test.go
- pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere-proxy.yaml
- pkg/userdata/sles/provider.go
- pkg/userdata/sles/provider_test.go
- pkg/userdata/ubuntu/provider_test.go
This is a companion/dependency PR for https://github.com/kubermatic/kubeone/pull/1674
```release-note
New -node-containerd-registry-mirrors flag
```
> New -node-containerd-registry-mirrors flag

- cmd/machine-controller/main.go
- go.mod
- pkg/apis/plugin/plugin.go
- pkg/controller/machine/machine_controller.go
- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/provider_test.go
Clanup of some of the code that is not needed anymore
Last user (flatcat) of kubelet image was modified such as now it will use binary directly on the host, outside of the container 
```release-note
Remove unused hyperkube and kubelet repository
```
> Remove unused hyperkube and kubelet repository

- .gimps.yaml
- cmd/machine-controller/main.go
- docs/registry-authentication.md
- pkg/admission/machinedeployments_validation.go
- pkg/containerruntime/containerd.go
- pkg/containerruntime/containerruntime.go
- pkg/controller/machine/machine_controller.go
- pkg/userdata/helper/helper.go
- pkg/userdata/helper/kubelet.go
- pkg/userdata/ubuntu/provider_test.go
- pkg/userdata/ubuntu/testdata/containerd.yaml
xref https://github.com/kubermatic/kubeone/issues/1574
```release-note
containerd daemon level registry auth configuration
```
> Containerd daemon level registry auth configuration

- pkg/controller/machine/bootstrap.go
Fix kubelet bootstrap-kubeconfig for flatcar os.
Fixes #
```release-note
None
```
> fix cloud config ignition selection

- .prow.yaml
At the moment, the vSphere setup that we run is a bit under the weather, thus we will disable the e2e tests until it is fixed 
Fixes #
```release-note
None
```
> disable vSphere tests

- examples/machine-controller.yaml
- pkg/controller/machine/machine_controller.go
- pkg/controller/machine/machine_test.go
- pkg/node/eviction/eviction.go
- pkg/node/nodemanager/node_manager.go
- pkg/node/poddeletion/pod_deletion.go
Cherry pick volume de/attach in vSphere external csi driver fix 
Fixes #
```release-note
Waiting for volumeAttachments deletion for vSphere cloud provider 
```
> [release/v1.36] Waiting for volumeAttachments deletion (#1190)

- pkg/controller/machine/machine_controller.go
- pkg/controller/machinedeployment/rolling.go
- pkg/controller/machinedeployment/sync.go
- pkg/controller/util/machine.go
- pkg/controller/util/machine_deployment.go
There are few utilities functions that are used in one place, are needed for upcoming changes. This PR is a prerequisite change for the usage of those controllers utilities. 
Fixes #
```release-note
None
```
> Refactor controller utilities

- pkg/cloudprovider/provider/vsphere/client.go
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/types/types.go
**What this PR does / why we need it**: Add tag support for vSphere provider
Fixes #1209
```release-note
Add tag support for vSphere provider
```
> Add tag support for vSphere provider

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
- pkg/cloudprovider/util/net.go
- pkg/node/poddeletion/pod_deletion.go
- test/e2e/provisioning/migrateuidscenario.go
Reverts kubermatic/machine-controller#1208
```release-note
None
```
> Revert "assign ipv6 address to aws"

- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/baremetal/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/types/types.go
- pkg/cloudprovider/validationwrapper.go
- pkg/controller/machine/machine_controller.go
- test/e2e/provisioning/migrateuidscenario.go
Reverting PR https://github.com/kubermatic/machine-controller/pull/1207
Fixes #
```release-note
None
```
> revert network config

- Makefile
- cmd/userdata/rockylinux/main.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/containerruntime/containerd.go
- pkg/containerruntime/docker.go
- pkg/providerconfig/types.go
- pkg/providerconfig/types/types.go
- pkg/userdata/manager/manager.go
- pkg/userdata/rockylinux/provider.go
- pkg/userdata/rockylinux/provider_test.go
- pkg/userdata/rockylinux/rockylinux.go
- pkg/userdata/rockylinux/testdata/kubelet-containerd-v1.20-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.20-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws-external.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-nutanix.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-mirrors.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-proxy.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
Adding support for RockyLinux OS in aws cloud provider. 
Fixes #
```release-note
Support RockyLinux for AWS 
```
> Add rocky linux support for AWS 

- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/userdata/rockylinux/provider.go
- pkg/userdata/rockylinux/testdata/kubelet-containerd-v1.20-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.20-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws-external.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-nutanix.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-mirrors.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-proxy.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
Support Rocky Linux on Hetzner Cloud
Fixes #
```release-note
Support rockylinux in hetzner
```
> Support rockylinux in hetzner

- pkg/cloudprovider/provider/digitalocean/provider.go
- test/e2e/provisioning/all_e2e_test.go
Support Rocky Linux on DO
Fixes #
```release-note
Support rocky linux for Digitalocean 
```
> Support rocky linux for DO

- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Rocky Linux support for KubeVirt 
Fixes #
```release-note
Support Rocky linux for KubeVirt cloud provider 
```
> Support Rocky linux for KubeVirt

- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
Extend Openstack e2e tests to support Rocky Linux 
Fixes #
```release-note
none 
```
> support rocky linux for OS

- pkg/cloudprovider/provider/kubevirt/provider.go
This PR adds `DataVolumeSourcePVC` to the `DataVolumeTemplates` in `VirtualMachine`. This enables cloning a `DataVolume` from existing one.
Fixes kubermatic/kubermatic#8491
```release-note
None
```
Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>
> add DataVolumeSourcePVC for KubeVirt

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/util/net.go
Adds dual-stack support for AWS. 
Implements part of https://github.com/kubermatic/kubermatic/issues/9100
```release-note
add dual-stack support for AWS
```
> add dual stack support for AWS

- .golangci.yml
- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/get_client.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/util/net.go
Adds dual-stack support for Azure.
Implements part of https://github.com/kubermatic/kubermatic/issues/9351
```release-note
add dual-stack support for Azure.
```
> add dual-stack support for Azure

- test/e2e/provisioning/all_e2e_test.go
Supporting Rocky Linux in vSphere
Fixes #
```release-note
rocky linux support in vSphere 
```
> Rocky Linux support in vSphere 

- .prow.yaml
- examples/machine-controller.yaml
- pkg/controller/machine/machine_controller.go
- pkg/controller/machine/machine_test.go
- pkg/node/eviction/eviction.go
- pkg/node/nodemanager/node_manager.go
- pkg/node/poddeletion/pod_deletion.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
manual backport of #1190
```release-note
[release/v1.37] Waiting for volumeAttachments deletion
```
> [release/v1.37] Waiting for volumeAttachments deletion

- go.mod
- go.sum
- pkg/cloudprovider/provider/azure/provider.go
Fix cleanup for machines on azure.
Fixes #1285
I don't think we need a release note for updating `github.com/Azure/azure-sdk-for-go` to v64.1.0 or do we?
```release-note
NONE
```
> Fix cleanup for machines on azure

- docs/anexia.md
Templates are rotated quite often and the old templates are removed as a result.This PR intends to document the process of retrieving a list of available templates.
Fixes #
```release-note
NONE
```
> docs(anexia): add info for templates

- pkg/cloudprovider/provider/azure/provider.go
- pkg/controller/machine/bootstrap.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
- pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
Addition of the rh_subscription cloud-init module to the yum
version of the bootstrap script.
Fixes #1261 
```release-note
RHEL in Azure has been updated to the 8.5 version, and the rh_subscription module has been added to the bootstrap cloud-init when using RHEL.
```
> rh_subscriprion bootstrap script

- .prow/provider-nutanix.yaml
Fixes #
```release-note
NONE
```
> Disable e2e tests for Nutanix

- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/all_e2e_test.go
Manual cherry-pick for https://github.com/kubermatic/machine-controller/pull/1301
Fixes #
```release-note
```
> Refactor handling of kubeconfig for kubevirt

- docs/operating-system.md
Add Rocky Linux to the compatibility matrix.
Fixes #
```release-note
NONE
```
> docs: include rocky linux in compatibility matrix

- pkg/cloudprovider/provider/vmware-cloud-director/helper.go
- pkg/cloudprovider/provider/vmware-cloud-director/provider.go
Set computer name for VCD VMs.
Fixes #
```release-note
NONE
```
> Set computer name for VCD VMs

- pkg/cloudprovider/provider/azure/provider.go
This PR fixes a regression introduced in #1253. Since #1253, we unconditionally try to get an IPv6 address for a VM. However, if there's no IPv6 address for that VM, the API call will fail. This results in the `getNICIPAddresses` function failing, so no IP address is set on the Machine object.
The API call fails with the following message:
```
E0526 16:54:40.541974  218906 machine_controller.go:378] Failed to reconcile machine "marko-1-pool1-7b9955cf46-qvns5": failed to get instance from provider: failed to retrieve IP addresses for VM 0xc0007600f0: failed to get addresses for interface "marko-1-pool1-7b9955cf46-qvns5-netiface": failed to retrieve IP string for IP "ip-config-1": failed to get IP "marko-1-pool1-7b9955cf46-qvns5-netiface-pubipv6": …
```
> Load IPv6 address on Azure only if IPFamily is IPv6 or Dualstack

- pkg/cloudprovider/provider/aws/provider.go
In offline setups it's not possible to reach the IAM API. To make the machine controller function in a private VPC with no internet access, the validation of the instance profile needs to be reduced to a simple check, if it was set.
Fixes #787
Reference: https://stackoverflow.com/questions/72307375
```release-note
(AWS) Instance profile validation is no longer calling the IAM API
```
> Reduce instance profile validation to existence check

- pkg/cloudprovider/provider/digitalocean/provider.go
Adds dual stack support for DigitalOcean.
Part of https://github.com/kubermatic/kubermatic/issues/10005
```release-note
Added dual stack support for DigitalOcean.
```
> add dual stack support for DigitalOcean

- pkg/cloudprovider/provider/equinixmetal/provider.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-equinixmetal.yaml
- test/e2e/provisioning/testdata/machinedeployment-gce.yaml
Adding support for Rocky Liinux in Equinixmetal cloud provider  
Fixes #
```release-note
Roky linux support in Equinixmetal. 
```
> Support rockylinux in Equinixmetal cloud provider 

- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
Upgrade to go 1.18.3 🚀 
Fixes #
```release-note
Upgrade to go 1.18.3
```
> Upgrade to go 1.18.3

- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
Add support for using accelerated networking for Azure VMs.
Fixes #869
```release-note
Azure: Support for accelerated networking
```
> Azure: Support for accelerated networking

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Makefile
- hack/ci/download-gocache.sh
- hack/ci/setup-kind-cluster.sh
- hack/ci/upload-gocache.sh
- test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
Fixes #
```release-note
NONE
```
> Improvements for CI

- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Manual cherry-pick for https://github.com/kubermatic/machine-controller/pull/1301
Fixes #
```release-note
```
> [release/v1.45] Refactor handling of kubeconfig for kubevirt 

- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Manual cherry-pick for https://github.com/kubermatic/machine-controller/pull/1301
Fixes #
```release-note
```
> [release/v1.37] Refactor handling of kubeconfig for kubevirt 

- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Manual cherry-pick for https://github.com/kubermatic/machine-controller/pull/1301
Fixes #
```release-note
```
> [release/v1.36] Refactor handling of kubeconfig for kubevirt 

- examples/operating-system-manager.yaml
- go.mod
- go.sum
Fixes #
```release-note
Operating System Manager updated to v0.6.0
```
> Update OSM to v0.6.0

- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/provider.go
Manual backport for https://github.com/kubermatic/machine-controller/pull/1286 and https://github.com/kubermatic/machine-controller/pull/1287
Fixes #
```release-note
Azure resources are ignored during machine cleanup if resource-specific finalizers are not set
```
> [release/v1.43] Fix cleanup for machines on azure

- pkg/cloudprovider/provider/kubevirt/provider.go
This PR adds 'machine-name' prefix to secondary disk's name for kubevirt provider to avoid naming conflict.
Fixes #1378 
```release-note
NONE
```
Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>
> fix kubevirt secondary disk naming

- pkg/cloudprovider/provider/aws/provider.go
Changing the description of the SLES AMI for aws as the old description for the same image has been updated.
Fixes #
```release-note
None
```
> Fix SLES description

- docs/operating-system.md
The current OS and cloud provider compatibility matrix isn't correct and outdated, this PR updates this document and paves the way to reflect the same status in the UI. 
Fixes #
/kind documentation
/kind cleanup
```release-note
None
```
```documentation
None
```
> Operating system compatibility matrix update

- pkg/userdata/rockylinux/provider.go
- pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws-external.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-mirrors.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-proxy.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.24-aws.yaml
Part of https://github.com/kubermatic/kubermatic/issues/9994
```release-note
NONE
```
> enable DHCPv6 in RockyLinux

- .prow/provider-vsphere.yaml
- examples/operating-system-manager.yaml
- go.mod
- go.sum
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Fix E2E tests for vSphere and OpenStack

- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
Signed-off-by: Moath Qasim <moad.qassem@gmail.com>
Fixes #
```release-note
None
```
```documentation
None
```
> enable flatcar, rockylinux and rhel for azure

- cmd/machine-controller/main.go
In some situations you want to disable leader election on controllers. We already provide flags for that in KKP controllers, this essentially adds "feature parity", although it is mainly useful for development purposes (and therefore, no release note is added).
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Add leader election related flags to machine-controller

- .prow/provider-nutanix.yaml
- hack/ci/run-e2e-tests.sh
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-nutanix.yaml
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Remove references to proxy in Nutanix e2e testing

- examples/operating-system-manager.yaml
Using the image against latest commit hash to include the containerd 1.6 changes.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update OSM image for e2e tests

- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Fix E2E tests for vSphere.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.54] Fix e2e tests for vSphere

- .prow/postsubmits.yaml
- CONTRIBUTING.md
- docs/howto-provider.md
- hack/ci/download-gocache.sh
- hack/ci/upload-gocache.sh
We are in the process of renaming the master branch across all repos, and this PR prepares this repo for the renaming.
/kind cleanup
```release-note
The primary Git branch was renamed from `master` to `main`.
```
```documentation
NONE
```
> rename master branch to main

- .prow/e2e-features.yaml
- hack/ci/calico.yaml
- hack/ci/setup-kind-cluster.sh
- hack/lib.sh
- test/e2e/provisioning/verify.go
Backports #1464 and #1459 so the release branch can be properly tested for bugfix cherry-picks.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.54] Update to Calico CNI, adjust node readiness checks and use KKP `main` branch

- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-openstack.yaml
- .prow/provider-vsphere.yaml
There is no point in running unrelated E2E tests unconditionally. 
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update trigger condition for cloud provider specific E2E jobs

- examples/operating-system-manager.yaml
Update deployment for OSM, used in E2E tests.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update OSM deployment for E2E tests

- test/e2e/provisioning/all_e2e_test.go
Disable flatcar tests for vSphere temporarily until the image is available 
Fixes #
```release-note
None
```
```documentation
None
```
> Disable flatcar tests for vsphere

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- examples/operating-system-manager.yaml
- hack/update-fixtures.sh
- hack/verify-licenses.sh
Upgrade to Go 1.19.4.
Fixes #
/kind feature
```release-note
Machine Controller is now built using Go 1.19.4
```
```documentation
NONE
```
> Upgrade to Go 1.19.4

- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Fix Ci/
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> KubeVirt fix ci (DC)

- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-openstack.yaml
- .prow/provider-vsphere.yaml
Manual cherry pick for https://github.com/kubermatic/machine-controller/pull/1499
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.54] Update trigger condition for cloud provider specific E2E jobs 

- pkg/cloudprovider/validationwrapper.go
When I introduced context handling in #1294, I accidentally made the code cache canceled contexts. I would argue that this is, especially for _canceled_ (not timed out) contexts a major mistake, and even timeouts should probably not be cached (but I'm open for debate :D).
This problem was very obvious in PRs like #1591 or #1592.
/kind bug
```release-note
Cancelled or timed out admission requests are not cached anymore.
```
```documentation
NONE
```
> do not cache canceled/timed out validations

- docs/cloud-provider.md
- examples/aws-machinedeployment.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/clusterv1alpha1machineWithProviderConfig/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/machinesv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineWithProviderConfig/aws.yaml
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Fix E2E tests for AWS.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.54] Fix E2E tests for AWS

- docs/cloud-provider.md
- examples/aws-machinedeployment.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/clusterv1alpha1machineWithProviderConfig/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/machinesv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineWithProviderConfig/aws.yaml
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Fix E2E tests for AWS.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.56] Fix E2E tests for AWS

- test/e2e/provisioning/helper.go
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Fix E2E tests for vSphere

- examples/vmware-cloud-director-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider/vmwareclouddirector/client.go
- pkg/cloudprovider/provider/vmwareclouddirector/provider.go
- pkg/cloudprovider/provider/vmwareclouddirector/types/types.go
This PR adds support for API token authentication for VMware Cloud Director. 
Required for https://github.com/kubermatic/kubermatic/issues/11624
/kind feature
```release-note
VMware Cloud Director now supports authentication using API Token
```
```documentation
NONE
```
> API token authentication support for VMware Cloud Director

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
- hack/verify-licenses.sh
Update Golang version to 1.20.3
Fixes https://github.com/kubermatic/release/issues/11
/kind chore
```release-note
Update Golang version to 1.20.3.
```
```documentation
NONE
```
> Update Golang version to 1.20.3

- pkg/node/eviction/eviction.go
A mistake slipped through in my log refactoring.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> fix missing formatting in log line

- test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> E2E: Fix configuration for spot instances on AWS

- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
Backport for #1646
/kind bug
```release-note
Anexia Provider: Fix nil pointer exception when providing no network configuration
```
```documentation
NONE
```
> [release/v1.56] Anexia Provider: Fix empty network config handling

- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
Backport for #1646
/kind bug
```release-note
Anexia Provider: Fix nil pointer exception when providing no network configuration
```
```documentation
NONE
```
> [release/v1.54] Anexia Provider: Fix empty network config handling

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
- hack/verify-licenses.sh
Update Golang to 1.20.5
/kind chore
```release-note
Update to Go 1.20.5
```
```documentation
NONE
```
> Update Golang to 1.20.5

- examples/operating-system-manager.yaml
Update CRDs for OSM.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update CRDs for OSM

- .prow/provider-vsphere.yaml
- pkg/cloudprovider/provider/vsphere/network.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-multiple-nic.yaml
Add E2E tests for multiple NIC supports for vSphere.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> VSphere: Fine tune multiple NIC support and add E2E tests

- OWNERS_ALIASES
Updating project owners list.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update project owners

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- hack/ci/setup-kind-cluster.sh
Same as #1744, these prow jobs need bumping.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.57] Bump Prow jobs and pin KKP version to match release branch

- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/edge/provider.go
- pkg/providerconfig/types/types.go
Adding a new provider in machine controller to support edge clusters.
Fixes #
/kind feature
```release-note
Support edge provider in machine controller 
```
```documentation
None
```
> Support Edge Provider in Machine Controller

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
- hack/verify-licenses.sh
Fixes #
/kind chore
```release-note
machine-controller is now built using Go 1.22.1
```
```documentation
NONE
```
> Upgrade to Go 1.22.1

- .prow/provider-vsphere.yaml
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/rule.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-anti-affinity.yaml
This is a manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1779
```release-note
vSphere: fix anti-affinity DRS configuration for VMs
```
/kind bug
> [release/v1.59] Fix vSphere anti-affinity

- .prow/provider-vsphere.yaml
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/rule.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-anti-affinity.yaml
This is a manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1779
```release-note
vSphere: fix anti-affinity DRS configuration for VMs
```
/kind bug
> [release/v1.58] Fix vSphere anti-affinity 

- pkg/cloudprovider/provider/aws/provider.go
Fixes #
/kind bug
```release-note
AWS: fix AMI filter for rocky linux
```
```documentation
NONE
```
> Fix AMI filter for rocky linux

- cmd/machine-controller/main.go
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Deprecate cluster-dns flag

- .prow/provider-vmware-cloud-director.yaml
- examples/alibaba-machinedeployment.yaml
- examples/anexia-machinedeployment.yaml
- examples/aws-machinedeployment.yaml
- examples/azure-machinedeployment.yaml
- examples/digitalocean-machinedeployment.yaml
- examples/equinixmetal-machinedeployment.yaml
- examples/gce-machinedeployment.yaml
- examples/hetzner-machinedeployment.yaml
- examples/kubevirt-machinedeployment.yaml
- examples/linode-machinedeployment.yaml
- examples/nutanix-machinedeployment.yaml
- examples/opennebula-machinedeployment.yaml
- examples/openstack-machinedeployment.yaml
- examples/scaleway-machinedeployment.yaml
- examples/vmware-cloud-director-machinedeployment.yaml
- examples/vsphere-datastore-cluster-machinedeployment.yaml
- examples/vsphere-machinedeployment.yaml
- examples/vultr-machinedeployment.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update to latest k8s patch releases for e2e tests

- .golangci.yml
Removing redundant rules.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Cleanup for golangci config

- OWNERS_ALIASES
Fixes #
```release-note
None
```
```documentation
None
```
> Add Navid as a machine controller maintainer

- .prow/provider-kubevirt.yaml
Fixes #
```release-note
None
```
```documentation
None
```
> disable kubevirt tests and connection to dev is fixed

- pkg/cloudprovider/provider/kubevirt/provider.go
Copy the annotations from MachineDeployment to VMI unconditionally.  
Fixes #
/kind feature
```release-note
copy annotations from MD to VMI
```
```documentation
None
```
> Copy annotations to KV VMI

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
This PR will fix a typo in `decode-cloud-init` action in Tinkerbell template client package
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Fix typo in template.go

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/hetzner/provider.go
Add support for Ubuntu 24.04 in providers:
- AWS
- Azure
- Hetzner
- Digital Ocean
- Google 
- equinixmetal
- Openstack 
- vSphere 
- KubeVirt
- VMware Cloud Director
Fixes #
/kind feature
```release-note
support ubuntu 24.04 nobel
```
```documentation
none
```
> Support Ubuntu 24.04 

- pkg/cloudprovider/provider/aws/provider.go
Update ubuntu 24.04 arm image in aws
Fixes #
/kind bug
```release-note
None
```
```documentation
None
```
> Refactor Ubuntu ARM image in AWS 

- examples/kubevirt-local-mounter.yaml
- hack/lib.sh
This PR is to update the new image tag for KKP owned images.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update the new image tag for KKP owned images

- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- sdk/apis/cluster/v1alpha1/conversions/testdata/machinesv1alpha1machine/openstack.yaml
- sdk/cloudprovider/openstack/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-openstack-multiple-networks.yaml
Fixes #263
/kind feature
```release-note
* Added support for connecting Openstack instance to multiple networks
```
```documentation
https://github.com/kubermatic/docs/pull/1922
```
> feat(openstack): add support for defining multiple networks

- pkg/cloudprovider/provider/azure/provider.go
Manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1956
Fixes #
/kind feature
```release-note
Azure: Use `flatcar-container-linux-corevm-amd64` offer for Flatcar and upgrade to version `4230.2.2`
```
```documentation
NONE
```
> [release/v1.61] Use flatcar-container-linux-corevm-amd64 for flatcar on Azure

- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
update rockylinux and rhel image for e2e tests 
Fixes kubermatic/kubermatic#12366
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> update rockylinux and rhel image for e2e tests 
