kubermatic/machine-controller

- cmd/controller/main.go
- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/openstack/helper.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/controller/machine.go
- pkg/ssh/configmap.go
- pkg/ssh/configmap_test.go
- pkg/ssh/key.go
Currently we create a public ssh key on the cloud providers with the same name.
As this breaks when you have multiple clusters, we need to make the name customizable.
> Unique ssh key name

- pkg/controller/machine.go
- pkg/controller/machine_test.go
We got errors from the apiserver on some PATCH requests.
As we are the only controller operating on machines, we can use PUT instead.
> Use PUT instead of PATCH to eliminate the api errors

- cmd/controller/main.go
- examples/machine-controller.yaml
- pkg/controller/machine.go
- pkg/template/functions.go
- pkg/userdata/coreos/userdata.go
- pkg/userdata/coreos/userdata_test.go
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
- pkg/userdata/userdata.go
Make `cluster-dns` flag on the kubelet configurable
> make cluster dns flag on the kubelet configurable

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/userdata/coreos/userdata.go
- pkg/userdata/coreos/userdata_test.go
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
It exports the provider configs so they can be used outside of the machine-controller
> export provider specific configs

- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
Changes the cni plugin download link to a copy on gcp.
That improves the node-startup by up to 2 minutes.
> update cni plugin download link

- cmd/controller/main.go
- pkg/health/readiness.go
- pkg/machines/register.go
We ensure in the main.go if the crd's exist and create them if necessary. If something fails we exit with a fatal. After we ensured that the crd's exist we start the health endpoints. There is absolutely no need to have a dedicated readiness check for the crd as it cannot fail at this moment.
> remove crd readiness check

- test/tools/verify/cmd/main.go
**What this PR does / why we need it**: the dep tool should restore vendored packages that we depend on. There is no need to move the tool to a different location unless we want.
Fixes #47
> running dep ensure is enough.

- .circleci/config.yml
- Makefile
Automatically publish a docker image via CircleCI
Fixes #57 
> Build docker image in circleci pipeline

- .circleci/config.yml
- Makefile
Adjusts the circleci build to use the Maketarget in the projects root dir to ensure we always publish the exact same binary we test, including go version and build flags.
Background: The currently published docker image does not work, because it contains a dynamically linked binary but no linker:
```bash
$ docker run --rm -it --user root kubermatic/machine-controller:4baafd3c477fa64dabefca61c52ccb7171cd4773 sh
/ # apk update && apk add file && file /usr/local/bin/machine-controller 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
v3.7.0-74-g1540930789 [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.0-73-g5f006fb2a0 …
```
> Use projects maketarget for circleci building

- Gopkg.lock
- cmd/controller/main.go
**What this PR does / why we need it**: runs the machine controller via leader election this essentially means that we can have multiple instances and at the same time only one is operational.
before we acquire a lock we actually warm up caches mirroring the state of the API server.
machine controller will be run only if a proper lock was acquired.
note that the program terminates when the leadership was lost.
**Which issue(s) this PR fixes**: Fixes #58
> run machine controller via leader election

- cmd/controller/main.go
- pkg/controller/machine.go
**What this PR does / why we need it**: starts informers correctly, before some informers were not registered at their factories and as a consequence they were not started and synced.
> starts informers correctly

- pkg/cloudprovider/instance/instance.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/controller/machine.go
- pkg/controller/machine_test.go
- Makes aws ami configurable
- Improves aws instance deletion.
AWS instances stay for longer as they go into a `terminated` state for a few minutes when they get deleted.
Fixes #93
> add status handling for better handling of terminating machines. Also make aws ami configurable

- docs/cloud-provider.md
- pkg/cloudprovider/provider/aws/provider.go
Makes the SecurityGroup and InstanceProfile to use configurable.
When not set, a default for both will be created.
Fixes #97
> make securitygroups and instanceprofile configurable

- examples/machine-controller.yaml
Fixes `round_trippers.go:436] POST https://10.96.0.1:443/api/v1/namespaces/kube-system/events 403 Forbidden in 2 milliseconds`
> Allow machine-controller to create events

- cmd/controller/main.go
**What this PR does / why we need it**: this pr sets read and write http timeouts. As by default these timeouts are off, it means that clients can hold up connections indefinitely this in turn can potentially use up all available connections in a pool.
> setting read/write http timeouts

- pkg/userdata/ubuntu/crio.go
- pkg/userdata/ubuntu/crio_test.go
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
Fixes #
Manually verified this by running e2e tests  with cri-o instead of docker:
```
root@machine-controller-test-local ~ # kubectl get nodes testnode-local -o yaml|grep -i cr
creationTimestamp: 2018-03-10T13:26:22Z
- gcr.io/google_containers/kube-proxy-amd64@sha256:19277373ca983423c3ff82dbb14f079a2f37b84926a4c569375314fa39a4ee96
- gcr.io/google_containers/kube-proxy-amd64:v1.9.3
containerRuntimeVersion: cri-o://1.9.9
```
> Fix cri-o by using versioned meta package

- pkg/clusterinfo/configmap.go
- pkg/controller/machine.go
- pkg/userdata/coreos/userdata.go
- pkg/userdata/coreos/userdata_test.go
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
- pkg/userdata/userdata.go
Allow the API server to authenticate itself as valid client for the Kubelets REST api
Fixes #
I manually verified logs and exec through the APIserver work again but do not work when just curling the Kubelet.
> Deploy K8s CACert with kubelet and use it to verify requests

- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/errors/errors.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/controller/machine.go
**What this PR does / why we need it**:  this pull extends cloud providers in a way that they can return terminal errors that indicate if a user intervention is required to recover from faulty situation.
for example a user may provide incorrect credentials which would prevent the system from instantiating or deleting any machines in the cloud. those errors are part of `Machine.Status` and can make their way to the end user.
Fixes #
> return terminal errors when working with cloud providers

- examples/machine-aws.yaml
- examples/machine-digitalocean.yaml
- examples/machine-hetzner.yaml
- examples/machine-openstack.yaml
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/providerconfig/types.go
**What this PR does / why we need it**: reads some fields of cloudProviderSpec from env variables.
the names of variables are hardcoded in the source code and cannot be changed.
there are other mechanisms through which the fields can be set, we only fallback
to reading from env variables when all fails.
Fixes #123 
> reads some fields of cloudProviderSpec from env variables.

- pkg/cloudprovider/provider/aws/provider.go
Sets the max retries to 100 for AWS
> set max retries for AWS

- .circleci/config.yml
- test/e2e/provisioning/aws_e2e_test.go
- test/e2e/provisioning/digital_ocean_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machine-aws.yaml
- test/e2e/provisioning/testdata/machine-digitalocean.yaml
- test/tools/integration/provision_master.sh
- test/tools/integration/run_e2e_tests.sh
- test/tools/verify/cmd/main.go
**What this PR does / why we need it**: 
at the moment we have test scenarios for DO and AWS.
tests can be run in two modes -short and normal.
when run in -short mode only a subset of tests will be tested.
by default e2e tests are disabled, we require special build tag to be provided.
Fixes #
> implements E2E tests for machine controller

- pkg/providerconfig/types.go
- pkg/providerconfig/types_test.go
Adds marshallJSON to configVar types, this avoids having a huge cluttered machine definition when the spec gets written back after defaulting.
Fixes #130 
> Adds marshallJSON to configVar types

- .circleci/config.yml
- test/e2e/provisioning/helper.go
Makes our e2e tests concurrency-safe, also I took the freedom of putting the `check-dependencies` job to the same stage as the `build`, `verify-tool` and `test` steps which gains us ~30 seconds less overall build time
Fixes #
> Add build number to e2e tests

- pkg/cloudprovider/provider/aws/provider.go
- test/e2e/provisioning/testdata/machine-aws.yaml
- test/e2e/provisioning/testdata/machine-digitalocean.yaml
Every image comes with a default root device.
As we dynamically set a device, depending on the user settings, we need to replace the default root device.
Otherwise we end up with a 8gb default device mounted at `/`  and a 50gb SSD unused.
> add os dependend root device path for aws

- pkg/cloudprovider/provider/openstack/provider.go
When no tags are specified we hit a nil-pointer-exception
> fix npe during openstack machine-creation

- test/e2e/provisioning/helper.go
**What this PR does / why we need it**: the golang test runtime waits for individual subtests to complete before reporting the status. if one of them is blocking/waiting and the global timeout is reached the status will not be reported/visible.
the global timeout is set to 20 minutes and the verify tool waits up to 60 hours for a machine to show up.
thus one faulty scenario prevents from showing the whole test runs status which is confusing because it looks like all tests are broken.
Fixes #
> decreases verify tool timeout

- pkg/controller/machine.go
Use a exponential backoff queue with 1 second as minimal delay to prevent being blocked due to too many api requests
> use exponential back-off queue

- pkg/cloudprovider/provider/azure/provider.go
We need this to use the RawConfig struct in the cluster-controller
> cloudprovider/Azure: export RawConfig for use by other packages

- pkg/cloudprovider/provider/openstack/helper.go
remove setting of openstack endpoint availability, as some installations do not expose it and it causes no resources to be returned.
> remove setting of openstack endpoint availability

- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/controller/machine.go
- pkg/controller/machine_test.go
- pkg/providerconfig/types.go
We currently add the delete finalizer to the machine at the very
beginning of the sync loop without even validating it before.
This moves the finalizer creation to happen right before the creation.
This will drastically reduce the occurence of situations where the
finalizer has to be manually deleted.
Related issue: #224
Fixes #224 
> Add the delete finalizer at the latest possible point

- pkg/controller/machine.go
Ensure a instance gets recreated after the instance got deleted at the cloud-provider.
Otherwise if a nodeRef exists on the machine it will enter a fail loop.
> ensure a instance gets recreated after the instance got deleted at the cloud-provider

- pkg/userdata/centos/testdata/docker-1.13-aws.golden
- pkg/userdata/centos/userdata.go
This is only required on CentOS as we do not install via package in
Ubuntu.
Fixes #
> Avoid overwrite of cloud provider args in centos

- cmd/controller/main.go
- examples/alerts.yaml
- pkg/controller/machine.go
- pkg/controller/metrics.go
If a machine can't be deleted we want to alert on it.
With the old approach we had state in the metrics that we couldn't delete. Hence a machine that once existed still had metrics which made us unable to alert on the metric, even when the machine was long gone.
By using the Prometheus collector pattern we simply query the informers to give us a list of machines and nodes. We iterate over those lists and forget about the state afterwards.
This improvement allows metrics of deleted machines to not show up anymore.
We can now tell, that if a `machine_controller_machine_deleted` metric is there for more than 10min the machine is not able to be deleted.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> Use Prometheus collector pattern for stateless metrics

- cmd/controller/main.go
- pkg/controller/machine.go
This allows creating multiple instance of machine controller, e.g. for testing.
> use an instantiated prometheus registry instead of the global instance

- .circleci/config.yml
- Gopkg.lock
- pkg/client/informers/externalversions/factory.go
- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine.go
- pkg/controller/machine_test.go
This will allow cloud provider packages to add/remove finalizers on machine objects.
>  pass a machine object updater to provider Create/Delete functions

- pkg/userdata/centos/testdata/docker-1.13-kubelet-v1.11-aws.golden
- pkg/userdata/centos/testdata/docker-1.13-kubelet-v1.8-aws.golden
- pkg/userdata/centos/testdata/docker-1.13-kubelet-v1.9-aws.golden
- pkg/userdata/centos/userdata.go
- pkg/userdata/ubuntu/testdata/docker-1.13-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-1.13-kubelet-1.11-aws.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/testdata/docker-17.03-openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/userdata.go
For kubelet flags a systemd-unit overwrite is used to specify DNS options.
What is missing is the clearing out $KUBELET_DNS_ARGS (from kubeadm)
to make the overwrite take any effect.
This fixes the userdata for ubuntu and centos.
Fixes #
> Fix DNS options for ubuntu and centos.

- examples/machine-aws.yaml
- examples/machine-azure.yaml
- examples/machine-digitalocean.yaml
- examples/machine-hetzner.yaml
- examples/machine-openstack.yaml
- examples/machine-vsphere.yaml
- pkg/controller/machine/machine.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machine-aws.yaml
- test/e2e/provisioning/testdata/machine-azure.yaml
- test/e2e/provisioning/testdata/machine-digitalocean.yaml
- test/e2e/provisioning/testdata/machine-hetzner.yaml
- test/e2e/provisioning/testdata/machine-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machine-openstack.yaml
- test/e2e/provisioning/testdata/machine-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machine-vsphere.yaml
- test/tools/integration/Makefile
This makes it easier for higher-level controllers like the machineset controller to generate machines, as it doesn't have to set their name anymore.
Fixes #
> Default nodename to machine name

- docs/cloud-provider.md
- examples/machine-openstack.yaml
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machine-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machine-openstack.yaml
- test/tools/integration/hetzner.tf
- test/tools/integration/provision_master.sh
The image to be used in e2e tests on OpenStack was configured to be `ubuntu`. This forced using the same image in all configurations, including branches using both Ubuntu Xenial and Bionic. With this change, specific version image is named.
```release-note
NONE
```
> use ubuntu 18.04 image on openstack

- pkg/userdata/ubuntu/testdata/docker-17.12-dist-upgrade-on-boot-aws.golden
- pkg/userdata/ubuntu/testdata/docker-18.06-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/ubuntu/testdata/docker-18.06-openstack-multiple-dns.golden
- pkg/userdata/ubuntu/testdata/docker-18.06-openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/userdata.go
Ubuntu Bionic uses systemd-resolve and therefore /etc/resolv.conf is not available - the default path the kubelet mounts to pods.
The new path needs to be specified on the kubelet, what this PR does.
> set path to resolv.conf on kubelet for bionic

- pkg/cloudprovider/provider/openstack/helper.go
- pkg/cloudprovider/provider/openstack/provider.go
This PR will reduce the critical time, in which a concurrent machine-controller can steal an already assigned FloatingIP.
As a cheap additional hack, a check was added to verify that the assigned FloatingIP is still assigned after 3 seconds.
Fixes #313
> Improve FloatingIP allocation on OpenStack

- cmd/controller/main.go
This adds the same Prometheus process and go metrics as the default
Registry[0] uses
Resolves #324
[0] https://github.com/prometheus/client_golang/blob/v0.8.0/prometheus/registry.go#L51-L53
Fixes #
> Add default prometheus process and go metrics

- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/controller/machine/machine.go
This PR will ensure that we remove the finalizers only when we know that all actions have been successful.
Being more specific:
- Only when the instances at the cloud provider cannot be found anymore*, the deletion will be considered successful and the finalizer will be removed.
*For AWS the instance state `terminated` is considered deleted as well.
- The node object will only be removed in case the cloud provider instance is gone - this will ensure that the kubelet does not restart & registers again before the instance got shutdown.
Fixes #345
> Remove finalizers when instance is gone

- pkg/cloudprovider/provider/openstack/helper.go
Fix nil pointer exception during OpenStack FloatingIP assignment
> fix nil pointer exception during OpenStack FloatingIP assignment

- pkg/controller/machine/machine.go
This PR aims to simplify the clearing of ErrMessage and ErrReason on the Machine object, by putting the logic above the `syncHandler`.
This will ensure that the controller always removes the error in case of a successful sync.
> simplify clearing of a machine error

- docs/vsphere.md
- pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
- pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
- pkg/userdata/centos/userdata.go
- pkg/userdata/centos/userdata_test.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/testdata/openstack.golden
- pkg/userdata/ubuntu/testdata/version-1.10.10.golden
- pkg/userdata/ubuntu/testdata/version-1.11.3.golden
- pkg/userdata/ubuntu/testdata/version-1.12.1.golden
- pkg/userdata/ubuntu/testdata/version-1.9.10.golden
- pkg/userdata/ubuntu/testdata/vsphere.golden
- pkg/userdata/ubuntu/userdata.go
- pkg/userdata/ubuntu/userdata_test.go
- test/e2e/provisioning/all_e2e_test.go
Fixes #166 
```release-note
NONE
```
> Add CentOS support to VSphere

- pkg/cloudprovider/provider/openstack/provider.go
Encode OpenStack quota errors as terminal errors
```release-note
Correctly identify quota errors as terminal errors
```
> encode openstack quota errors as terminal errors

- pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
- pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
- pkg/userdata/centos/userdata.go
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
- pkg/userdata/coreos/userdata.go
- pkg/userdata/helper/kubelet.go
- pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/testdata/openstack.golden
- pkg/userdata/ubuntu/testdata/version-1.10.10.golden
- pkg/userdata/ubuntu/testdata/version-1.11.3.golden
- pkg/userdata/ubuntu/testdata/version-1.12.1.golden
- pkg/userdata/ubuntu/testdata/version-1.9.10.golden
- pkg/userdata/ubuntu/testdata/vsphere.golden
- pkg/userdata/ubuntu/userdata.go
Never override the hostname on AWS nodes.
Kube-Proxy uses the `hostname= to lookup the `corev1.Node` object its running on.
On AWS nodes, the name of the `corev1.Node` is always the private dns name in AWS.
This is a requirement of the AWS code in kubernetes. Thus, manually overriding the hostname in the OS is not useful.
Instead if leads to the error messages: 
```
W1023 13:23:23.835678       5 server.go:601] Failed to retrieve node info: nodes "aws-coreos-1-10-8-node-2" not found
W1023 13:23:23.835871       5 proxier.go:306] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
```
```release-note
NONE
```
> Never override the hostname on AWS nodes

- pkg/cloudprovider/provider/openstack/helper.go
Currently https://github.com/kubermatic/machine-controller/blob/111a9df8af5475a84432ade9e5ed8f426d690065/pkg/cloudprovider/provider/openstack/helper.go#L390 runs into a nullpointer dereference, as the `ip` variable is only defined in the if-context.
The err variable is not (re-)defined, as its used above already.
```release-note
* Fix a nullpointer dereference in openstack IP assignment.
```
> Fix nullpointer dereference in openstack helper.go

- pkg/cloudprovider/provider/aws/provider.go
This PR will use dynamic loading of AMI ID's for the relevant operating system images, instead of relying on a static hard coded map.
Fixes #357
```release-note
AWS: Always use the latest AMI available, when none is specified
```
> [AWS] always use latest AMI ID

- cmd/controller/main.go
- examples/machine-controller.yaml
- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine/machine.go
- test/e2e/provisioning/migrateuidscenario.go
- test/e2e/provisioning/verify.go
Fixes #
Initially I started off by passing down a new struct with all required info into the cloudproviders `New()`. This poses a problem thought, as both the `MachineControllerMetrics` and the `AdmissionWebhook` call that `New()`, hence the change would result in being forced to have a `MachineUpdater` and a `PVLister` to be available in the metrics and webhook even thought its not used at all. 
```release-note
NONE
```
> Pass PVLister down to providers Create/Delete

- Gopkg.lock
- Gopkg.toml
- pkg/cloudprovider/provider/aws/provider.go
- vendor/github.com/patrickmn/go-cache/CONTRIBUTORS
- vendor/github.com/patrickmn/go-cache/LICENSE
- vendor/github.com/patrickmn/go-cache/cache.go
- vendor/github.com/patrickmn/go-cache/sharded.go
This PR introduce a simple library which can be used for caching.
In this case, the AMI ID in the AWS provider gets cached.
The long term goal is to reduce the number of API calls to AWS.
It will speed up the machine processing.
```release-note
NONE
```
> AWS - Add cache for the AMI ID's

- pkg/admission/machines.go
- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- test/e2e/provisioning/migrateuidscenario.go
Remove deprecated changed return parameter on cloud provider implementations.
```release-note
NONE
```
> Remove deprecated changed return parameter on cloud provider implementations

- examples/machine-controller.yaml
- pkg/admission/machines.go
- pkg/cloudprovider/cache/cloudprovidercache.go
- pkg/cloudprovider/cache/cloudprovidercache_test.go
- pkg/cloudprovider/provider.go
- pkg/cloudprovider/validationwrapper.go
Fixes #397
Fixes #
Log from the webhook, first eight lines are on the first run of tests, second eight lines on the second run:
```
$ k logs machine-controller-webhook-854d6d9959-ms6tx -f |grep 'validationwrapper.go'
I1108 17:02:03.779021       1 validationwrapper.go:41] Got cache miss for validation
I1108 17:02:03.797608       1 validationwrapper.go:41] Got cache miss for validation
I1108 17:02:03.799101       1 validationwrapper.go:41] Got cache miss for validation
I1108 17:02:03.799295       1 validationwrapper.go:41] Got cache miss for validation
I1108 …
```
> Cache cloudprovider validation

- Makefile
- hack/ci-e2e-test.sh
- test/tools/integration/Makefile
This PR updates Makefiles and adds a script for the e2e test so that we can directly use them in prowjobs.
This is a first step for moving from CircleCI to Prowjobs: https://github.com/kubermatic/machine-controller/issues/400.
```release-note
NONE
```
> Update makefiles for migrating to prow

- Makefile
- README.md
- examples/machine-controller.yaml
- test/tools/integration/Makefile
- test/tools/integration/hetzner.tf
- test/tools/integration/provision_master.sh
Fixes various issues with the local test env:
* HZ token env var name in README was wrong
* Missing default for the `E2E_SSH_PUBKEY` env var caused the provisioning script to fail
* Manifests were not applied automatically
* The `e2e-cluster` Make target was missing the `machine-controller` and `webhook` dependencies
* The defaulting for the `BUILD_ID` was broken
* The defaulting for `BUILD_ID` was hardcoded to `local`, allowing only one person to use this at a time due to Hetzner server name restriction
* The binaries for `machine-controller` and `webhook` were always synced to the kubeadm …
> Improve local testing

- examples/openstack-machinedeployment.yaml
- pkg/cloudprovider/provider/openstack/provider.go
Openstack Region should be put into secret..
'Region' is secret in openrc file (params to link to keystone of openstack)
Fixes #
```
Region should be a secret , not a common user settings
```
> Move region into secret of openstack

- examples/machine-controller.yaml
Remove kubeadm specific RBAC manifests. Kubeadm does not get used anymore.
```release-note
NONE
```
> remove kubeadm specific RBAC manifests

- pkg/cloudprovider/cloud/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/validationwrapper.go
- pkg/controller/machine/machine.go
- test/e2e/provisioning/migrateuidscenario.go
This PR changes the way we delete cloud provider resources.
Instead of doing a one-shot delete call, the controller will now continuously call `Cleanup` on the cloud provider implementation until it returns `true` - stating that all resources are gone.
Fixes #383
```release-note
NONE
```
> replace delete with cleanup to ensure proper deletion of all cloud provider resources

- pkg/cloudprovider/provider/openstack/helper.go
- pkg/cloudprovider/provider/openstack/provider.go
This change will add the desired image name to the request so the API takes care of filtering.
This will avoid that the controller checks all existing images.
```release-note
NONE
```
> filter images by name when loading the image from the openstack api

- pkg/cloudprovider/provider/aws/cloudconfig.go
- pkg/cloudprovider/provider/aws/cloudconfig_test.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/aws/testdata/simple-config.golden
- pkg/cloudprovider/provider/azure/cloudconfig.go
- pkg/cloudprovider/provider/azure/provider.go
Expand cloud config structs.
The AWS config has been added for completeness.
```release-note
NONE
```
> Expand cloud configs

- pkg/cloudprovider/provider/vsphere/provider.go
Limit the amount of CPUs per node to a maximum of 8 on VSphere.
Fixes #https://github.com/kubermatic/kubermatic/issues/2139
/
```release-note
Limit amount of CPUs per node to a maximum of 8 on VSphere
```
> Limit node CPUs on VSphere

- pkg/admission/machinedeployments_test.go
- pkg/admission/machinedeployments_validation.go
Fixes #
Upstream by now has defaulting for this, once #416 is done I will change the Webhook to use the defaulting from upstream and add the tests to upstream.
```release-note
none
```
> Fix MachineDeployment defaulting

- cmd/provision/README.md
This PR adds a readme (proposal-ish) which describes a potential replacement for our node provisioning.
Topics to cover:
```release-note
NONE
```
> add document to describe the provision command

- hack/ci-e2e-test.sh
- test/tools/integration/Makefile
- test/tools/integration/cleanup_machines.sh
- test/tools/integration/output.tf
- test/tools/integration/provider.tf.disabled
- test/tools/integration/provision_master.sh
- test/tools/integration/variables.tf
Fixes #
```release-note
none
```
> Use S3 bucket for CI e2e state

- hack/ci-e2e-test.sh
- pkg/cloudprovider/provider/aws/provider.go
Fixes #358
Fixes #
```release-note
A terminal error will be set if an AMI is used whose terms were not accepted
```
/assign @mrIncompetent 
Result looks like this:
```
$ k get machine machinedeployment-kubermatic-rxhxx5tprc-xntcw-78ddbf7d89-plf9f -o json|jq '.status'
{
"errorMessage": "An error of type = AMI terms not accepted, with message = OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce\n\tstatus code: 401, request …
```
> Set a terminal error if AMI terms were not accepted

- pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
- pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
- pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
- pkg/userdata/coreos/userdata.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/testdata/openstack.golden
- pkg/userdata/ubuntu/testdata/version-1.10.10.golden
- pkg/userdata/ubuntu/testdata/version-1.11.3.golden
- pkg/userdata/ubuntu/testdata/version-1.12.1.golden
- pkg/userdata/ubuntu/testdata/version-1.9.10.golden
- pkg/userdata/ubuntu/testdata/vsphere.golden
- pkg/userdata/ubuntu/userdata.go
Fixes  CVE-2019-573 for Ubuntu and CoreOS. For CentOS there is no updates package available yet
Fixes #
```release-note
none
```
> Fix CVE-2019-573 for Ubuntu and CoreOS

- cmd/controller/main.go
- hack/run-machine-controller.sh
Profiling and debugging issues with machine-controller, e.g. orphaned goroutines in #447
```release-note
NONE
```
> add a cmdline flag to enable profiling

- cmd/controller/main.go
This is made to ensure that the status of MachineDeployments and
MachineSets converges in less than 10 hours.
Fixes #
```release-note
Periodically reconcile MachineDeployments and MachineSets
```
/assign @mrIncompetent 
CC @xrstf
> Configure a five minute resync period for upstream controllers

- README.md
- test/e2e/provisioning/helper.go
Allows easily running the tests against any environment when running them locally. Previously, the hardcoded path required copying/linking the kubeconfig to `$(go env GOPATH)/src/github.com/kubermatic/machine-controller/.kubeconfig`
```release-note
NONE
```
> e2e tests: respect local KUBECONFIG env before using hardcoded path

- examples/gce-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/service.go
In order to better support network placement of nodes
```release-note
GCE network placement controls
```
> Support for network configuration of GCE instances

- README.md
Include Linode in the README.md list of clouds where nodes can be deployed.
I missed this in: https://github.com/kubermatic/machine-controller/pull/451
I placed Linode in the list to avoid changing the word "cloud" (should it have always been "clouds")?
> add Linode to README.md

- cmd/controller/main.go
- pkg/controller/machine/kubeconfig.go
- pkg/controller/machine/machine.go
Allows to use the token from a configured service account as bootstrap token instead of dynamically creating one
Fixes #
```release-note
none
```
> Allow using a serviceAccount token instead of bootstrap tokens

- test/e2e/provisioning/testdata/machinedeployment-hetzner.yaml
- test/tools/integration/hetzner.tf
Use `nbg1` as region for Hetzner Cloud instances during e2e tests (Also master)
```release-note
NONE
```
> Use nbg1 as region for Hetzner Cloud instances during e2e tests

- test/tools/integration/hetzner.tf
Reduce e2e control plane size. We don't need such a big node if we have a dedicated control plane for each provider.
```release-note
NONE
```
> Reduce e2e control plane size

- Gopkg.lock
- Gopkg.toml
- pkg/apis/cluster/v1alpha1/conversions/conversions.go
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/azure.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/digitalocean.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/hetzner.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/linode.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/openstack.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere-static-ip.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere.yaml
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/common/consts.go
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/delete_policy.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/machine.go
Updates the cluster-api dependency so selective downscaling of MachineSets is possible, xref kubernetes-sigs/cluster-api#726
Fixes #
```release-note
none
```
> Update cluster-api to add selective downscaling

- pkg/cloudprovider/provider/openstack/cloudconfig.go
- pkg/cloudprovider/provider/openstack/cloudconfig_test.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/testdata/bs-defaulting-config.golden
Use automatic detection of the OpenStack BS version.
```release-note
Use automatic detection of the OpenStack BS version in the Kubelet's cloud-config
```
> use automatic detection of the OpenStack BS version

- test/e2e/provisioning/helper.go
- test/tools/integration/provision_master.sh
Adds Kubernetes 1.14 to the e2e tests. Also moves the e2e tests controller from 1.13 to 1.14
Fixes #
```release-note
none
```
> Test Kubernetes 1.14

- cmd/controller/main.go
- examples/machine-controller.yaml
- pkg/admission/admission.go
- pkg/admission/machines.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine/machine.go
- pkg/node/eviction/eviction.go
Disables logging of leader election related messages by default. Additionally moves all our debug log to level 3, as level 4 contains the leader election log
Fixes #424 
```release-note
none
```
> Dont show leader election log by default

- pkg/admission/machines.go
- pkg/admission/machines_test.go
Add validation for ssh keys.
Fixes #469
A alerting rule for existing machines will be added to Kubermatic
```release-note
Validate SSH Keys
```
> add validation for ssh keys

- pkg/controller/machine/machine.go
We currently don't re-enque machines after instance creation. That means if the creation fails silently, we will never notice because nothing triggers the reconciliation of the machine.
Fixes #
```release-note
none
```
> Re-check after instance creation

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
- pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
- pkg/userdata/ubuntu/testdata/openstack.golden
- pkg/userdata/ubuntu/testdata/version-1.10.10.golden
- pkg/userdata/ubuntu/testdata/version-1.11.3.golden
- pkg/userdata/ubuntu/testdata/version-1.12.1.golden
- pkg/userdata/ubuntu/testdata/version-1.9.10.golden
- pkg/userdata/ubuntu/testdata/vsphere.golden
Disable swap on lentos so Kubelet starts. 
We already do it for Ubuntu [here](https://github.com/kubermatic/machine-controller/blob/master/pkg/userdata/ubuntu/provider.go#L223-L225) for exactly the same reason, so we should do it for centos as well. As discussed with @mrIncompetent and @thz in Slack.
Using exact same language/code for centos as Ubuntu.
```release-note
Disable swap on centos like on ubuntu
```
> Add swapoff to centos so kubelet starts

- pkg/cloudprovider/provider/gce/config.go
This needs to be exported for adding GCP support in Kubermatic. 
for https://github.com/kubermatic/kubermatic/issues/3120
```release-note
NONE
```
> Make CloudProviderSpec public so that it can be exported

- cmd/controller/main.go
- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
This adds a flag to the machine-controller to skip the eviction for machines which have a deletion timestamp which is older than 2 hours.
The duration can be configured via flag.
Fixes #481
```release-note
Add 2 hour timeout to the node eviction
```
> add timeout for node eviction to skip evictions which won't succeed

- examples/gce-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/service.go
- test/e2e/provisioning/testdata/machinedeployment-gce.yaml
Allows to create instances on GCP without a public IP. Note that this also swaps the default to not assign a public IP by default.
Fixes #
```release-note
none
```
/assign @mrIncompetent 
CC @nikhita
> Allow creating GCP instances without public address

- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider.go
This PR allows specifying tags for GCE instances. This is necessary so that we can add firewall support in kubermatic.
For https://github.com/kubermatic/kubermatic/pull/3350
```release-note
NONE
```
/cc @themue
> gce: allow specifying tags for instances

- pkg/cloudprovider/provider/vsphere/provider.go
In case `uploadAndAttachISO()` fails the already created VM gets destroyed.
Fixes #377 
```release-note
NONE
```
> vSphere VM cleanup after ISO failure

- Makefile
`check-dependencies` should fail when vendor is directly updated without updating `Gopkg.toml`.  To have that, we should be using `dep check` instead of `dep status`.
Ref:
- https://golang.github.io/dep/docs/daily-dep.html#key-takeaways
- https://golang.github.io/dep/docs/ensure-mechanics.html#staying-in-sync
Related https://github.com/kubermatic/kubermatic/pull/3422
```release-note
NONE
```
> Fix check-dependencies to use dep check

- pkg/cloudprovider/provider/gce/cloudconfig.go
- pkg/cloudprovider/provider/gce/cloudconfig_test.go
Ref: https://github.com/kubermatic/kubermatic/pull/3350#discussion_r281632201
/cc @alvaroaleman @themue 
```release-note
NONE
```
> Expand CloudConfig for GCE

- docs/vsphere.md
- examples/vsphere-machinedeployment.yaml
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
Makes the vsphere root disk size extendable. 
Fixes #376 
```release-note
It is now possible to configure the root disk size of vSphere machines
```
/hold
Until vsphere e2e tests are re-activated and I can write an e2e test for this
> Make vsphere root disk size extendable

- pkg/cloudprovider/provider/gce/cloudconfig.go
- pkg/cloudprovider/provider/gce/cloudconfig_test.go
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider.go
The controller-manager crashes with:
```
F0510 08:44:10.389281       1 controllermanager.go:213] error building controller context: cloud provider could not be initialized: could not init cloud provider "gce": metadata: GCE metadata "instance/network-interfaces/0/network" not defined
```
This comes from https://github.com/kubernetes/kubernetes/blob/b9ccdd2824c8df7711d3aed985d3e1b549a40de3/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L787-L791 when it tries to find the networkName via metadata but fails...which occurs due to https://github.com/kubernetes/kubernetes/blob/b9ccdd2824c8df7711d3aed985d3e1b549a40de3/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L342-L354
```release-note
NONE
```
> Add NetworkName and SubnetworkName to GCP cloudconfig

- pkg/cloudprovider/provider/gce/cloudconfig.go
- pkg/cloudprovider/provider/gce/cloudconfig_test.go
Ref: https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/gce/gce.go#L305
I'm not adding it to the CloudProviderConfig because I intend to default it to `nil` in Kubermatic.
/cc @alvaroaleman @mrIncompetent 
```release-note
NONE
```
> Add TokenURL in GCE CloudConfig

- pkg/cloudprovider/provider/openstack/provider.go
Fixes the Openstack validation to now allow an empty image and flavor. It is possible that there is an image or flavor without a name in the openstack API which will then be used.
/assign @nikhita 
Fixes #
```release-note
none
```
> Openstack validation: Force passing in image and flavor

- pkg/cloudprovider/provider/gce/config.go
This PR fixes breaking change introduced in #510 
```release-note
GCE public IP by default
```
> GCE public IP by default

- pkg/cloudprovider/provider/packet/provider.go
Removes the unused `OS` field from the packet providerspec
Fixes #
```release-note
none
```
> Remove unused `os` field from the packet spec

- .golangci.yml
- cmd/controller/main.go
- pkg/apis/cluster/v1alpha1/migrations/migrations.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/packet/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/types/types.go
- pkg/cloudprovider/validationwrapper.go
- pkg/controller/machine/machine.go
- test/e2e/provisioning/migrateuidscenario.go
Extends cloudproviderinterface to accept providerData on GET
Ref: https://github.com/kubermatic/machine-controller/pull/531#discussion_r284574679
Unfortunately the PR got bigger than expected, I recommend reviewing it commit by commit :S
Fixes #
```release-note
none
```
> Extend cloudproviderinterface to accept providerData on GET

- examples/azure-machinedeployment.yaml
- pkg/cloudprovider/provider/azure/provider.go
Signed-off-by: Artiom Diomin <kron82@gmail.com>
Make MC read ENV variables with credentials as documented in examples
```release-note
Azure: start reading credentials from ENV
```
> Azure: start reading credentials from ENV

- Gopkg.lock
- Gopkg.toml
- pkg/apis/cluster/v1alpha1/conversions/conversions.go
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/azure.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/digitalocean.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/hetzner.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/linode.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/openstack.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere-static-ip.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere.yaml
- vendor/sigs.k8s.io/cluster-api/logos/LICENSE.md
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
- vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/machinedeployment_controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/delete_policy.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/machineset_controller.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/status.go
- vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/util.go
- vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
This allows us to use foreground deletion:
https://github.com/kubernetes-sigs/cluster-api/pull/953
Fixes #
```release-note
none
```
> Update cluster-api to 2ec456177c0e8f0a903f4e746d44baaae54cc591

- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
- pkg/node/eviction/eviction.go
Fixes #541 #542 
```release-note
Before an eviciton is attempted, the machine-controller will now check if there is a possible target and if no, omit it
```
> Skip eviction if there is no possible target

- pkg/cloudprovider/provider/gce/cloudconfig.go
- pkg/cloudprovider/provider/gce/cloudconfig_test.go
- pkg/cloudprovider/provider/gce/provider.go
`NodeTags` is the list of tags to use on firewall rules for load balancers. This is necessary for LBs to work on GCP.
For https://github.com/kubermatic/kubermatic/pull/3572
Ref:
- https://github.com/kubernetes/kubernetes/blob/ef7808fec57284582c7bf3fc834570e5769df83e/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L121
- https://github.com/kubernetes/kubernetes/blob/ef7808fec57284582c7bf3fc834570e5769df83e/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_external.go#L979-L981
```release-note
NONE
```
> Add NodeTags to GCE CloudConfig

- pkg/cloudprovider/provider/azure/provider.go
Fixes a typo in the azure provider
Fixes #
```release-note
```
> typo in vmSize for azure provider.go

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
With this change, docker on CentOS now logs to json-file rather than
journald. This is required in order to make the conformance-tests pass on
machine-controller-generated nodes. Without it, a changing subset of the
tests constantly failed, their commonon denominator: They look for a
string in the output of container logs and get an empty log and no error
back.
Successful conformance tests: https://prow.loodse.com/view/gcs/prow-data/logs/pull-kubermatic-e2e-aws-centos-1.14/1139930128395014144
Fixes #
```release-note
The Docker log driver on CentOS was changed …
```
> Fix conformance tests for CentOS

- pkg/userdata/coreos/coreos.go
- pkg/userdata/coreos/provider.go
- pkg/userdata/coreos/provider_test.go
- pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
- pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
- pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
- pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
For certain setups, mainly the ones using the Container Linux Update Operator,
it's required to have the CoreOS update-engine enabled while disabling
locksmithd. Previously, you could only enable/disable these together.
Thos patch adds two options so that they can be individually tweaked
while also retaining the old behaviour.
This patch also fixes the test data, as my patch introduced some
whitespace differences.
Fixes #
```release-note
Add Container Linux specific config options: `disableLocksmithD` and `disableUpdateEngine`, to allow for more fine-grained …
```
> Enable fine-grained control over coreos update.

- examples/hetzner-machinedeployment.yaml
- pkg/cloudprovider/provider/hetzner/provider.go
Allows to configure labels for hcloud/hetzner machines
Fixes #
```release-note
none
```
> Hcloud: Allow configuring labels

- pkg/cloudprovider/provider/openstack/cloudconfig.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/testdata/bs-defaulting-config.golden
- pkg/cloudprovider/provider/openstack/testdata/config-with-special-chars.golden
- pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
- pkg/providerconfig/types.go
This PR adds support to set the TenantID for OpenStack machines.
Fixes #568
```release-note
Add support to set the TenantID for OpenStack machines.
```
/hold 
needs at least a manual test run
> Add Openstack tenant id

- pkg/cloudprovider/provider/openstack/cloudconfig.go
- pkg/cloudprovider/provider/openstack/cloudconfig_test.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/testdata/config-with-special-chars.golden
- pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
This makes the Openstack `node-volume-attach-limit` cloud-config setting configurable in the openstack machine settings. If set, the value will be written to cloud-config when the node is created.
The kubelet will write this to the node object (status.allocatable.attachable-volumes-cinder), where the scheduler will use it if configured to do so ("MaxCinderVolumeCount" scheduler predicate; not enabled by default).
```release-note
Openstack node-volume-attach-limit setting configurable per machine
```
> Make Openstack NodeVolumeAttachLimit configurable

- pkg/providerconfig/types.go
Generates swagger.json with the typo in kubermatic :P 
```release-note
NONE
```
> Fix typo in the GlobalObjectKeySelector type name

- pkg/controller/machine/machine.go
Fix typo in error message
```release-note
NONE
```
> Fix typo in error message

- examples/aws-machinedeployment.yaml
- pkg/cloudprovider/provider/aws/provider.go
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
This PR makes the public IP assignment for AWS instances optional.
```release-note
NONE
```
> Aws optional public ip

- pkg/providerconfig/types.go
Or else would lead to:
```
credentialsReference:
key: ""
name: credential-aws-sscdddgm5n
namespace: kubermatic
```
```release-note
NONE
```
> providerconfig: add omitempty for key in GlobaObjectKeySelector

- CONTRIBUTING.md
Add a note to the contributing guidelines that we require all commits in a PR to be signed off and how to retroactively signoff commits.
```release-note
NONE
```
/assign @alvaroaleman @nikhita
> Add a note about signing-off existing commits to the contributing guidelines

- pkg/cloudprovider/provider/vsphere/helper.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
This ensures that we used the devices of the cloned VM to create our change specifications.
Otherwise the change specifications contain references to the template VM.
```release-note
NONE
```
> vSphere: Reconfigure VM's based on the clone's devices, not the template

- pkg/cloudprovider/provider/vsphere/helper.go
This will ensure that we clone VM's onto the correct datastore.
```release-note
NONE
```
> vSphere: set VM location

- Gopkg.lock
- pkg/controller/machine/kubeconfig.go
Avoids creating a cache for SAs and Secrets by unmarshaling them into unstructured.Unstructured, then into the actual type.
Fixes #
```release-note
none
```
> Do not create caches for ServiceAccounts and secrets

- pkg/userdata/manager/plugin.go
This PR changes the userdata manager to pass the whole env down to userdata plugins, allowing to pass down arbitrary values from the top-level env.
Fixes #
```release-note
none
```
> Allow passing arbitrary data onto userdata plugin

- pkg/controller/machine/kubeconfig.go
Fixes #
```release-note
none
```
/assing @thz
> Set current-context for bootstrap kubeconfig

- Gopkg.lock
- Gopkg.toml
- examples/hetzner-machinedeployment.yaml
- pkg/cloudprovider/provider/hetzner/provider.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/action.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/client.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/datacenter.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/error.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/image.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/iso.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/location.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/network.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/schema.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/floating_ip.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/location.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/network.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/volume.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/server_type.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/ssh_key.go
- vendor/github.com/hetznercloud/hcloud-go/hcloud/volume.go
This PR implements support for Hetzner Private Networks. A new optional field is added to the Hetzner spec called `network` that consumes a network ID or name. It is expected that the network already exists, i.e. that it's created by the user.
To make this work I had to vendor the latest version of the `hcloud-go` library which includes support for networks.
Fixes #599 
```release-note
Add support for Hetzner Private Networks
```
> Add support for Hetzner Private Networks

- pkg/cloudprovider/provider/aws/provider.go
AvailabilityZone, InstanceProfile, AMI, AssignPublicIP get an omitempty.
Fixes #
```release-note
NONE
```
> aws - omitempty for cloudProviderSpec attributes

- pkg/cloudprovider/provider/azure/provider.go
Currently we use `kubermatic` as SSH username, which is impossible to figure out without reading the code. This PR changes that to use centos/ubuntu for centos or ubuntu and core for coreos, as that is what is the default of the cloud image and what is done almost everywhere else.
Also the current approach is problematic for whitelabeling.
Fixes #
```release-note
The SSH username on Azure is now ubuntu for Ubuntu, centos for CentOS and core for CoreOS
```
> Azure: Use standard usernames for SSH

- test/tools/integration/provision_master.sh
Fixes the `pull-machine-controller-e2e-ubuntu-upgrade` test by disabling the `join-cluster-timeout` for it.
Fixes #
```release-note
none
```
> Fix upgrade test

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/ubuntu/testdata/openstack.yaml
- pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
- pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
- pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
- pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
- pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
- pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
- pkg/userdata/ubuntu/testdata/vsphere.yaml
Set mode for files with potentially sensitive information like cloud
credentials to 0600. This change is for CentOS and Ubuntu workers,
CoreOS already had proper permissions.
```release-note 
Limit cloud-config and bootstrap-kubelet.conf filesystem permissions
```
> Restrict file system permissions for config files

- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
* Removes the tag-based handling for multiple machines with the same name, as vsphere doesn't seem to support that anyways, seen e.G. in https://github.com/kubermatic/machine-controller/issues/636
* Replaces the tag-based marker used to indicate if creation was successful with a wrapper around the `Create` that will call `Cleanup` if there was an error. This is backwards-compatible (using an annotation or sth would result in all vsphere machines prior to this change getting re-created), more intuitive (no-one expects a function called GET to mutate things) and removes the need for the machine-controller to have permissions to manage tags
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
> vSphere: Remove tag-based handling for multiple machines with the same name

- pkg/cloudprovider/provider/vsphere/provider.go
Makes the vSphere provider use absolute paths when trying to find vms to avoid ambiguity. Also adds validation for the folder and that there is no vm yet.
Fixes #
```release-note
none
```
> vSphere: Use absolute path when trying to find vms

- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/all_e2e_test.go
In the past, CoreOS was not supported by the machine-controller for Kubevirt cloud provider due to some Kubevirt limitation. Since the release of Kubevirt 0.15 it supports CoreOS and Ignition.
Fixes #422
```release-note
None
```
> Add coreos support to kubevirt

- docs/kubevirt.md
Documenting the image name which should be used for deploying machines that run CoreOS.  
```release-note
None
```
> Documenting the coreos image which is used in Kubevirt cloud provider 

- .prow.yaml
- examples/aws-machinedeployment.yaml
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/aws/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
This indicates whether the encryption state of an EBS volume is changed while being restored from a backing snapshot. 
Fixes #
```release-note
None
```
> Add support for EBS volume encryption

- pkg/userdata/centos/provider.go
- pkg/userdata/coreos/provider.go
- pkg/userdata/helper/kubelet.go
- pkg/userdata/helper/kubelet_test.go
- pkg/userdata/helper/testdata/kublet_systemd_unit_taints-set.golden
- pkg/userdata/sles/provider.go
- pkg/userdata/ubuntu/provider.go
Signed-off-by: Olaf Klischat <o.klischat@syseleven.de>
If the machine spec of a machine being created contains taints, this adds a corresponding `--register-with-taints` option to the machine's kubelet invocation, which means the taints will be set on the node resource from the start. Without this patch, the taints would only be added asynchronously during the first reconcile loop after the node has come up. At that point pods that don't tolerate the taints may already have been scheduled, and they won't be removed again (unless the taint's effect is NoExecute), leading to a permanently misscheduled pod. This can be easily reproduced with DaemonSet pods.
```release-note
kubelet sets intial machine taints via …
```
> kubelet sets intial machine taints via --register-with-taints

- hack/run-machine-controller.sh
Adds an optional env variable to override kubeconfig location in the run script
```release-note
NONE
```
> Add machine controller kubeconfig env variable

- Makefile
- cmd/userdata/rhel/main.go
- examples/kubevirt-machinedeployment.yaml
- examples/vsphere-machinedeployment.yaml
- hack/ci-e2e-test.sh
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/providerconfig/types/types.go
- pkg/userdata/manager/manager.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/provider_test.go
- pkg/userdata/rhel/rhel.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Adding the support for RHEL os in the machine controller.
Fixes kubermatic/kubermatic#4965
```release-note
NONE
```
> Support RedHat Enterprise Linux os in the machine controller

- pkg/userdata/sles/provider.go
- pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/sles/testdata/multiple-dns-servers.yaml
- pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
- pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/sles/testdata/openstack.yaml
- pkg/userdata/sles/testdata/version-1.10.10.yaml
- pkg/userdata/sles/testdata/version-1.11.3.yaml
- pkg/userdata/sles/testdata/version-1.12.1.yaml
- pkg/userdata/sles/testdata/version-1.9.10.yaml
- pkg/userdata/sles/testdata/vsphere-mirrors.yaml
- pkg/userdata/sles/testdata/vsphere-proxy.yaml
- pkg/userdata/sles/testdata/vsphere.yaml
Adding the `kubelet.conf` to the `sles` userdata provider.  
Fixes #
```release-note
None
```
> Add kubelet config in suse

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
This PR updates the userdata template for RHEL to remove a redundant global package update, that can be accomplished by specifying [OSConfig.DistUpgradeOnBoot](https://github.com/kubermatic/machine-controller/blob/master/pkg/userdata/rhel/provider.go#L117) in the MachineDeployment.
Fixes #
```release-note
NONE
```
> Remove yum update command on rhel userdata

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
Using `systemd` as  a cgroup driver for both kubelet and docker instead of cgroupfs.  
Fixes #
```release-note
None
```
> Using systemd instead of cgroupfs in rhel

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/types/types.go
- pkg/cloudprovider/rhsm/subscription_manager.go
- pkg/cloudprovider/rhsm/subscription_manager_test.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
At the moment all the machines which are created by the machine controller in the cloud provider that supports rhel create redhat subscriptions. However, when those machines are deleted the subscriptions are not deleted automatically. This PR adds the functionality to delete those subscriptions(optionally) whenever those machines are deleted.
Fixes #
At the moment this functionality is only supported in the Kubevirt and Vsphere cloud providers since they are the only cloud providers that supports rhel for the time being. However, rhel will be integrated with all cloud providers in the next steps.
```release-note
None
```
> add redhat subscription manager

- test/e2e/provisioning/all_e2e_test.go
We shouldn't run rhel on all available cloud providers e2e tests and run it on one cloud provider is enough. 
```release-note
None
```
> exclude rhel from all cloud providers e2e tests except kubevirt

- examples/alibaba-machinedeployment.yaml
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/alibaba/types/types.go
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/ubuntu/testdata/openstack.yaml
- pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
- pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
- pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
- pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
- pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
- pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
- pkg/userdata/ubuntu/testdata/vsphere.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-alibaba.yaml
The UI team has started to integrate alibaba cloud provider in the ui. The CentOS image name was not correct and the disk type and size was hard coded in the provider code. This PR fix these issues.
Please make sure that the testing job for alibaba cloud is passing before merging.
```release-note
None
```
> Add disk type and size to alicloud

- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/aws/types/types.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Adding rhel as an OS option for AWS cloud provider. 
Fixes #5005
```release-note
None
```
> support rhel in aws cloud provider

- pkg/cloudprovider/provider/openstack/helper.go
Previously no openstack subnet would be defaulted when more than one is available.
Details of this change on openstack default subnet selection:
* pick the first subnet if more than one is available (instead of returning nil)
* error out when no subnet is available (after subnet api request)
* continue to skip subnet api request when network has exactly one subnet already
```release-note
NONE
```
> Improve openstack default subnet selection

- pkg/cloudprovider/provider/aws/provider.go
The error message when searching for the AMI-ID fails did not indicate this problem.
```release-note
NONE
```
> AWS: improve AMI-ID error message

- test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
We have often openstack e2e test failures due to quota issues.
Fixes #
```release-note
NONE
```
> Use smaller VM flavor in e2e tests to avoid hitting CPU quota

- .prow.yaml
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
- pkg/cloudprovider/rhsm/subscription_manager.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Adding support for Red Hat Enterprise Linux in Azure cloud provider.
Fixes kubermatic/kubermatic#5004
`pull-machine-controller-e2e-azure` should pass. 
```release-note
None
```
> Add rhel support in azure cloud provider

- .github/PULL_REQUEST_TEMPLATE.md
The old template made the release-note block look like the review notes.
```release-note
NONE
```
> Fix Github PR template formatting

- test/e2e/provisioning/all_e2e_test.go
Disable running rhel e2e tests for azure. 
```release-note
None
```
> disable running rhel os in azure cloud provider

- Makefile
- go.mod
- go.sum
* -mod=readonly will cause build to fail in case when there is need to
make modifications in go.mod (e.g. on CI)
* -trimpath will drop build prefixes from resulted debug metadata
* microscopic cleanup go.mod
Fixes #
```release-note
NONE
```
> Better go build flags

- .prow.yaml
- Dockerfile
- Makefile
When I updated the Makefile in PR #680 I replaced `machine-controller` rule with a pattern rule that differently from the previous one just builds the `machine-controller` and not the userdata binaries, but I forgot to update the `docker-image` rule accordingly, thus the images generated when the PR was merged do not include the userdata binaries
This PR does following things:
- Fixes the issue described above.
- Split the generation and the upload of the docker image in two different rules in the Makefile `docker-image` and `docker-image-publish`
- Builds the binary included in the docker image with a multistage build
- Adds the `-mod=readonly` flag to the build to avoid modifying the committed `go.mod` and `go.sum`.
**Which issue(s) this PR …
> Fix docker-image rule in Makefile

- Makefile
Concurrent PRs having almost the same GOFLAG settings caused duplication
Fixes #
```release-note
NONE
```
> Remove duplicated GOFLAGS from Makefile

- .prow.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/gce/types/cloudconfig.go
- pkg/cloudprovider/provider/gce/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-gce.yaml
Adding support for RHEL in gcp cloud provider.
Fixes kubermatic/kubermatic#5007
```release-note
None
```
> add rhel support to the gcp cloud provider

- pkg/cloudprovider/provider/aws/provider.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
- test/e2e/provisioning/helper.go
To manage red hat linux subscriptions in the customer cloud portal. This functionality was not available in aws due to the lack of support for rhel-8.x GA images. 
Fixes kubermatic/kubermatic#5001
```release-note
None
```
> Enable subscription manager for aws

- cmd/machine-controller/main.go
- pkg/controller/nodecsrapprover/doc.go
- pkg/controller/nodecsrapprover/node_csr_approver.go
- pkg/controller/nodecsrapprover/node_csr_approver_test.go
This PR implements the NodeCSRApprover controller, which automatically approves the node **serving** certificates.
In #667, we have enabled the [Kubelet TLS bootstrapping](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping), so Kubelet serving and client certificates are requested using CertificateSigningRequests (CSRs). The client certificates are approved automatically by `kube-controller-manager`, however, serving certificates are not. The Kubernetes documentation advises that certificates should be approved manually or using a custom controller.
```release-note
Implement the NodeCSRApprover controller for automatically approving node serving certificates
```
/assign @irozzo-1A …
> Implement the NodeCSRApprover controller

- pkg/cloudprovider/rhsm/subscription_manager.go
- pkg/cloudprovider/rhsm/subscription_manager_test.go
This PR uses the oauth2 client from go subrepository in order to avoid implementing the logic for obtaining and refreshing the tokens when talking to RHSM API
Fixes #
```release-note
NONE
```
> Use OAuth2 client instead of implementing access token retrieval and refresh

- examples/machine-controller.yaml
- hack/ci-e2e-test.sh
- pkg/cloudprovider/provider/azure/get_client.go
- pkg/cloudprovider/provider/azure/provider.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-azure.yaml
The `status.addresses` in the machine object was lacking the list of the ip addresses for the instances that are created in Azure cloud provider. The reason for that was sending wrong parameters to the azure api.
Fixes kubermatic/kubermatic#5137
Make sure that the `pull-machine-controller-e2e-azure` job is green :) 
```release-note
None
```
> Fix the ip address updating in the cluster status

- test/e2e/provisioning/all_e2e_test.go
RedHat Enterprise Linux e2e tests should be running on one cloud provider only. Thus, this PR deactivate all RHEL e2e tests on any other cloud providers but Kubevirt.
```release-note
None
```
> disable rhel e2e tests except for kubevirt

- docs/operating-system.md
The goal of this PR is to document the OS that machine controller currently supports 
Fixes #
```release-note
NONE
```
> OS support documentation

- docs/kubevirt.md
- docs/rhel-custom-image.md
- examples/alibaba-machinedeployment.yaml
- examples/aws-machinedeployment.yaml
- examples/azure-machinedeployment.yaml
- examples/gce-machinedeployment.yaml
- examples/openstack-machinedeployment.yaml
- examples/vsphere-datastore-cluster-machinedeployment.yaml
- examples/vsphere-machinedeployment.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
Updating the example folder
```release-note
None
```
> Update the examples folder

- docs/cloud-provider.md
Update cloud provider spec documentation
Fixes #
```release-note
NONE
```
> Update cloud provider spec documentation

- docs/cloud-provider.md
- docs/operating-system.md
- docs/rhel-custom-image.md
- docs/vsphere.md
Fixes #
Check that links are not broken and how it's rendered [here](https://github.com/irozzo-1A/machine-controller/blob/improve-vsphere-doc/docs/vsphere.md)
```release-note
NONE
```
> Improve vsphere doc

- examples/azure-machinedeployment.yaml
- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
- test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Adding multiple availability zones support in the machine controller for azure cloud provider.
Fixes #
```release-note
None
```
> adding azure az support

- docs/vsphere.md
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/provider_test.go
- pkg/cloudprovider/provider/vsphere/types/types.go
Adds support for resource pools and coincidently adds [support for VM templates](#670 ) . 
Fixes #596
Introduces resourcePool as required field for the machinedeployments
```release-note
Add vSphere ResourcePool support
```
> Add vSphere ResourcePool support

- pkg/cloudprovider/instance/instance.go
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/gce/instance.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/packet/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
Attaching the Node Address Type to the created machines, and cleanup rhel subscription based on the private dns for aws cloud provider. 
Fixes kubermatic/kubermatic#5307
```release-note
None
```
> Use addresses instead of node ref for rhel aws instances

- Makefile
- cmd/userdata/flatcar/main.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/providerconfig/types/types.go
- pkg/userdata/flatcar/flatcar.go
- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/provider_test.go
- pkg/userdata/flatcar/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
- pkg/userdata/flatcar/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
- pkg/userdata/flatcar/testdata/v1.11.2-vsphere-static-ipconfig.yaml
- pkg/userdata/flatcar/testdata/v1.12.0-vsphere-mirrors.yaml
- pkg/userdata/flatcar/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
- pkg/userdata/flatcar/testdata/v1.12.0-vsphere-proxy.yaml
- pkg/userdata/flatcar/testdata/v1.15.0-vsphere.yaml
- pkg/userdata/flatcar/testdata/v1.17.0.yaml
- pkg/userdata/flatcar/testdata/v1.9.2-disable-auto-update-aws-external.yaml
- pkg/userdata/flatcar/testdata/v1.9.2-disable-auto-update-aws.yaml
- pkg/userdata/flatcar/testdata/v1.9.2-disable-locksmith-aws.yaml
- pkg/userdata/flatcar/testdata/v1.9.2-disable-update-engine-aws.yaml
- pkg/userdata/manager/manager.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
Adding support for flatcar os for aws cloud provider.
Fixes kubermatic/machine-controller#716
```release-note
None
```
> Support flatcar in aws

- .prow.yaml
- go.mod
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
- pkg/providerconfig/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
Support `DNSConfig` propagation from the `MachineDeployment` to the Kubevirt `VM`.
Fixes #
```release-note
None
```
> Adding kubevirt dnsconfig

- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
Adding flatcar integration tests for Openstack
Fixes kubermatic/machine-controller#719
```release-note
None
```
> adding openstack test

- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- test/e2e/provisioning/all_e2e_test.go
Support flatcar in vSphere cloud provider
Fixes kubermatic/machine-controller#718
```release-note
NONE
```
> Support flatcar in vsphere

- pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
Introduce the datastore cluster to the global opts  
```release-note
None
```
> add datastore-cluster to GlobalOpts

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
Fixed too wide permissions of the /opt/bin/setup
```release-note
NONE
```
> Fix setup script permissions

- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/ubuntu/testdata/openstack.yaml
- pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
- pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
- pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
- pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
- pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
- pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
- pkg/userdata/ubuntu/testdata/vsphere.yaml
https://github.com/kubermatic/machine-controller/pull/759
Bind `docker-ce-cli` to the same version as `docker-ce`.
CentOS is not affected in 1.10 release because we are using the [Docker v1.13 package](https://github.com/kubermatic/machine-controller/blob/2b8a521f63efb757c091c9355597acccd5a13bdf/pkg/userdata/centos/provider.go#L187).
```release-note
release/v1.8: Bind docker-ce-cli to the same version as docker-ce
```
/assign @kron4eg
> [release/v1.8] Bind docker-ce-cli to the same version as docker-ce

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/ubuntu/testdata/openstack.yaml
- pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
- pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
- pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
- pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
- pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
- pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
- pkg/userdata/ubuntu/testdata/vsphere.yaml
https://github.com/kubermatic/machine-controller/pull/759
Bind `docker-ce-cli` to the same version as `docker-ce`.
CentOS is not affected in 1.10 release because we are using the [Docker v1.13 package](https://github.com/kubermatic/machine-controller/blob/04c3f2ab0fe688858b8ac124ce17cf686cd6d9c7/pkg/userdata/centos/provider.go#L187).
```release-note
release/v1.10: Bind docker-ce-cli to the same version as docker-ce
```
/assign @kron4eg
> [release/v1.10] Bind docker-ce-cli to the same version as docker-ce

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
- test/e2e/provisioning/all_e2e_test.go
This PR removes the registration of the machine from the setup script (run by a systemd unit) and attempts to use `rh_subscription` cloud-init module as a replacement.
The advantage of doing this is that the module attempts the registration only if the system is not already registered.
Fixes #777
```release-note
None
```
> Use cloud-init rh_subscription module to register and auto-attach subscriptions

- test/e2e/provisioning/all_e2e_test.go
Our RHEL 8.x subscription has ran out of support and expired. Once we renew it we enable those tests again. For GA images(e.g: aws, azure) the tests are still enabled.
```release-note
None
```
> Disable rhel tests untill subscriptions are renewed

- pkg/cloudprovider/provider/gce/instance.go
Assign external IP and DNS name for GCP machines.
Fixes #781
```release-note
Add external IPs and DNS name to .status.Addresses for the GCP machines. This fixes the issue with NodeCSRApprover controller refusing to approve CSRs for GCP worker nodes.
```
> Assign external IP and DNS name for GCP machines

- test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
After the creation of the new Kubevirt cluster, the images registry address has been changed. This PR adds the new images server address to the tests templates for Kubevirt cloud provider. 
```release-note
None
```
> adjust the source url for the registry server

- .prow.yaml
- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
- test/e2e/provisioning/all_e2e_test.go
This PR unblocks the ability to user CentOS8 / RHEL7.
* now it's possible to upgrade docker version
* CentOS8 / RHEL7 can be provisioned
While by default without externally provided image machine-controller will search for CentOS7 images (fixing this is out of scope of this PR), it's now possible to provide CentOS8 (or RHEL7) image in MachineDeployment.
```release-note
support CentOS7/CentOS8/RHEL7/RHEL8
```
> Make it work for CentOS7/CentOS8/RHEL7/RHEL8

- examples/machine-controller.yaml
This PR adds the RBAC rules needed for the NodeCSRApprover controller to work properly.
```release-note
NONE
```
> Add CSR RBAC to the example manifest

- test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
Lastly we hit some quota issues in the openstack tenant we use for our e2e tests. In order to reduce disk consumption this PR is:
* Moving the `rootDiskSizeGB` to the openstack upgrade test that is run with ubuntu OS only
* Reducing `rootDIskSizeGB` to 10G that should be enough
Fixes #
```release-note
NONE
```
> Reduce disk storage consumption in Openstack e2e tests

- pkg/cloudprovider/provider/gce/instance.go
- pkg/cloudprovider/provider/gce/provider.go
Currently, the NodeCSRApprover controller is refusing to approve the kubelet serving CSRs because of the hostname mismatch:
```
E0721 15:50:11.376789   57460 node_csr_approver.go:78] Reconciliation of request /csr-bvrws failed: error validating the x509 certificate request: dns name '<instance-name>.c.<project-name>.internal' cannot be associated with node '<node-name>'
```
We have attempted to fix this issue in #782, however, it turned out that the Hostname field of the instance resource is empty if a hostname is not specified when creating the instance (i.e. the default hostname is being used).
There are two ways to determine the hostname if the default hostname is being used (which is our case):
* By using the metadata API. This is not suitable …
> Add proper hostnames to the GCP Machine objects

- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
This PR attempts to fix the bug which occurs when a Machine is rolled-out and the new Machine has the same IP addresses as the old one. It could happen that the machine-controller sets the NodeOwner label on the old Node object to the UID of the new Machine. That can break the logic for removing the old Node object, as it depends on the NodeOwner label having the UID of the Machine that's being deleted.
There are two fixes:
* The getNode function which is used when adding the NodeRef now confirms that the instance and node names match for **Hetzner Machines/instances**. Previously, we only checked IP addresses, so if we a new Machine has the same addresses as the old one, it can adopt a node that's to-be-deleted
* This assumes the name of the Node …
> Delete Nodes by NodeRef and compare node and machine names when getting a Hetzner node

- test/e2e/provisioning/testdata/machinedeployment-packet.yaml
We've used t1.small.x86 instances for running E2E tests because we
don't need large instances. The t1.small.x86 instance type is first
generation, and as the first generation is deprecated, it's not
available anymore. The c1.small.x86 instances are bit more expensive,
but it's the smallest instance type currently available. Besides that,
we now run Packet E2E tests in the Amsterdam region.
```release-note
NONE
```
> Use c1.small.x86 instance type on Packet

- pkg/cloudprovider/provider/packet/provider.go
- test/e2e/provisioning/all_e2e_test.go
To allow Flatcar to be used as one of the operating systems, we need to update `getNameForOS()` so it also accepts the input value `flatcar` in `operatingSystem` of the provider config.
```release-note
support Flatcar in Packet cloud provider
```
> Support Flatcar in Packet cloud provider

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
- pkg/userdata/helper/helper.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
- pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
- pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
- pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
- pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
- pkg/userdata/ubuntu/testdata/openstack.yaml
- pkg/userdata/ubuntu/testdata/version-1.17.3.yaml
- pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
- pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
- pkg/userdata/ubuntu/testdata/vsphere.yaml
This PR updates Docker to 19.03.12 for Ubuntu, CentOS, and RHEL clusters running Kubernetes 1.17 and newer. The clusters running Kubernetes 1.16 and older are using Docker 18.06, as before this change.
The reason for updating Docker is that there is an issue with collecting metrics on 1.19 clusters using Docker 18.06. More details can be found in the following Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/94281
* I've decided to go with 19.03.12 as we already use it in KubeOne.
* Flatcar is still using Docker 18.06, as there is no stable release that includes Docker 19.03. There is a beta release that comes with Docker 19.03.11. If users want to use Flatcar with Kubernetes 1.19, and utilize …
> Update Docker to 19.03.12 for Ubuntu, CentOS, RHEL

- pkg/controller/machine/machine.go
- pkg/controller/machine/machine_test.go
There's a regression introduced in #813, which prevents the Machine object from being deleted if the Node referred by NodeRef is deleted.
```release-note
Ignore Node when deleting by NodeRef if it doesn't exist anymore
```
> Ignore Node when deleting by NodeRef if it doesn't exist anymore

- test/e2e/provisioning/all_e2e_test.go
It appears that GCE and DigitalOcean have removed the CoreOS images, causing our E2E tests to fail.
The GCE Machine object is showing the following error:
```
An error of type = InvalidConfiguration, with message = Failed to insert instance: googleapi: Error 404: The resource 'projects/coreos-cloud/global/images/family/coreos-stable' was not found, notFound occurred
```
The DigitalOcean Machine object is showing the following error:
```
failed to create machine at cloudprovider, due to POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.
```
```release-note
NONE
```
> Disable CoreOS E2E tests on GCE and DigitalOcean

- cmd/machine-controller/main.go
- pkg/apis/plugin/plugin.go
- pkg/controller/machine/machine.go
- pkg/userdata/centos/provider.go
- pkg/userdata/centos/provider_test.go
- pkg/userdata/coreos/provider.go
- pkg/userdata/coreos/provider_test.go
- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/provider_test.go
- pkg/userdata/helper/kubelet.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/provider_test.go
- pkg/userdata/sles/provider.go
- pkg/userdata/sles/provider_test.go
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/provider_test.go
This PR adds support for setting (enabling and disabling) arbitrary feature gates on the Kubelet. This is useful in scenarios when an user needs to enable some cluster features that are disabled by default and/or provider-specific, such as CSI Migration.
The feature gates are enabled by setting the `--node-kubelet-feature-gates` flag on machine-controller. The feature gates are provided in the same format as to other Kubernetes components, i.e. key/value pair where the key is the feature gate name and the value is `true` or `false`. Currently, the feature gates are set on **all** machines/nodes, i.e. it's not possible to do it for a subset of machines.
Example usage: `./machine-controller --node-kubelet-feature-gates=CSIMigration=true,CSIMigrationAWS …
> Add support for setting arbitrary feature gates on the kubelet

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
- test/e2e/provisioning/all_e2e_test.go
Recently docker introduced `docker-ce` repository for CentOS 8 it only contains docker version `19.03.13-3`. This caused a regression when using RHEL/CentOS 8, because previously we were using CentOS 7 repo indistinctly for CentOS/RHEL 7/8 but now the docker versions we were installing are no longer available in CentOS 8 repo.
As we do not have OS versioning yet the quick and dirty solution is to always use CentOS 7 repo for the docker versions that are not available on both repos.
https://download.docker.com/linux/centos/8/x86_64/stable/Packages/
https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
Fixes # …
> Fix releasever to 7 for RHEL and CentOS in yum docker repository

- pkg/userdata/flatcar/provider.go
This PR adds the polkit permission required for the user to reboot the machine. The user runs [flatcar-update-operator ](https://github.com/kinvolk/flatcar-linux-update-operator)and needs permissions to reboot the machine when flatcar-update-controller receives a signal for the OS to update.
The polkit rule is based on this issue on flatcar-update-operator https://github.com/kinvolk/flatcar-linux-update-operator/issues/18. There was no need to add the second rule for dbus since only the core user must be allowed to reboot the machine.
Login with the user `core` in a flatcar machine and try to send the message that the update operator and send a dbus message to reboot the machine:
```
dbus-send --system …
```
> Fix hanging reboot on auto update.

- pkg/userdata/flatcar/provider.go
This bug was introduced in https://github.com/kubermatic/machine-controller/pull/824.
The name of the file to be created must be suffixed with `.rules` instead of `.rule`
```release-note
Fix polkit rule filename to allow `core` user to rebbot machine for auto updates.
```
> Fix polkit rules filename for flatcar reboot.

- pkg/controller/machine/machine.go
After creating a new provider instance we always want to have the
machine-delete-finalizer. Possible provider specific finalizers can't be
deleted without it.
We have noted this especially for azure clusters, where the machine-controller doesn't try to run deleteCloudProvider instance because the finalizer `machine-delete-finalizer` is missing.
Fixes #
```release-note
NONE
```
> Always ensure to have machine-delete-finalizer

- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/provider_test.go
- pkg/userdata/flatcar/testdata/v1.18.0.yaml
- pkg/userdata/flatcar/testdata/v1.19.0.yaml
We already use Hyperkube Kubelet for clusters running Kubernetes
1.17 and older. This PR extends this to 1.18, as there are no
Poseidon Kubelet images for the latest 1.18 releases any longer.
```release-note
Use Hyperkube Kubelet for 1.18 clusters
```
/assign @kron4eg
> Use Hyperkube Kubelet for 1.18 clusters

- examples/anexia-machinedeployment.yaml
- pkg/cloudprovider/provider/anexia/types/types.go
- pkg/providerconfig/types/types.go
**What this PR does / why we need it**: 
This PR adds the cloud provider spec and configs to the machine controller. Next step will be to the full implementation of the provider api in addition to the e2e tests.
Fixes #
```release-note
NONE
```
> Add Anexia Cloud Provider Spec to Machine-Controller 

- examples/openstack-machinedeployment.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/machinesv1alpha1machine/openstack.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/openstack.yaml
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/cloudprovider/provider/openstack/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
Make instanceReadyCheckTimeout for OpenStack Provider configurable
#819 
This haven't been tested properly yet.
It is still work in progress.
```release-note
[action required] instanceReadyCheckTimeout `instanceReadyCheckPeriod` and `instanceReadyCheckTimeout` are now configurable to allow alternative Timeouts and Re-Tries. 120s is the default 
```
> Implement a configurable timeout for OpenStack

- test/tools/integration/Makefile
- test/tools/integration/versions.tf
E2E tests are broken due to some conflicts in api versions which terraform is using.
```release-note
None
```
> upgrade terraform to 0.13.5

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
Refactor Kubevirt DNSConfig type from being a raw string to PodDNSConfig. This config is part of kubermatic datacenter configs.
Follow up PR to this issue https://github.com/kubermatic/kubermatic/issues/6121
```release-note
Support Kubevirt DNSConfig in Kubermatic 
```
> Refactor the KubeVirt dns settings

- pkg/cloudprovider/provider/openstack/provider.go
- test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
- test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
Fix the defaulting logic for Openstack instanceReadyPeriod/Timeout. 
```release-note
None 
```
> fix openstack instanceReadyPeriod/Timeout

- .prow.yaml
- Dockerfile
- Makefile
This updates to Go 1.15.1. I chose this version because this is what we have ready-made Docker images for.
Fixes #829
```release-note
Machine-Controller is built using Go 1.15.
```
> Update to Go 1.15.1

- test/tools/integration/hetzner.tf
- test/tools/integration/output.tf
- test/tools/integration/versions.tf
Terraform complains about a deprecation:
> Warning: Interpolation-only expressions are deprecated
>
>  on hetzner.tf line 2, in provider "hcloud":
>   2:   token = "${var.hcloud_token}"
Since Terraform 0.14, the `fmt` command takes care of fixing that automatically. This is what this PR does.
```release-note
NONE
```
> terraform fmt

- pkg/cloudprovider/provider/anexia/provider.go
I was asked to remove this flag since internal changes in Anexia now make this flag counter productive.
None
None
```release-note
NONE
```
> Remove cloud-init flag from the Anexia provider

- .prow.yaml
- Makefile
- hack/ci-download-gocache.sh
- hack/ci-e2e-test.sh
- hack/ci-upload-gocache.sh
This saves bandwidth and CPU cycles for all of our tests.
```release-note
NONE
```
> Add gocache and goproxy to CI jobs

- docs/cloud-provider.md
- examples/azure-machinedeployment.yaml
- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/cloudconfig.go
- pkg/cloudprovider/provider/azure/types/types.go
- test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
- test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Support specifying a different resource groups for vnets in Azure.
Fixes #836
```release-note
Vnet Resource group support
```
> Specify resource group field for azure vnet

- pkg/cloudprovider/provider/openstack/types/cloudconfig.go
- pkg/cloudprovider/provider/openstack/types/cloudconfig_test.go
- pkg/cloudprovider/provider/openstack/types/testdata/use-octavia-explicitly-disabled.golden
- pkg/cloudprovider/provider/openstack/types/testdata/use-octavia-explicitly-enabled.golden
This PR adds the `use-octavia` flag to the OpenStack cloud config, this is a pre-requisite for:https://github.com/kubermatic/kubermatic/issues/6309
Fixes #
```release-note
NONE
```
> Add optional use-octavia flag to OpenStack cloud config

- cmd/machine-controller/main.go
In my last update I accidentally removed this call for the machine collector.
```release-note
Fix missing machine_controller_machines metric
```
> fix missing machine metrics

- pkg/cloudprovider/provider/aws/provider.go
Signed-off-by: Marko Mudrinić <mudrinic.mare@gmail.com>
Some AWS regions are slower to create the instance (e.g. us-east-1), so it might happen that machine-controller checks is the instance created before it's created in AWS. That causes instance to get created two times. Therefore, if we get no instance, we retry several times to get it.
Fixes #792
```release-note
Fix the bug causing the machine-controller to create two instances for one Machine in some AWS regions
```
/assign @kron4eg @moadqassem
> Retry getting AWS instance

- cmd/machine-controller/main.go
- docs/network-restrictions.md
This replaces the default kubelet Docker image with kubermatic/kubelet. We use this repo now because it provides updates for older Kubernetes releases. This is part of https://github.com/kubermatic/kubermatic/issues/6441
```release-note
Switch default kubelet Docker image to quay.io/kubermatic/kubelet
```
> use quay.io/kubermatic/kubelet

- cmd/machine-controller/main.go
- docs/network-restrictions.md
Cherry-pick of #885.
```release-note
Switch default kubelet Docker image to quay.io/kubermatic/kubelet
```
/assign @kron4eg
> [release/v1.24] use quay.io/kubermatic/kubelet

- .prow.yaml
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-azure-custom-image-reference.yaml
Support azure custom image reference. This is needed in order to create worker nodes that run ubuntu 20.04 e.g and to support other os versions. The current `image_id` field doesn't work with public images and it only works with custom images.
Fixes #
```release-note
Image Reference Support in Azure
```
> Support image reference in azure

- pkg/userdata/scripts/health-monitor.sh
text by @phiphi282 
Sometimes the kubelet suddenly starts to hang and the kubelet needs to be restarted, or even the node if there is no ssh access.
This pr adds a script to cloud init to check the kubelet logs periodically and restarts the kubelet if needed.
This is because of this bug in kubernetes: kubernetes/kubernetes#87615
That will probably be fixed with the first kubernetes version that will use golang 1.16 (probably earliest version will be 1.21).
Replaces #844
```release-note
Create workaround for kubelet stopped posting node status bug
```
> Create workaround for kubelet stopped posting node status bug

- examples/openstack-machinedeployment.yaml
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/cloudprovider/provider/openstack/types/cloudconfig.go
- pkg/cloudprovider/provider/openstack/types/cloudconfig_test.go
- pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials-ignore-userpass.golden
- pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials.golden
- pkg/cloudprovider/provider/openstack/types/types.go
Signed-off-by: Happy2C0de <46957159+Happy2C0de@users.noreply.github.com>
Add support for openstack application credentials
Fixes #899
Addition of `getConfigAuth` function in provider.go limits the cyclomatic complexity that was reached with a direct integration into `getConfig` function. From my point of view, excluding the retrieval of authentication information makes sense.
Please to proper e2e tests.
```release-note
Add application credentials support to the Openstack provider
```
> Add application credentials to openstack provider

- pkg/cloudprovider/provider/hetzner/provider.go
- test/e2e/provisioning/testdata/machinedeployment-hetzner.yaml
Fun fact: all these HCloud-Go API methods document
> If the ... does not exist, nil is returned.
As piping nil values through to hcloud-go will cause panics, this PR improves the error handling. Nonexisting resources are not treated as terminal errors, as their status can change at any time (e.g. if the user notices and creates the missing network).
```release-note
Improve Hetzner error handling
```
> handle misconfigured hetzner machines better

- .prow.yaml
:tada:
```release-note
Update to Go 1.16.1
```
> Update to Go 1.16.1

- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/packet/provider.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
Signed-off-by: Moath Qasim <moad.qassem@gmail.com>
When machine deployments are created manually(without using the api) and the OperatingSystemSpec is left empty, KKP api will fail to decode the MachineDeployment spec. This PR returns an empty OperatingSystemSpec in case of dropping that field in the manually created MD.
Fixes kubermatic/kubermatic#6637
```release-note
Validating OperatingSystemSpec in MachineDeployment
```
> validate operatingSystemSpec is not empty

- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/baremetal/plugins/driver.go
- pkg/cloudprovider/provider/baremetal/provider.go
- pkg/cloudprovider/provider/baremetal/types/types.go
- pkg/providerconfig/types/types.go
- test/e2e/provisioning/testdata/machinedeployment-baremetal.yaml
This PR introduces a new structure to provision machines(worker nodes) on a baremetal environments(onPrem). It represents the scheme of how baremetal providers/provisioners are added and used  by the machine controller.
This is only a draft/initial-structure for the baremetal providers. At the moment there is no real implementation/logic has been added, however the upcoming PRs would address the implementation of a potential provisioner/driver. 
```release-note
Baremetal Clusters Provisioning 
```
> Adding initial baremetal provider structure

- pkg/cloudprovider/provider/openstack/helper.go
This is a tentative fix for #803. I have still doubts about the possible side-effects. It could possibly result in available FIPs not been considered eligible.
See https://github.com/kubermatic/machine-controller/pull/28#discussion_r163773619 for more details.
Fixes #803 
```release-note
NONE
```
> Fix free floating IP detection logic for OTC

- pkg/nautobot/client.go
- pkg/nautobot/common.go
- pkg/nautobot/device.go
- pkg/nautobot/interface.go
- pkg/nautobot/ip.go
- pkg/nautobot/prefix.go
- pkg/nautobot/util.go
Support Nautobot minimal client which will be used to provision baremetal clusters
Fixes #
The client is not being used in the baremetal provider. will be added once tested in a separate commit 
```release-note
Nautobot client support
```
> Support Nautobot client in machine controller

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere.yaml
The deregistration of a RHEL subscription failed if the machines FQDN
did not match its node name. This happened for instance on OpenStack
clusters that add the .novalocal domain suffix.
This change sets the fqdn field in the cloud-init userdata to the hostname to
ensure that the machine name matches the registered name in the
RHSM or Satellite server.
Fixes #
```release-note
Fix RHEL subscription deregistration on OpenStack
```
> Fix RHEL subscription deregistration on OpenStack

- pkg/cloudprovider/provider/aws/provider.go
This PR fixes an hardcoding in the AWS provider when using flatcar.
The flatcar version has been replaced by a wildcard to fetch the
latest os version.
Fixes #
```release-note
Flatcar version in AWS fix
```
> Flatcar version in AWS fix

- .prow.yaml
- test/e2e/provisioning/all_e2e_test.go
Since #958 introduced the containerd support to flatcar, this PR adds an E2E test using flatcar with containerd in AWS.  
Fixes #
**Special notes for your reviewer*
```release-note
NONE
```
> E2E test for flatcar with containerd in AWS

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver_test.go
- pkg/cloudprovider/provider/baremetal/provider.go
Adding unit tests for tinkerbell provider and clean up some left out resources on machine deletion.
Fixes #934
Please do not review until this PR is merged(https://github.com/kubermatic/machine-controller/pull/956)
```release-note
None
```
> Add unit tests for tinkerbell

- pkg/cloudprovider/provider/vsphere/client.go
Fix the vSphere client issue where it doesnt use the provided custom CA bundle. Based on vmware/govmomi#1200.
Fixes #966 
```release-note
Fixed vSphere client not using the provided custom CA bundle
```
> fix vSphere client not using the provided custom CA bundle

- pkg/cloudprovider/provider/vsphere/client.go
Backport of original #969 
```release-note
Fixed vSphere client not using the provided custom CA bundle (#969)
```
> [release/v1.27] fix vSphere client not using the provided custom CA bundle (#969)

- .prow.yaml
- pkg/cloudprovider/provider/azure/provider.go
- pkg/userdata/rhel/provider.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-azure-custom-image-reference.yaml
- test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
- test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Using RHEL GA images instead of custom images. 
Fixes #974
```release-note
None
```
> use the rhel ga instead of custom image on azure

- pkg/cloudprovider/provider/aws/provider.go
Label machines and nodes with aws-node-termination-handler for aws spot instances draining.
Fixes kubermatic/kubermatic#6723
Please have a look on this PR as well:
https://github.com/kubermatic/kubermatic/compare/master...moadqassem:supports-aws-node-termination-handler?expand=1
```release-note
AWS Spot instances support
```
> add aws-node-termination-handler label for node selector

- pkg/controller/machine/machine_controller.go
- pkg/rhsm/satellite_subscription_manager.go
- pkg/rhsm/util.go
When the satellite subscription has been deleted manually or wasn't registered correctly in the first place due to some custom setup, the deletion of the subscription should be avoid otherwise the machine will be stuck in deletion phase
Fixes #980 
```release-note
None
```
> Skip satellite subscription deletion when the subscription is not found

- pkg/cloudprovider/provider/openstack/provider.go
Fix for openstack custom ca bundle handling. Client was trying to authenticate before setting the custom CA bundle which was causing errors.
Fixes #994 
```release-note
Fixed using a custom CA Bundle for Openstack by authenticating after setting the custom CA bundle
```
> Fixed openstack client ca bundle handling

- pkg/controller/nodecsrapprover/node_csr_approver.go
After upgrading certificates API to v1, .status field became required.
```
E0614 12:50:17.169084       1 node_csr_approver.go:77] Reconciliation of request /csr-dfnrk failed: failed to approve CSR "csr-dfnrk": CertificateSigningRequest.certificates.k8s.io "csr-dfnrk" is invalid: status.conditions[0].status: Required value
```
Fixes #
```release-note
Fix node_csr_approver
```
> Fix node_csr_approver

- docs/cloud-provider.md
- examples/openstack-machinedeployment.yaml
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/cloudprovider/provider/openstack/types/types.go
Signed-off-by: Happy2C0de <46957159+Happy2C0de@users.noreply.github.com>
Adds support to add a volume type to the machine deployments. This goes along with the setting `rootDiskSizeGB` and I added it such that it's only applied if and only if the `rootDiskSizeGB` is specified. I think that makes sense.
Exposes the VolumeType option in the underlying library, see:
https://pkg.go.dev/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume#BlockDevice
Fixes #
```release-note
Add support to specify the root disk volume type in Openstack if …
```
> Add support for volume type openstack

- cmd/machine-controller/main.go
Sometimes it fails with:
```
E0616 15:27:06.818753       1 main.go:304] failed to start kubebuilder manager: no matches for kind "CertificateSigningRequest" in version "certificates.k8s.io/v1"
```
```release-note
Fix: Force certificates/v1 to register
```
> Force certificates/v1 to register

- pkg/cloudprovider/provider/openstack/provider.go
**What this PR does / why we need it**: add application credentials for cloud-config.
Passing only application credentials cause the failure  of openstack-cloud-controller-manager:
```
W0618 07:16:50.834250       1 openstack.go:303] New openstack client created failed with config: You must provide a password to authenticate
F0618 07:16:50.834306       1 controllermanager.go:131] Cloud provider could not be initialized: could not init cloud provider "openstack": You must provide a password to authenticate
```
I assume the application credential are not included in cloud config.
Fixes #
```release-note
NONE
```
> add application credentials for cloud config

- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/cloudconfig.go
- pkg/cloudprovider/provider/azure/types/types.go
Add loadBalancerSku field in the azure cloud config file to have the possibility to change the LB type to Standard.
Fixes #
```release-note
None
```
> add loadBalancerSku to azure cloud

- pkg/cloudprovider/provider/aws/provider.go
This PR adds a `nil` check before trying to extract the SpotInstanceConfig. The machine-controller-webhook panics without this check if `IsSpotInstance` is set to true, but the config is not provided.
```
2021/06/29 17:39:38 http: panic serving 10.244.0.0:32995: runtime error: invalid memory address or nil pointer dereference
goroutine 231 [running]:
net/http.(*conn).serve.func1(0xc0005e1ae0)
net/http/server.go:1801 +0x147
panic(0x2ced6e0, 0x52e3290)
runtime/panic.go:975 +0x3e9
net/http.(*timeoutHandler).ServeHTTP(0xc000771b00, 0x38829c0, 0xc0007fa8c0, 0xc0008f9b00)
net/http/server.go:3277 +0x988
net/http.serverHandler.ServeHTTP(0xc0007fa0e0, 0x38829c0, 0xc0007fa8c0, 0xc0008f9b00)
net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0005e1ae0, …
```
> Add nil check for SpotInstanceConfig

- cmd/machine-controller/main.go
- pkg/controller/nodecsrapprover/node_csr_approver_v1beta1.go
We had to update certificates API, now I'm returning the support for older certificates.k8s.io/v1beta1, but NOW it can be chosen based on API availability.
```release-note
Dynamically choose which certificates.k8s.io version to support
```
> Dynamically choose which certificates.k8s.io version to support

- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
The external CSI controller requires cluster-id to be set to correctly provision volumes in vSphere. This PR aims at solving this issue, adding such field in the vSphere cloud-config API.
Fixes #
```release-note
NONE
```
> Cluster-id addition in vsphere cloud-config api

- pkg/cloudprovider/provider/openstack/provider.go
- pkg/providerconfig/types.go
Make unmarshaling of openstack InstanceReadyCheckPeriod InstanceReadyCheckTimeout more Go-ish.
```release-note
NONE
```
> Refactor unmarshaling openstack InstanceReadyCheckPeriod InstanceReadyCheckTimeout

- pkg/cloudprovider/provider/aws/provider.go
Without resetting the metric, old label values will never get cleaned up, so the number of metrics will just grow without bounds.
Fixes #
```release-note
Fix machine_controller_aws_instances_for_machine metric growing with new machines, but never forgetting old, deleted machines.
```
> prevent AWS metrics from growing over time

- test/e2e/provisioning/all_e2e_test.go
Disabling azure tests for centos operating system, until it is decided whether we deprecate it or simply look for another publisher. 
Fixes #
```release-note
None
```
> Disable centos tests for azure cloud provider

- pkg/cloudprovider/provider/azure/provider.go
- test/e2e/provisioning/all_e2e_test.go
Choose a different CentOS sku in azure, due to the removal of the current one.
Fixes #1040
```release-note
Use CentOS sku 7_9 instead of 7-CI  
```
> Choose the right centos sku in azure

- examples/cdi-operator.yaml
- examples/kubevirt-operator-0.19.0.yaml
- examples/machine-controller.yaml
This updates the CRDs so machine-controller is installable in Kubernetes 1.22+ clusters.
This is a prerequisite for https://github.com/kubermatic/kubermatic/issues/7457
```release-note
Upgrade CRDs to use apiextensions/v1
```
> Upgrade CRDs to apiextensions/v1

- .prow.yaml
- Dockerfile
The old images had the confusing entrypoint that needed to be run manually, which has since been fixed to just provide a clear `start-docker.sh` that containers run whenever they need to.
```release-note
NONE
```
> fix postsubmit for the new Docker images we use

- hack/ci-download-gocache.sh
- hack/ci-upload-gocache.sh
This is the sister PR to https://github.com/kubermatic/kubermatic/pull/7780
```release-note
NONE
```
> use a directory to make gocache separation easier to deal with

- .prow.yaml
Disabling vSphere e2e tests until vcenter is available again
Fixes #
```release-note
None
```
> Disable vsphere e2e tests

- .prow.yaml
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/packet/provider.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
So far the default Ubuntu version that we use to deploy Ubuntu OS is 18.04 LTS. This PR upgrade the default ubuntu image from 18.04 to 20.04. 
Fixes #
At the moment vSphere is blocked by the absence of vcenter.
```release-note
Upgrade default ubuntu version to 20.04
```
> Upgrade default ubuntu version to 20.04 LTS

- test/e2e/provisioning/all_e2e_test.go
At the moment, the current vSphere image that we have is not behaving as expected, die to some issue with the our subscription. Thus we are disabling the tests on vSphere until we get a valid subscription shortly.   
Fixes #
```release-note
None
```
> Disable e2e tests for vSphere cloud provider temporarily

- test/e2e/provisioning/all_e2e_test.go
Adjusting the RHEL image to run without registering the nodes which led to faster provisioning and also fixed the issue with ubuntu replicas using the same parent IP address.   
Fixes #
```release-note
None
```
> Enable e2e tests for vSphere cloud provider

- pkg/cloudprovider/provider/aws/provider.go
The current image filter for AMIs in AWS targets a legacy account for CentOS 7 images. CentOS (via their Community Platform Engineering team) started publishing their own images as per https://wiki.centos.org/Cloud/AWS. We should use those images instead.
The new location also has an ARM64 image.
Fixes #1069
```release-note
Use new source of CentOS 7 images (issued by CentOS CPE) in AWS when no AMI is set
```
> Use CentOS 7 images issued by CentOS CPE team

- .prow.yaml
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/aws/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
**What this PR does / why we need it**: Allows using the AWS AssumeRole calls to run user clusters in external AWS accounts.
Fixes #1072 
```release-note
Support AWS AssumeRole functionality to run user clusters in external accounts
```
> Add support for AWS AssumeRole functionality

- pkg/cloudprovider/provider/openstack/helper.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
Implements the change from Nova API to Glance API to get the required image information.
Fixes #1084 
- I had to change the Mux return of the test environment in `provider_test.go`. The new implementation uses `/v2/images` to list the images. I used the official example to make things clear.
- Ideally, you test this implementation in an e2e-Test to assure that it works as expected.
- Image API v2 is the de-facto standard, I have never seen a v1 API in the community, because V2 was released at Openstack Folsom (2012). Glance API v1 was deprecated in Newton (2016). So, it's absolutely save …
> Change getImageByName to use the Image client

- test/e2e/provisioning/migrateuidscenario.go
Fix a bug in the migrate machine uid tests. We use a fake client in order to run the migarate uid test. In the current code base, we populate the fake client with a machine object that has a name and a namespace value. There are some modifiers functions that we use, in order to update machine cr(e.g: adding finalizers). Since the machine cr that we populate the client with, only has a name and namespace, the cloud provider would simply fail to parse the cloud provider spec(since it nil) and thus the test will fail. 
This PR change this by populating the full object in the client, thus once the modifiers functions execute an update it will have the full copy of the machine not just the machine name and namespace.  …
> fix migrate uid test

- .prow.yaml
- cmd/machine-controller/main.go
- docs/cloud-provider.md
- examples/openstack-machinedeployment.yaml
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/cloudprovider/provider/openstack/types/cloudconfig.go
- pkg/cloudprovider/provider/openstack/types/cloudconfig_test.go
- pkg/cloudprovider/provider/openstack/types/types.go
- pkg/providerconfig/types_test.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-openstack-project-auth.yaml
OpenStack has deprecated `OS_TENANT_NAME / OS_TENANT_ID` in favor or `OS_PROJECT_NAME / OS_PROJECT_ID`, but these variables contain the same value.
ref kubermatic/kubermatic#6248
The cloudProviderSpec has been updated to add `projectName` and `projectID`. 
We first try to read `project` variables. If they are not defined, we fall back to tenant variables. Internally (ie `Config` struct), the values are stored under `project` variables, even if the user has specified it in `tenant` vars under `cloudProviderSpec`
```release-note
Add support for Openstack authentication with `project name` and  `project id`
```
> Openstack support auth with projectName/ projectID

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/rhel.go
- pkg/userdata/rhel/testdata/kubelet-containerd-v1.19-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.19-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.20-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Once a rhel machine is created and provisioned using machine controller, if we are using the username and password to register this machine we attach a subscription to it automatically. This is however doesn't give the option for the users to choose whether they would like to attach a subscription to the provisioned machine or not. Also this imposes a limitation for RHEL SCA which is not optimal. This PR gives the user the possibility to choose whether they would like to attach a subscription to the provisioned machine or not.  
Fixes #
```release-note
Optional …
```
> Include optional subscription attachment in RHEL MachineDeployment 

- test/e2e/provisioning/all_e2e_test.go
the test does not need to be launched for every k8s version and UUID migration. So it will reduce the number of necessary jobs to pass CI
Fixes #
```release-note
NONE
```
> run e2e test Openstack Project Auth Provisioning  for one version of k8S

- pkg/controller/machine/bootstrap.go
For centos `ssh_pwauth: no` doesn't work and we need to set it to false instead. 
**Which  issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #
```release-note
None
```
> disable ssh pwauth

- pkg/controller/machine/bootstrap.go
Write machine name to `/etc/hostname`, which is then later on consumed by kubelet to populate the flag `--hostname-override`
Fixes #
```release-note
NONE
```
> Populate /etc/hostname during bootstrap for ignition

- pkg/admission/machines.go
- pkg/providerconfig/types.go
- pkg/providerconfig/types_test.go
- pkg/userdata/flatcar/flatcar.go
Because AWS has very low user-data limit and ignition exceeding it preventing new flatcar instances to be created.
```release-note
Default flatcar provisionUtility on AWS to cloud-init
```
> Default flatcar provisionUtility on AWS to cloud-init

- pkg/userdata/flatcar/flatcar.go
The current implementation (#1119) sets the provisioning utility for AWS Flatcar machines to cloud-init only if the OperatingSystemSpec is not provided. Users might set some of the OperatingSystemSpec fields, but don't set the provisioning utility, in which case the current implementation wouldn't default to cloud-init.
With the proposed implementation, AWS Flatcar machines would get the provisioning utility unconditionally defaulted to cloud-init.
```release-note
Use cloud-init for Flatcar machines on AWS unconditionally
```
/assign @kron4eg @moadqassem 
/hold
> Use cloud-init for Flatcar machines on AWS unconditionally

- .golangci.yml
- pkg/cloudprovider/provider/aws/provider.go
Keeping up with AWS, this adds support for the `gp3` disk type. The difference to `gp2` is that you can define the IOPS for the disk to not depend on disk size for guaranteed IOPS.
Fixes #1123
```release-note
Add support for gp3 disk type in AWS
```
> Add support for gp3 disk type in AWS

- pkg/userdata/helper/kubelet.go
Eviction hard [mapStringString flag](https://pkg.go.dev/k8s.io/component-base@v0.23.1/cli/flag#LangleSeparatedMapStringString) is using symbol `<` as a separator between pairs.
```release-note
Fix evictionHard parsing
```
> Fix evictionHard parsing

- OWNERS_ALIASES
- pkg/cloudprovider/provider/OWNERS
- pkg/userdata/OWNERS
At the moment, machine-controller and OSM have duplications mainly for [cloudprovider](https://github.com/kubermatic/machine-controller/tree/master/pkg/cloudprovider) and [userdata](https://github.com/kubermatic/machine-controller/tree/master/pkg/userdata). In order to ensure that both of them are in-sync we have created this SIG that can take care of this synchronization.
Fixes #
```release-note
NONE
```
> Add SIG osm for overseeing changes for userdata and cloudprovider

- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
Spot prices in eu-central-1 seem to be causing the AWS e2e tests for spot instances to fail. Bumping this up so CI succeeds again (blocks a couple of PRs right now).
Fixes #
```release-note
NONE
```
> Move spot instance e2e test to different AZ in eu-central-1

- pkg/cloudprovider/provider/nutanix/provider.go
Minor fix to the disk size calculation for disk size validation for Nutanix specs. It compares kilobytes to bytes before, which meant the disk size needed to be really large to pass the webhook.
Fixes #
```release-note
NONE
```
> Fix disk size calculation in Nutanix spec validation

- cmd/webhook/main.go
- pkg/admission/admission.go
- pkg/admission/machinedeployments.go
- pkg/admission/machines.go
This PR fixes two problems:
1. #1136 introduced usage of an empty/fresh `Scheme` to generate a Kubernetes client for the webhook. Unfortunately, that broke reading machine spec values from secret or configmap references (#1142), as the client did not recognise `v1.Secret` or `v1.ConfigMap` resources anymore. We're using the default scheme now and only add OSM APIs to it.
Because https://github.com/kubermatic/machine-controller/blob/86b1621658bb2e4a38ce3ff3c7c8d0c621aff1b0/pkg/providerconfig/types.go#L109-L117 does not throw or log the error from `cvr.GetConfigVarStringValue`, I found this only by running a debugger and reading the `err` variable. We might want to adjust that as well, but this PR focuses on fixing the webhook.
2. The client request …
> Use default scheme and pass request context to ConfigVarResolver

- Makefile
Signed-off-by: Simon Bein <simontheleg@gmail.com>
Adds detection whether gnu or bsd base64 package is available and
selects the correct flag. This is necessary as MacOs (or BSD) uses the
-b flag while gnu uses the -w flag. Unfortunately there is no flag for
line-wrapping that both of them support
```release-note
None
```
> Use appropriate base64 flags

- pkg/admission/machinedeployments.go
- pkg/admission/machinedeployments_validation.go
This PR provides us a way to populate default OSP annotation in case it's missing. This is a requirement since OSM will only watch and cater resources that have this particular annotation.
Fixes #
Webhook is the best place to facilitate this mutation. Since in the future, we'll have an option to specify a custom value from the front-end/API but for defaulting webhook will be used.
```release-note
NONE
```
> Add mutating logic to populate OSP annotation based on OS flavor

- go.mod
- go.sum
- pkg/cloudprovider/provider/nutanix/client.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/nutanix/types/types.go
Adds support for setting a proxy URL for Nutanix via `NUTANIX_PROXY_URL` or a field in the spec. This will be helpful for our E2E testing, and it's nice to support this use case for users as well (although I'm unsure how frequent that will be).
Fixes #
```release-note
NONE
```
> Nutanix: Add support for proxy URL setting

- cmd/webhook/main.go
- pkg/admission/admission.go
- pkg/admission/machines.go
In KKP, these webhooks are deployed in a seed/master and worker(user) cluster architecture. Beforehand we were assuming that the only k8s client it needs is for the worker cluster since there was no need to interact with seed/master cluster. 
Although, after the addition of validations for OSM. There is a need to access resources, specifically OperatingSystemProfile, from the seed/master cluster.
To facilitate that we are splitting clients into:
1. Client - For seed/master, can use the in-cluster config
2. Worker Client - For worker cluster, needs out-of-cluster config
In case, the flag `worker-cluster-kubeconfig` is not specified then we assume that our subject is a single cluster and we use …
> Split clients into worker and seed(default) clients for webhooks

- pkg/controller/machine/bootstrap.go
Kubelet bootstrap kubeconfig is generated per machine, thus it is bounded to the machine resource not to the machine deployment resource. OSM handles requests per machine deployment, thus we need to move the bootstrap kubeconfig to the machine controller at this point. 
Fixes #
```release-note
None
```
> add bootstrap kubeconfig to the osm bootstraping

- pkg/cloudprovider/provider/nutanix/provider.go
This PR renames the `NUTANIX_ALLOW_INSECURE` environment variable to `NUTANIX_INSECURE`. [Terraform is using `NUTANIX_INSECURE`](https://registry.terraform.io/providers/nutanix/nutanix/latest/docs#argument-reference), so I think it would be nice to try to match environment variables used by Terraform. That would also make integration with KubeOne easier.
```release-note
Rename NUTANIX_ALLOW_INSECURE environment variable to NUTANIX_INSECURE
```
/assign @embik 
/hold
to discuss
> Rename NUTANIX_ALLOW_INSECURE to NUTANIX_INSECURE

- pkg/apis/plugin/plugin.go
- pkg/controller/machine/machine_controller.go
- pkg/userdata/amzn2/provider.go
- pkg/userdata/amzn2/provider_test.go
- pkg/userdata/centos/provider.go
- pkg/userdata/centos/provider_test.go
- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/provider_test.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/provider_test.go
- pkg/userdata/sles/provider.go
- pkg/userdata/sles/provider_test.go
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/provider_test.go
We currently use the `CloudProviderName` field in templates for:
* the `--cloud-provider` flag in the Kubelet service
* running commands only for some provider(s)
However, `CloudProviderName` contains the value returned by `GetCloudConfig` function. This function returns the cloud provider name used by Kubelet, and only if the provider has an in-tree cloud provider implementation (in-tree CCM). In other words, `CloudProviderName` will be empty on providers such as Nutanix, DigitalOcean, Hetzner, etc...
We encountered the issue when we tried to install some packages only on Nutanix machines in #1161. Because Nutanix doesn't have in-tree CCM, `.CloudProviderName` is empty, and the Nutanix-specific logic is not executed.  Therefore, this PR is a …
> Differentiate CloudProviderName and KubeletCloudProviderName in templates

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/provider_test.go
- pkg/userdata/centos/testdata/kubelet-containerd-v1.20-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.20-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-nutanix.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-vsphere.yaml
- pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/provider_test.go
- pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/provider_test.go
- pkg/userdata/ubuntu/testdata/nutanix.yaml
This PR changes the userdata so the following tasks are done on Nutanix machines:
* the `open-iscsi` package is installed on Ubuntu
* the `iscsi-initiator-utils` package is installed on CentOS and RHEL
* the `iscsid` service is enabled on Ubuntu/CentOS/RHEL
This is required for the Nutanix CSI driver to attach volumes.
```release-note
Install and enable iscsid on Nutanix machines
```
/assign @embik @moadqassem @ahmedwaleedmalik 
/hold
to test it manually
> Install and enable iscsid on Nutanix machines

- .prow.yaml
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/providerconfig/types.go
- pkg/providerconfig/types/types.go
- pkg/providerconfig/types/types_test.go
`GetConfigVarBoolValueOrEnv` never read the environment variable it was passed, as `stringVal` was always `"false"` when no value was passed (`configVar.Value` is a bool and defaults to `false` if not set), but the condition to read the env variable was `stringVal == ""`. This must be a pretty old bug as this code was introduced 4 years ago, but it was only ever used in `VSPHERE_ALLOW_INSECURE`, which is not in use in KKP for whatever reason.
This PR reworks the `ConfigVarBool` functions to make sure we can differentiate between an unset value and `false`.
This is needed as it also breaks `NUTANIX_ALLOW_INSECURE`, which is used in https://github.com/kubermatic/kubermatic/pull/8448.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
> Actually read environment variable in GetConfigVarBoolValueOrEnv

- pkg/providerconfig/types/types.go
- pkg/providerconfig/types/types_test.go
Small refinement for the initial PR #1154 that changed `ConfigVarBool`. This slims down the JSON generated by `MarshalJSON` if the value is unset.
Also adds more tests to make sure my changes are capable of handling various input.
Fixes #
```release-note
NONE
```
> Omit null value from marshalled JSON for ConfigVarBool

- pkg/controller/machine/machine_controller.go
We define a metric but have not set its value since refactoring the MC to use controller-runtime in #592. This PR restores setting the metric value.
```release-note
Fix machine_controller_workers metric always being 0.
```
> set the machine_controller_workers metric to an actual value

- test/e2e/provisioning/helper.go
The current RHEL image on Openstack is RHEL 8.0 which had few issues. This PR updates the RHEL 8 image to the latest(8.5)
Fixes #
```release-note
NONE
```
> update machine controller openstack rhel image

- pkg/userdata/helper/kubelet.go
[SeccompDefault](https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads) is a useful kubelet feature gate to isolate every container with seccomp by default. Since it's an alpha feature, it needs a kubelet feature gate _and_ a kubelet config value. This PR sets the config value if the feature gate is passed.
Fixes #
```release-note
Enable SeccompDefault setting if kubelet feature gate `SeccompDefault` is passed
```
> Enable SeccompDefault setting if kubelet feature gate is passed

- pkg/userdata/centos/provider.go
- pkg/userdata/centos/testdata/kubelet-containerd-v1.20-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.20-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-aws-external.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-nutanix.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-mirrors.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-proxy.yaml
- pkg/userdata/centos/testdata/kubelet-v1.21-vsphere.yaml
- pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
Change baseurl to vault.centos.org for CentOS 8.
```release-note
Change baseurl to vault.centos.org for CentOS 8
```
/assign @kron4eg @moadqassem
> Change baseurl to vault.centos.org for CentOS 8

- pkg/controller/machine/bootstrap.go
As of Feb 1 2022 centos8 packages been moved to the archeology site vault.centos.org so we are following the lead.
```release-note
Make centos8 work again
```
> Apply band-aid to reanimate CentOS8 bootstraping

- pkg/userdata/helper/kubelet.go
Sets kubelet ContainerLog settings when docker is used, although it has no effect.
This will prevent the default settings to be applied to kubelet where docker has different settings.
Ensures consistency to KubeOne which does the same for control-plane nodes.
```release-note
NONE
```
> Sets kubelet ContainerLog settings when docker is used

- examples/vsphere-datastore-cluster-machinedeployment.yaml
- examples/vsphere-machinedeployment.yaml
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/provider_test.go
- pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
- pkg/cloudprovider/provider/vsphere/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
The cluster id field for vSphere cloud provider, isn't used anywhere except in the labels of machines. It used to be part of the cloud-config however, it seems that it is not the case anymore. Thus we will remove it since it is not used by the provider. 
Fixes #
```release-note
Remove cluster-id from vsphere cloud provider 
```
> Remove cluster field from vSphere provider

- pkg/cloudprovider/provider/vsphere/types/types.go
Removal of this field is a backward compatibility issue and will break all the vSphere machineDeployment objects that had .Cluster in their ProviderSpec.
```release-note
fix: returned vSphere RawConfig.Cluster
```
> fix: returned vSphere RawConfig.Cluster

- pkg/cloudprovider/provider/aws/provider.go
Makes sure that we validate the max price field of the machine deployment spec when the aws instance is marked as spot instance. 
Fixes kubermatic/machine-controller#1197
```release-note
None
```
> Validate max price in spot instance request

- go.mod
- go.sum
- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/get_client.go
- pkg/cloudprovider/provider/azure/provider.go
Our Azure dependencies could use an update, this bumps both the Azure SDK go module and the used Azure APIs. That unlocks some functionality the old APIs were lacking (for example, filtering SKUs by location). KKP already uses more recent API versions.
Fixes #
```release-note
Azure SDK updated to v62.0.0, Azure compute API updated to `2021-11-01`, Azure network API updated to `2021-05-01`
```
> Update Azure SDK and API version

- pkg/cloudprovider/provider/alibaba/provider.go
- test/e2e/provisioning/all_e2e_test.go
The `ubuntu` and `centos` image names for Alibaba are hard-coded in https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/alibaba/provider.go#L46.
At the time ticket 7789 was created, both `ubuntu` and `centos` were failing.
Reproducing today and adding logs, the list of images we get is:
```
I0317 17:22:18.665019   17409 machine_controller.go:712]  image: Alibaba Cloud Linux  3.2104 LTS 64 bit Quick Boot-----------------------------------------------------
I0317 17:22:18.665041   17409 machine_controller.go:712]  image: Alibaba Cloud Linux  2.1903 LTS 64 bit Quick Boot-----------------------------------------------------
I0317 17:22:18.665048   17409 …
```
> Alibaba Images names

- cmd/machine-controller/main.go
- pkg/apis/plugin/plugin.go
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/baremetal/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/types/types.go
- pkg/cloudprovider/validationwrapper.go
- pkg/controller/machine/machine_controller.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/provider_test.go
- pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
- test/e2e/provisioning/migrateuidscenario.go
Adds `pod-cidrs` command line flag to accept pod-cidrs information from command line.
Changes `provider.Create` method to use the information during machine instance creation. 
Implements part of [#9294](https://github.com/kubermatic/kubermatic/issues/9294)
```release-note
NONE
```
> consider pod cidr information during instance creation

- go.mod
- go.sum
- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/types/errors.go
- pkg/cloudprovider/provider/anexia/types/types.go
- pkg/cloudprovider/provider/anexia/utils/utils.go
Signed-off-by: kstiehl <kevin.stiehl@numericas.de>
The Anexia API can behave a little bit weird sometimes. 
* Requests to the API get a negative status code because of some internal engine timeouts but in the VM get's provisionend anyways. We are now tracking whether we already provisionend an IP, and stop provisioning more of them on error.
* During deletion we use the new deprovisioning tracking
* The machine controller remembers ongoing provisionings and reattaches to them now after an error
Fixes #
```release-note
Anexia Provider is more resilient now and …
```
> Make anexia provider more resilient against errors

- .gitignore
- OWNERS_ALIASES
Signed-off-by: themue <frank.mueller@themue.dev>
Add Helene and Sankalp to the OWNERS_ALIASES to the group `machine-controller-maintainers`.
Fixes #
```release-note
NONE
```
> Add Helene and Sankalp to OWNERS_ALIASES

- examples/kubevirt-machinedeployment.yaml
- pkg/cloudprovider/provider/kubevirt/provider.go
This PR adds a common label `machine: md-<machine-id>` to all VM spawned by the same MachineDeployment.
We already have in all `machine` this common label. Re-using it to add it to the `VirtualMachines`.
Also taking this PR opportunity to update the `example` for the Kubevirt MachineDeployment specification.
Fixes #
```release-note
NONE
```
> Kubevirt Add common label to all VMs linked to the same MachineDeployment

- cmd/webhook/main.go
- pkg/admission/admission.go
- pkg/admission/machines.go
To allow better version skew policy service webhook is starting to validate provided constraint to avoid accidental sudden and violent version changes.
Fixes #1216
```release-note
New -kubernetes-version-constraints webhook flag
```
> New -kubernetes-version-constraints webhook flag

- docs/nutanix.md
We fully support Nutanix now in `machine-controller` and KKP, thus this PR removes the mention of "alpha status" in `docs/nutanix.md`.
Fixes #
```release-note
NONE
```
> Remove 'alpha' status of Nutanix implementation

- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/testdata/cloud-init_v1.20.14.yaml
- pkg/userdata/flatcar/testdata/cloud-init_v1.21.8.yaml
- pkg/userdata/flatcar/testdata/cloud-init_v1.22.5.yaml
- pkg/userdata/flatcar/testdata/cloud-init_v1.23.0.yaml
- pkg/userdata/flatcar/testdata/containerd.yaml
Fixes #
When `FlatcarConfig.DisableUpdateEngine` is set to true the update-engine.service is not stopped on new provisioned machines, which lead to an unwanted auto-updates to the latest flatcar version with a followed reboot. 
Only after this first reboot the service is then disabled.
The stop command stop the systemd service instantly to suppress the first auto-update on new provisioned machines.
```release-note
fix disable auto-update when FlatcarConfig.DisableUpdateEngine is set to true
```
> Flatcar stop disabled units

- .prow.yaml
This PR temporarily disable the Nutanix e2e tests when packages other than cloud provider nutanix have changed. For the time being Nutanix infra is down due to some maintenance. 
Fixes #
```release-note
None
```
> Disable nutanix e2e tests temporarily 

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/util/net.go
The PR is the first part to fix #1202. We force a fixed MAC address in the VM to have the device recognised when VM is restarted so that the system keeps the interface in the Up state.
After this PR the `Node` will be `Ready` state.
What remains to fix:
- the kubelet starts with the old ip as `--node-ip`
Fixes #1202
```release-note
Kubevirt: VM are created with a fixed randomised MAC address.
```
> Kubevirt: fixed randomised MAC address for VM

- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/get_client.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-azure.yaml
The provider spec for Azure did not support setting storage types for disks in Azure, thus spawning nodes with the high cost premium storage type by default. More cost-effective storage types might be sufficient for some workloads and users should be able to chose to optimise their cloud billing.
Fixes #1191
```release-note
Azure provider supports optionally setting OS disk and data disk SKUs via `osDiskSKU` and `dataDiskSKU` provider fields. If unset, disk SKUs are picked by Azure based on the VM SKU
```
> Add support for setting Azure disk types (OS and data)

- .golangci.yml
- pkg/cloudprovider/provider/openstack/provider.go
In this PR we workaround Opestack limitation in OVH Cloud. They do not allow to call GET regions endpoint.
Fixes #
```release-note
NONE
```
cc: @ovh @cbourgois
> make openstack provider work on ovh cloud

- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/gce/provider_test.go
- pkg/cloudprovider/provider/gce/types/types.go
Signed-off-by: Tomas Lamr <tomas@lamr.org>
Hello, we wanted to expose node selection API from google (SPOT/STANDARD) so that we can create a node pool of spot instances as in was.
Fixes #
```release-note
Support for specifying provisioning model for instances on GCE
```
> Expose google provisioning model to be able to acquire spot instances

- cmd/machine-controller/main.go
- pkg/apis/plugin/plugin.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/controller/machine/machine_controller.go
- pkg/providerconfig/types/types.go
- pkg/userdata/amzn2/provider.go
- pkg/userdata/centos/provider.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/provider_test.go
- pkg/userdata/rockylinux/provider.go
- pkg/userdata/sles/provider.go
- pkg/userdata/ubuntu/provider.go
Without  this change IP config  is static or not is decided just by checking if `.Network` is `nil`. 
All the fields in the `NetworkConfig` are not for static IP configuration anymore due to addition  of `IPFamily` field. 
This PR checks if the fields that specify static IP config are set or not and updates the code accordingly.  
PR also removes leftover refs to podCIDRs command  line flag. It was just wired through the code but never actually used.
Part of https://github.com/kubermatic/kubermatic/issues/9617
```release-note
NONE
```
> define static ip config

- Makefile
- examples/machine-controller.yaml
- test/tools/integration/master_install_script.sh
What it says on the title. Image publishing location is moved from `docker.io/kubermatic/machine-controller` to `quay.io/kubermatic/machine-controller` to not be affected by DockerHub pull rate limits anymore.
Fixes #1266
- I checked the prow job and it already signs in with quay.io credentials, so it seems no further change is needed for that.
- The repo under quay.io/kubermatic already exists and it seems images were pushed there occasionally.
```release-note
Container images are now published to `quay.io/kubermatic/machine-controller`
```
Signed-off-by: …
> Publish image to quay.io/kubermatic/machine-controller

- pkg/containerruntime/containerd.go
- pkg/containerruntime/containerruntime.go
- pkg/userdata/ubuntu/testdata/containerd.yaml
As discussed, this PR changes logic introduced with #1272 to only use containerd 1.5 in Kubernetes 1.24+. containerd 1.5 is now used for all Kubernetes versions still supported by `machine-controller`. Amazon Linux 2 is the exception as it does not have containerd 1.5 available.
Note: containerd installed with docker remains on 1.4 right now due to docker 19.03 only mentioning containerd 1.3 in its release notes. Maybe 1.5 works fine too, but let's investigate that in a separate PR which also bumps docker to 20.10.
Fixes #
```release-note
Update containerd to …
```
> Update containerd to 1.5 for all Kubernetes versions

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
- pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
This enables DHCPv6 on RHEL machines. 
Part of https://github.com/kubermatic/kubermatic/issues/9617
```release-note
NONE
```
> enable DHCPv6 on RHEL

- hack/run-machine-controller.sh
OSM is not GA yet, it's confusing for people who are trying to run machine-controller locally that it's enabled by default. Since you need to run OSM in parallel with machine-controller for everything to work in this case. We should disable it for now.
Fixes #
```release-note
NONE
```
> Remove use-osm flag from run-machine-controller script

- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/gce/provider_test.go
We are removing this check because GCP now supports dual stack in all  the regions. 
This is not directly documented. But the docs that had listed restrictions are gone and 
@rastislavs was able to create dual stack subnets anywhere. 
Partial fulfillment of https://github.com/kubermatic/kubermatic/pull/9751
```release-note
NONE
```
> remove check for dualstack unsupported zones in GCP

- pkg/cloudprovider/provider/azure/create_delete_resources.go
- pkg/cloudprovider/provider/azure/provider.go
We set finalizers for different resources created by the azure provider, but the cleanup logic effectively ignored their presence (except for removing them) and always tried to delete all resources. When cleanup is only partially successful, subsequent attempts should be faster because there is no reason to try deleting the VM again if we were able to delete it before.
Also replaces a bunch of `ListAll` calls for VMs because we know the resource group to query, so let's not list _all_ VMs.
Fixes #
```release-note
Azure resources are ignored during machine …
```
> Only attempt resource deletion in azure provider if finalizer is set

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
What it says at the top. Bumps Go in prow jobs to 1.18.2 and respectively updated `kubermatic/build` images.
Fixes #
```release-note
Update Go to 1.18.2
```
> Upgrade to Go 1.18.2

- test/tools/integration/master_install_script.sh
`Buildah` was removed from `http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/` and moved to `http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_20.04/`. 
The reason is still not well known. From ubuntu 20.10 and 21.x, this package is included in the OS default APT repositories. Maybe this is removed to `testing` repository because it isn't going to be actively maintained for 20.04 and 18.04, just an assumption.
Fixes # …
> Update package repo path for Buildah

- examples/kubevirt-machinedeployment.yaml
- pkg/cloudprovider/provider/kubevirt/provider.go
- test/e2e/provisioning/all_e2e_test.go
This PR intends to make the handling of Kubeconfig for KubeVirt consistent between KKP and machine-controller. 
* When Kubeconfig is specified directly in the CR then it should be base64 encoded.
* If referred using a secret or environment variable. Then it can either be an unencoded string or base64 encoded.
Fixes #
```release-note
```
> Refactor handling of Kubeconfig for KubeVirt

- Dockerfile
- test/tools/integration/hetzner.tf
- test/tools/integration/master_install_script.sh
We were previously using `kubic` packages from SUSE for the installation of buildah. Although they have been discontinued.
The alternative that I chose is to upgrade to `Ubuntu 22.04` in this case. Although eventually, we'll remove all of this in favor of KIND cluster and docker for building image with https://github.com/kubermatic/machine-controller/pull/1304
```
"NOTE: Kubic packages have been discontinued for Ubuntu 22.04 LTS. Current users of the Kubic repos for Ubuntu are highly recommended to uninstall the packages from the Kubic repos before upgrading to Ubuntu 22.04 LTS."
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR …
> Switch to Ubuntu 22.04 LTS for e2e tests

- pkg/admission/machines.go
We already removed the feature flag in kubelet, but in my opinion we should also block this from being set in a `MachineSpec`, as it mirrors to the `Node` object and I would expect that the `NodeSpec` fields are going to go away eventually as well.
Fixes #
```release-note
Machine specs for Kubernetes 1.24 or higher are not allowed to set spec.ConfigSource (as the dynamic kubelet configuration feature has been removed)
```
> Block setting spec.ConfigSource for Kubernetes 1.24+

- pkg/apis/cluster/common/consts.go
- pkg/userdata/helper/kubelet.go
This PR adds support for configuring the maximum number of pods per node.
The maximum number of pods can be adjusted by applying the following annotation on the Machine object:
```yaml
...
metadata:
annotations:
v1.kubelet-config.machine-controller.kubermatic.io/MaxPods: "<maxpods>"
...
```
If you're using MachineDeployment to manage Machines, you can apply this annotation by adding it to `spec.template.metadata.annotations` on MachineDeployment:
```yaml
...
...
spec:
template:
metadata:
annotations:
v1.kubelet-config.machine-controller.kubermatic.io/MaxPods: "<maxpods>"
...
```
xref …
> Support configuring MaxPods for Machines

- pkg/admission/machinedeployments_validation.go
Populate default OSP annotation if an empty value is provided for the OSP key/
Fixes #
```release-note
NONE
```
> Populate default OSP annotation if an empty value is provided for the OSP key

- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
- Created a service for os images instead of Pod Ip (subject to changes)
- OS images are now in /usr/share/nginx/html/images (mounted from a PVC), so not lost when the pod is restarted.
Fixes #
```release-note
NONE
```
> Fix KubeVirt e2e Os images http server

- pkg/cloudprovider/provider/anexia/provider.go
We found the current HTTP timeout of 30s is a bit short under some circumstances, so we change it to 120s.
```release-note
Anexia: change HTTP client timeout from 30s to 120s
```
> Anexia: increase HTTP client timeout

- go.mod
- go.sum
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/equinixmetal/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-equinixmetal.yaml
Adding support for equinixmetal metro field in machine controller. This is needed to enable machine controller equinixmetal cloud provider to pick any server available in a whole metro(group of facilities) to avoid availability problems when deploying multiple replica. 
Fixes #
```release-note
Equinixmetal metro support in machine controller 
```
> Add metro support for equinixmetal

- hack/run-machine-controller.sh
- pkg/userdata/amzn2/provider.go
- pkg/userdata/centos/provider.go
- pkg/userdata/flatcar/provider.go
- pkg/userdata/helper/helper.go
- pkg/userdata/helper/kubelet.go
- pkg/userdata/helper/kubelet_test.go
- pkg/userdata/rhel/provider.go
- pkg/userdata/rockylinux/provider.go
- pkg/userdata/sles/provider.go
- pkg/userdata/ubuntu/provider.go
- pkg/userdata/ubuntu/provider_test.go
- pkg/userdata/ubuntu/testdata/digitalocean-dualstack.yaml
- pkg/userdata/ubuntu/testdata/openstack-dualstack.yaml
`--node-ip` and `--cloud-provider` kubelet flags conflict in the dualstack setup.
In general, it is not expected to need to use `--node-ip` with external CCMs, as the the cloud provider is expected to know the correct IPs to return.
This PR
```
|--------------+------------------------------+----------------------------|
|              | KKP support for external CCM | --node-ip set in dualstack |
|--------------+------------------------------+----------------------------|
| DigitalOcean | No                           | Yes                        |
| OpenStack    | Yes                          | No                         |
|--------------+------------------------------+----------------------------|
```
**Which issue(s) this PR fixes** *(optional, in …
> set --node-ip depending on external CCM availaibilty in dualstack 

- test/e2e/provisioning/all_e2e_test.go
There are some changes in our azure subscription, regarding flatcar, rockylinux and rhel vm creation. Thus I am disabling the tests for those operating systems until the issue is resolved.
Fixes #
```release-note
None
```
> Disable a subset of azure tests temporarily

- test/e2e/provisioning/helper.go
`c3.small.x86` is not available in AM metro, so let's use `m3.small.x86` for CentOS E2E tests. We already use that instance size for Ubuntu and Rocky Linux E2E tests.
```release-note
NONE
```
/assign @moadqassem
> Equinix: use m3.small.x86 for CentOS E2E tests

- pkg/providerconfig/types/types.go
- pkg/providerconfig/types/types_test.go
To keep strings safe to embed inside HTML `json.Marshal()` encodes them using [HTMLEscape](https://github.com/golang/go/blob/go1.18.4/src/encoding/json/encode.go#L161). It replaces invalid bytes with the Unicode replacement rune. For example "<", ">" will be converted to "\u003c","\u003e", respectively. `json.Unmarshal` takes care of replacing these escape characters with the actual value. 
In general, this works fine for us but in the case of `ConfigVarString` we override the unmarshalling and marshalling behavior. And Unmarshalling [doesn't replace the escape characters](https://github.com/kubermatic/machine-controller/blob/master/pkg/providerconfig/types/types.go#L164).
This PR reworks the …
> Fix unmarshalling for `configvarstring` in cloudProviderSpec

- pkg/cloudprovider/instance/instance.go
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/baremetal/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/gce/instance.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/cloudprovider/provider/vmwareclouddirector/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine/machine_controller.go
- pkg/controller/machine/machine_test.go
`machine_controller` is matching Machine object with respective Node object by:
* matching expected ProviderID with actual ProviderID of the Node object
* matching IP addresses of Machine object with IP addresses of the Node object
Matching Machines and Nodes by ProviderID currently works only for some providers such as AWS and Azure. It doesn't work for GCP, vSphere, and some other providers. This is because we expect all providers to format ProviderID like `<provider-name>:///<instance-id>` but that's not the case. Instead:
* some providers use double-slash instead of triple-slash, e.g. `<provider-name>://<instance-id>`
* some providers use something other than `<instance-id>`, e.g. `<provider-name>:///<availability-zone>/<instance-id>`
That said, …
> Fix logic for finding node by ProviderID

- .prow.yaml
- pkg/cloudprovider/instance/instance.go
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/baremetal/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/fake/provider.go
- pkg/cloudprovider/provider/gce/instance.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/controller/machine/machine_controller.go
- pkg/controller/machine/machine_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-equinixmetal.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
This is a manual cherry-pick of #1351 to the `release/v1.43` branch, which is used on the KubeOne 1.4 release branch.
```release-note
Fix finding nodes by providerID for clusters with CCM or in-tree cloud provider
```
/assign @moadqassem @ahmedwaleedmalik
> [release/v1.43] Fix logic for finding node by ProviderID

- pkg/admission/machines.go
- pkg/controller/util/machine.go
Add label on machine to differentiate between the tool used for managing machine configurations.
Fixes #
```release-note
NONE
```
> Add label on machine to differentiate between the tool used for managing machine configurations

- pkg/cloudprovider/provider/anexia/instance.go
#1351 changed the mapping from Machine to Node, but left the `ProviderID()` method unimplemented for Anexia, this adds the implementation.
Our CCM currently does not set any prefix, which I guess could make problems when having a single cluster spanning multiple providers. At least they are fairly long and random, so chance for collision isn't too high .. still, if you need us to change that, I'll happily find a way for that.
Probably would make the most sense if @xmudrii takes a look at this, as I took that named TODO ^^'
```release-note
Implement ProviderID function for Anexia
```
> Implement ProviderID() for Anexia

- hack/lib.sh
- hack/update-fixtures.sh
- pkg/containerruntime/containerd.go
- pkg/containerruntime/docker.go
- pkg/userdata/centos/testdata/kubelet-containerd-v1.20-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-containerd-v1.20-aws.yaml
- pkg/userdata/ubuntu/testdata/containerd.yaml
This PR updates containerd to v1.5 for all Kubernetes versions because v1.4 has reached EOL.
xref https://github.com/kubermatic/kubeone/issues/2215
```release-note
Update containerd to v1.5 for all Kubernetes versions
```
> [release/v1.43] Update containerd to v1.5 for all Kubernetes versions

- .golangci.yml
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/azure/types/types.go
The public IP address SKU wasn't configurable before. This adds it, plus some validation around the field.
Fixes #1395
```release-note
Add new field `publicIPSKU` for Azure provider that configures the public IP address SKU (can be either `basic` or `standard`)
```
> Add `publicIPSKU` field to Azure provider

- pkg/cloudprovider/provider/kubevirt/provider.go
Align KubeVirt cloud config with upstream and stop exposing kubeconfig in machines.
Signed-off-by: Marcin Franczyk <marcin0franczyk@gmail.com>
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Align KubeVirt cloud config with upstream

- docs/cloud-provider.md
- examples/gce-machinedeployment.yaml
- examples/kubevirt-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-gce.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
This PR ensures that we always inject a base64-encoded kubeconfig in the kubevirt config, even if (in the future) an unencoded kubeconfig was provided in the e2e tests / via env vars. The same careful handling was added to the GCP SA, which also needs to be base64-encoded, which was never mentioned anywhere.
*Nothing changes for the users. This only affects our testing.*
/kind cleanup
```release-note
NONE
```
> improve kubeconfig/gcp handling of credentials in e2e tests

- docs/cloud-provider.md
- examples/gce-machinedeployment.yaml
- examples/kubevirt-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-gce.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
This is a manual backport of #1404.
/kind cleanup
```release-note
NONE
```
> [release/v1.42] improve kubeconfig/gcp handling of credentials in e2e tests (#1404)

- docs/cloud-provider.md
- examples/gce-machinedeployment.yaml
- examples/kubevirt-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-gce.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
This is a manual backport of #1404.
/kind cleanup
```release-note
NONE
```
> [release/v1.43] improve kubeconfig/gcp handling of credentials in e2e tests (#1404)

- docs/cloud-provider.md
- examples/gce-machinedeployment.yaml
- examples/kubevirt-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-gce.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
This is a manual backport of #1404.
/kind cleanup
```release-note
NONE
```
> [release/v1.45] improve kubeconfig/gcp handling of credentials in e2e tests (#1404)

- .prow/provider-anexia.yaml
- examples/anexia-machinedeployment.yaml
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/reconcile_context.go
- pkg/cloudprovider/provider/anexia/types/types.go
This extends the configuration for disks in provider Anexia. The important bit is the now-configurable disk performance type, but the config was revamped a bit to allow configuring multiple disks in the future.
As a side-effect, this PR also fixes CI for Anexia by disabling OperatingSystemManager for now as it is not yet supported.
In the first commit I did some cleanup of the config structs. This inflates the PR diff a bit, but it's separate commits at least.
The API changes are currently backwards compatible, so no "action required" needed for now.
```release-note
Allow configuring the disk performance type for provider Anexia
```
> Anexia: extend disk configuration

- docs/anexia.md
- examples/anexia-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/anexia/instance_test.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/reconcile_context.go
- pkg/cloudprovider/provider/anexia/types/errors.go
- pkg/cloudprovider/provider/anexia/types/types.go
- pkg/cloudprovider/provider/anexia/utils/utils.go
This PR backports a number of improvements in our provider to the v1.45 branch. We'd like to have this backported to this version, as this is the version used by the current KKP version.
Includes the following PRs:
* #1175 
* #1288 
* #1331 
* #1402
* #1410 - this one is not merged or approved yet
/kind feature
```release-note
* Anexia Provider is more resilient now and supports reattaching to ongoing provisionings after an error
* Anexia: change HTTP client timeout from 30s to 120s
* Allow configuring the disk performance type for provider Anexia
```
```documentation
NONE
```
> [release/v1.45] Improvements for Anexia

- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/anexia/instance_test.go
- pkg/cloudprovider/provider/anexia/provider.go
When creating a machine at, we always first reserve an IP address for it. Later when retrieving the addresses of that machine, we rely on the vminfo API, which has some delay as it retrieves the IPs from the running VM.
This commit adds the reserved address to the list of addresses returned from an instance, which should reduce provisioning time a bit and make it more stable.
Also fixes a long-standing TODO comment: marking internal IPs as internal.
/kind feature
[As per this comment](https://github.com/kubermatic/machine-controller/pull/1405#issuecomment-1216429137)
```release-note
NONE
``` …
> Anexia: return reserved IP when instance IPs are requested

- Makefile
GOFLAGS need to be passed with quotes to ensure they are not split over
multiple arguments to `make`.
<details>
<summary>Failure without the added quotes</summary>
```
$ make test-unit-docker
make: invalid option -- 'a'
Usage: make [options] [target] ...
Options:
-b, -m                      Ignored for compatibility.
-B, --always-make           Unconditionally make all targets.
-C DIRECTORY, --directory=DIRECTORY
Change to DIRECTORY before doing anything.
-d                          Print lots of debugging information.
--debug[=FLAGS]             Print various types of debugging information.
-e, --environment-overrides
Environment variables override makefiles.
-E STRING, --eval=STRING    Evaluate STRING as a makefile statement.
-f FILE, --file=FILE, …
```
> Makefile: fix test-unit-docker

- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Switches the folder for vsphere e2e tests to ci
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> switch to kubermati-ci folder in e2e tests

- pkg/userdata/helper/helper.go
- pkg/userdata/ubuntu/testdata/digitalocean-dualstack.yaml
- pkg/userdata/ubuntu/testdata/openstack-dualstack.yaml
Signed-off-by: Sachin Tiptur <sachin@kubermatic.com>
In case of Dualstack, mitigate the timing issue between interface IPv6 assignment and kubelet service bringup.
This is achieved by adding a check for IPv6 address while configuring env variables for kubelet service. If the IPv6 is not yet assigned, return an error, which in-turn triggers the restart of setup and kubelet service.
Fixes #[10871](https://github.com/kubermatic/kubermatic/issues/10871)
Verified for below combinations:
- Equinix - Rockylinux
- Hetzner - Ubuntu
```release-note
NONE
``` …
> Fix to mitigate race condition while configuring kubelet node ips

- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Bump Kubernetes versions used for E2E tests to 1.22.14, 1.23.11 and 1.24.5 respectively

- pkg/userdata/rhel/provider.go
- pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
- pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
- pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
- pkg/userdata/rockylinux/provider.go
- pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws-external.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-mirrors.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-proxy.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere.yaml
- pkg/userdata/rockylinux/testdata/kubelet-v1.24-aws.yaml
Signed-off-by: Sachin Tiptur <sachin@kubermatic.com>
IPv6 interface configuration was not proper and config files were flooded in failure scenarios. This PR fixes this bug
and Configures/enables IPv6 address for the interface in case of RHEL and RockyLinux which uses NetworkManager.
Fixes #[10871](https://github.com/kubermatic/kubermatic/issues/10871)
Manual tests and KKP CI dual stack e2e tests are done.
```release-note
NONE
```
```documentation
NONE
```
> Fix dualstack IPv6 addr assignment issue in rockylinux and RHEL

- hack/ci/setup-kind-cluster.sh
The image from https://raw.githubusercontent.com/flannel-io/flannel/v0.18.0/Documentation/kube-flannel.yml seems broken.
```
Failed to pull image "rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0": failed to read expected number of bytes: unexpected EOF
```
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Upgrade to flannel v0.19.2 for E2E tests

- examples/gce-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/gce/provider_test.go
- pkg/cloudprovider/provider/gce/types/types.go
Allows to use nested virtualization on GCP
Fixes #
/kind feature
```release-note
Enable nested virtualization for GCP cloud provider
```
```documentation
NONE
```
> Add an option to enable nested virtualization and CPU platform for GCP

- examples/kubevirt-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
This PR adds support for `TopologySpreadConstraint` for VMs which will spread user cluster nodes across infra-cluster nodes. And removes the Pod affinity/anti-affinity mechanism.
Fixes https://github.com/kubermatic/kubermatic/issues/10646
/kind feature
```release-note
Add support for topology spread constraint for KubeVirt VirtualMachines.
```
```documentation
TBD
```
Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>
> add support for topology spread constraint for VMs

- examples/gce-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider_test.go
- pkg/cloudprovider/provider/gce/service.go
- pkg/cloudprovider/provider/gce/types/types.go
Enables guest os features for GCP compute instance
https://cloud.google.com/compute/docs/images/create-custom#guest-os-features
Fixes #
/kind feature
```release-note
Enable Guest OS Features for GCP cloud provider
```
```documentation
NONE
```
> Add an option to enable guest os features at GCP

- examples/kubevirt-machinedeployment.yaml
- go.mod
- go.sum
Bump KubeVirt CDI to 1.55.0 and fix examples/kubevirt-machinedeployment.yaml.
Fixes #
/kind feature
```release-note
Bump KubeVirt CDI to 1.55.0
```
```documentation
NONE
```
> Bump KubeVirt CDI to 1.55.0

- .prow/e2e-features.yaml
- hack/ci/calico.yaml
- hack/ci/setup-kind-cluster.sh
- hack/lib.sh
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/verify.go
This is a bit complicated to explain but essentially the e2e tests running out of kind were only somewhat working, but flannel "covered" that up a bit. The problem is between the kind control plane and the joining nodes; CNI pods cannot talk to the Kubernetes API endpoint as the `Endpoints` for the "kubernetes" `Service` is an internal IP nodes will not be able to reach. This also affects `kube-proxy` never being able to properly start.
For some reason, flannel still marked the nodes as `Ready` (although technically they weren't), same for Cilium, but none _really_ worked for CNI and flannel broke during the CI cluster upgrade (machine-controller-webhook was no longer able to resolve DNS due to service IPs no longer properly routing).
This PR moves …
> Use Calico as CNI for e2e and disable node readiness checks

- hack/ci/setup-kind-cluster.sh
Found a leftover from the branch renaming work. This will correctly clone the KKP repo via it's `main` branch, as `master´ does not exist anymore.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Use 'main' as KKP branch instead of 'master' when cloning for cluster-exposer

- pkg/cloudprovider/provider/aws/types/cloudconfig.go
- pkg/cloudprovider/provider/aws/types/cloudconfig_test.go
- pkg/cloudprovider/provider/aws/types/testdata/simple-config.golden
Signed-off-by: Sachin Tiptur <sachin@kubermatic.com>
This PR adds NodeIPFamilies to GlobalOpts struct. This is required in Kubermatic repo for adding dual stack support with AWS CCM which is enabled with control plane version 1.24 onwards.
Fixes #
/kind feature
This is only a struct change, the actual logic will be added in Kubermatic repo.
```release-note
NONE
```
```documentation
NONE
```
> Dualstack support with AWS CCM

- pkg/containerruntime/config.go
- pkg/containerruntime/config_test.go
containerd can be configured for multiple registry mirrors per registry, this extends machine-controller to configure mirrors for registries other than docker.io, reusing the existing command line flag.
/kind feature
This should probably be documented, but didn't find where..
```release-note
Allow configuring containerd registry mirrors not only for docker.io
```
```documentation
NONE
```
> Extend containerd registry mirror config

- pkg/userdata/flatcar/provider.go
Fixes a bug where static networking configuration was being wrongfully set for flatcar.
Fixes #1468
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix static network rendering for flatcar

- examples/nutanix-machinedeployment.yaml
- pkg/cloudprovider/provider/nutanix/client.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/nutanix/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-nutanix.yaml
This PR adds the possibility to create a VM with an additional NIC for a storage subnet for the Nutanix provider. We need this as we use a dedicated network for our Nutanix storage provider.
/kind feature
I did the implementation as minimal as possible. But we where diskussing different options and I am open to change the code if you require it.
Second option would have been an "additionalSubnetNamess" List instead of the storageSubnetName field. But we were not sure if somebody needs more than two NICs anyways.
Third option would be replacing subnetName with a List. But this would break backwards compatibility. 
Let me know if you think any of the two options above would be a better …
> add optional additional subnets to Nutanix provider

- cmd/machine-controller/main.go
- code-of-conduct.md
- docs/kubevirt.md
- pkg/cloudprovider/provider/vsphere/network.go
Updating URLs that were referring wrongfully to the `master` branch. For example, https://github.com/kubermaric/machine-controller/blob/master/docs/registry-authentication.md no longer exists.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update GitHub URL references to use main branch

- pkg/cloudprovider/provider/aws/provider.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
CentOS changed their image names in a way our filters did not match anymore: https://wiki.centos.org/Cloud/AWS
Also added changes from https://github.com/kubermatic/machine-controller/pull/1484.
```release-note
Update CentOS AMI filter
```
```documentation
NONE
```
> Fix e2e tests: Update CentOS image filters & vcenter datastores

- pkg/cloudprovider/provider/kubevirt/provider.go
This PR cleans up a small wrong code. Behaviour does not change but this lines should go.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> KubeVirt cleanup small wrong code (preference error check)

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
This PR introduces `PrimarDiskImageSource` for the KubeVirt provider. The source can be `HTTP` or `PVC-Clone`.
If the source is `HTTP` with `preAllocatedDataVolume` as false, the VM disk-image will be downloaded from the HTTP source.
If the source is `HTTP` with `preAllocatedDataVolume` as true, the VM disk-image will be downloaded just once to create PreAllocatedDataVolume and VM Disks will be created by cloning over PreAllocatedDataVolume.
If the source is `PVC-Clone`, VM Disks will be created by cloning over custom-local-disks.
Fixes #https://github.com/kubermatic/kubermatic/issues/11234
/kind feature
**Does this PR introduce a user-facing change? …
> add http source for kubevirt VM Disk Image

- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
The `machine-controller` calls the providers `Create` method sequentially and only starts with the provisioning of another instance after `Create` returned without any errors. This PR changes the
- `Create` method to not block until the VM provisioning has completed 
- `Get` method to check via the instance status whether `InstanceID` and `ProvisioningID` are set
and utilizes the `Creating` state until the VM is ready.
This reduces the provisioning duration of node pools with more than one replica significantly as there are now only a couple of seconds (~10s) between the provisioning starts.
```release-note
Anexia: Refactor code to …
```
> Anexia Provider: Utilize `Creating` state instead of blocking `Create` call

- pkg/cloudprovider/provider/aws/provider.go
CentOS changed their image names in a way our filters did not match anymore: https://wiki.centos.org/Cloud/AWS
```release-note
Update CentOS AMI filter
```
```documentation
NONE
```
> [release/v1.42] Update filter for CentOS Linux images

- examples/kubevirt-machinedeployment.yaml
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
A small cleanup for Flavor and PodAffinity for KubeVirt.
- Removed even the // Deprecated from the example
- Removed useless MD fields in the e2e tests (they were already have no effect on the VM)
This PR is part of KKP + dashboard + machine-controller cleanup of any existing useless code/example/doc for GA.
Fixes #1492 
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> KubeVirt small cleanup: Flavor and PodAffinity

- pkg/cloudprovider/provider/aws/provider.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
CentOS changed their image names in a way our filters did not match anymore: https://wiki.centos.org/Cloud/AWS
```release-note
Update CentOS AMI filter
```
```documentation
NONE
```
> [release/v1.54] Update filter for CentOS Linux images

- docs/kubevirt.md
- examples/kubevirt-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
For https://github.com/kubermatic/kubermatic/issues/10923 we need to add cluster labels to KubeVirt VMs on creation.
```release-note
Add cluster labels to KubeVirt VM
```
```documentation
NONE
```
> Add cluster labels to kubevirt vm

- OWNERS_ALIASES
- pkg/cloudprovider/provider/kubevirt/OWNERS
Signed-off-by: Moritz Bracht <mail@morz.me>
This relieves dependency of sig-osm for kubevirt development.
```release-note
NONE
```
```documentation
NONE
```
> Set ownership for kubevirt provider to sig-virt

- docs/kubevirt.md
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
This change will block automatic VMs eviction which will then need to be handled externally. #1501 
```release-note
KubeVirt: Set eviction strategy of VMIs to external
```
```documentation
NONE
```
> Set EvictionStrategy to external on KubeVirt VMs

- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
- pkg/cloudprovider/provider/vsphere/types/cloudconfig_test.go
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Make CloudConfigToString a struct receiver function called String

- .prow.yaml
- pkg/cloudprovider/provider/aws/provider.go
- test/e2e/provisioning/testdata/machinedeployment-nutanix.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
CentOS changed their image names in a way our filters did not match anymore: https://wiki.centos.org/Cloud/AWS
```release-note
Update CentOS AMI filter
```
```documentation
NONE
```
> [release/v1.45] Update filter for CentOS Linux images

- .prow/e2e-features.yaml
- .prow/provider-kubevirt.yaml
Now that all repos have been tested and everything is OK for the switch of KubeVirt CI to our DC, here is the cleanup phase.
- I have updated the existing `preset-kubevirt` with the DC credentials.
- I can now switch back to `preset-kubevirt` that targets Kv cluster in our DC in all repos.
- I will then delete `preset-kubevirt-dc` from the infra repo.
In the vault:
- e2e-kubevirt now contains the DC credentials
- e2e-kubevirt-legacy contains the Equinix credentials.
Fixes #
/kind feature
```release-note
NONE
``` …
> KubeVirt switch CI to DC... cleanup phase

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
This PR adds validation for PVC osImageSource for kubevirt machines.
Using standard cloned images and custom-images are allowed only if the respective option is enabled.
- If the user tries to use a standard cloned image with image-cloning disabled, validation will fail.
- If the user tries to use a custom image with the custom image disabled, validation will fail.
- If the user tries to use a PVC source from a namespace other than the allowed ones, validation will fail.
Fixes #https://github.com/kubermatic/kubermatic/issues/11234
/kind feature
```release-note
NONE
``` …
> Add validation for image-cloning and custom-images for kubevirt

- cmd/machine-controller/main.go
- pkg/containerruntime/config.go
- pkg/containerruntime/containerd.go
- pkg/containerruntime/containerruntime.go
- pkg/containerruntime/docker.go
A [broken containerd release](https://github.com/containerd/containerd/pull/7838) made it impossible for our setup to provision working new nodes. This was a result of `machine-controller` automatically installing the latest `1.6*` release of `containerd` available.
This PR introduces the command line flag `--node-containerd-version` to manually pin the `containerd` version to install to a specific release.
The default for this new flag is empty, so the previously existing behavior remains intact if the flag is not specified.
Implements partially https://github.com/kubermatic/kubeone/issues/2545
/kind feature
**Does this PR introduce a user-facing change? Then add your Release Note …
> Allow manually configuring containerd version via CLI flag

- pkg/cloudprovider/provider/gce/config.go
We have an issue when creating ARM64-based instances on GCP:
```
An error of type = InvalidConfiguration, with message = Failed to insert instance: googleapi: Error 400: Invalid resource usage: 'Requested boot disk architecture (X86_64) is not compatible with machine type architecture (ARM64).'., invalidResourceUsage occurred 
```
It appears that the image we use is only compatible with AMD64-based instances. We would have to use another image with ARM64-based instances, which appears to be `projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts-arm64`.
We could do that by using the custom image option, but the current implementation assumes that the custom image is in the user's project. That's not the case because this image is in the …
> Allow specifying full image reference for GCP

- .prow/provider-kubevirt.yaml
- test/e2e/provisioning/all_e2e_test.go
At the moment, we are migrating KubeVirt cluster thus we need to disable the tests temporarily, as the ci keeps creating data volumes which blocks the migration process   
Fixes #
```release-note
None
```
```documentation
None
```
> Disable KubeVirt e2e tests

- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- hack/ci/run-e2e-tests.sh
- hack/lib.sh
- test/e2e/provisioning/all_e2e_test.go
A few weeks ago we introduced a way in Prow to disable certain cloud providers globally in our infrastructure. So intead of manually doing #1523, we can just rely on the global configuration. This PR adds support for these new `$<PROVIDER>_DISABLED` env variables and undoes the manual kubevirt changes from #1523.
/kind feature
```release-note
NONE
```
```documentation
NONE
```
> support prow-based provider disabling

- pkg/cloudprovider/provider/openstack/provider.go
Fixes a bug when machine-controller fails on 404 when deleting already gone floating-ip or server. 
Example failure
```
failed to delete machine at cloud provider, due to failed to clean up floating ip: failed to delete floating ip a87484bd-4ba6-4c18-8b7e-27b98606d240: Resource not found: [DELETE https://example-cloud.net:9696/v2.0/floatingips/a87484bd-4ba6-4c18-8b7e-27b98606d240], error message: {"NeutronError": {"message": "Floating IP a87484bd-4ba6-4c18-8b7e-27b98606d240 could not be found", "type": "FloatingIPNotFound", "detail": ""}}
```
Exact string match against `"Resource not found"` does not work because gophercloud v1.1.1, as well as previous versions, [return](https://github.com/gophercloud/gophercloud/blob/v1.1.1/errors.go#L193) …
> exact string match fails, use conventional errors.Is instead

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
Remove env vars that control PVC source.
Fixes #
/kind feature
```release-note
Remove KubeVirt image PVC source control from env vars
```
```documentation
NONE
```
> Refactoring of KubeVirt PVC image source

- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
Return `TerminalError` on 401 and 403 engine responses to signal invalid token configuration.
/kind cleanup
Please cherry-pick to v1.45 and v1.55.
```release-note
NONE
```
```documentation
NONE
```
> Anexia Provider: Return TerminalError on 401 and 403 engine responses

- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/types/types.go
When a new tag is being added to a vsphere machine deployment, a new tag is being created(if it didn't exist) and assign it to the machine. Once the machine is cleaned up, machine controller would simply delete that tag. Such a scenario is implemented in different cloud provider. However, vSphere tags are kinda different from a structure perspective, as tags must first belong to a tag category and then they can be assigned. In addition to that, tags can from different categories can be shared across different inventory resources. 
With that being said, if a machine being cleaned up and one tag is assigned to another VM, this tag will be lost. Also, if tags are created manually be users and assign across different resources, machine controller should …
> Refactor vsphere tagging mechanism

- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
Manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1483
/kind cleanup
```release-note
Anexia: Refactor code to reduce provisioning time for node pools with multiple replicas.
```
```documentation
NONE
```
> [release/v1.45] Anexia Provider: Utilize `Creating` state instead of blocking `Create` call

- docs/anexia.md
- examples/anexia-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/types/types.go
This PR adds support for named templates. Template IDs may break over time when a new build is released. With named templates the latest build can be selected without specifying the Template ID.
/kind feature
/kind documentation
/kind api-change
```release-note
Anexia Provider: Optionally configure "named templates" instead of (less stable) "template identifiers".
```
```documentation
https://github.com/kubermatic/machine-controller/blob/main/docs/anexia.md
```
> Anexia Provider: add support for named VM templates

- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/types/types.go
Either ID or a combination of Name and Category ID can be used to uniquely determine a tag.
Fixes #
/kind design
```release-note
VSphere tags can use name or ID as the unique identifier
```
```documentation
NONE
```
> Make ID an optional field for vSphere tags

- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
- pkg/userdata/flatcar/testdata/cloud-init_v1.24.9.yaml
- pkg/userdata/flatcar/testdata/cloud-init_v1.25.0.yaml
This PR configures the `rpc-statd` service as a dependency of `kubelet` via Flatcar Cloud-Init when `CloudProviderName` is "anexia". This is needed for our CSI driver to be able to connect to a NFS3 server from within containers without setting the `nolock` option.
/kind feature
The `rpc-statd` service is usually started by the nfs mount call. But since the mount is invoked from within a container, the hosts service doesn't start. Similar issue: https://github.com/coreos/bugs/issues/2074. 
```release-note
NONE
```
```documentation
NONE
```
> Anexia Provider: configure rpc-statd service as kubelet dependency

- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Removes the KubeVirt image repo cluster domain from the dns name as this one changed.
Its removed as its not needed.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Adjust kubevirt image repo

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
We discovered during QA that if you pass affinity settings for KubeVirt machines like this one:
```yaml
affinity:
nodeAffinityPreset:
key: test
type: hard
```
machine-controller will fail to create the VM because of this error:
```
E0208 10:40:53.418009       1 machine_controller.go:382] Failed to reconcile machine "mbhl5h4xkc-worker-bbxjzj-544cc46784-tz4rk": failed to create machine at cloudprovider, due to failed to create vmi: admission webhook "virtualmachine-validator.kubevirt.io" denied the request: spec.template.spec.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
```
This changes the generated expression to use a …
> Generate correct node affinity if no values are passed

- pkg/userdata/flatcar/provider.go
We have an issue where Flatcar nodes are not joining the cluster because the network configuration is broken. This happens only for machines that have `.ProviderSpec.Network.IPFamily` set (e.g. to `IPv4`). In such case, we try to configure IPAM on that node, however, in many cases IPAM is not used at all. This breaks the network configuration and usually that node doesn't have network connectivity at all.
This PR is supposed to fix that issue by configuring IPAM only if IPAM-related parameters are provided. This fix is already present on the `main` branch.
/kind bug
OSM doesn't support IPAM and is not affected by this issue.
**Does this PR introduce a user-facing change? Then add your …
> [release/v1.54] Fix Flatcar network issues when IPAM is not used

- .prow/provider-azure.yaml
- examples/operating-system-manager.yaml
- test/e2e/provisioning/helper.go
The E2E tests that we run in machine-controller should always be in sync with the latest state in OSM. This helps us avoid manually updating the image tag for testing OSM changes.
We also don't need to run tests on Azure unconditionally.
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Always use latest OSM image in e2e tests

- .prow/provider-aws.yaml
- pkg/cloudprovider/provider/anexia/instance_test.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
We run tests on AWS unconditionally, for E2E/sanity testing, which covers legacy userdata and OSM userdata testing. We should rely on spot instances for these tests for cost-cutting purposes.
A small downside of this is that we'll have to make adjustments in the code if we can't match the spot pricing from AWS. But imo it's still worth it.
Fixes #
/kind chore
The code changes are the result of running `gimps` on this repo. I just figured out that we don't have a job to verify imports in this repo. 
```release-note
NONE
```
```documentation
NONE
```
> Use AWS spot instances for tests that always run

- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/vmwareclouddirector/provider.go
Based on the CCM implementations and the information provided [here](https://github.com/kubermatic/machine-controller/issues/1552#issuecomment-1418706484) for VCD. I've implemented the providerID methods for VMware Cloud Director, Nutanix, and Linode. 
One drawback of not having providerID was that the cluster auto-scaler wouldn't work for these machines.
Fixes #
/kind feature
```release-note
Support for finding nodes by providerID for VMware Cloud Director, Nutanix, and linode.
```
```documentation
NONE
```
> Add providerID support for cloud providers

- .wwhrd.yml
- docs/cloud-provider.md
- examples/vultr-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/vultr/provider.go
- pkg/cloudprovider/provider/vultr/types/types.go
- pkg/providerconfig/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vultr.yaml
Signed-off-by: Yakul Garg <2000yeshu@gmail.com>
Fixes #1530 
/kind feature
```release-note
Support for Vultr cloud provider
```
```documentation
TBD
```
> Basic support for vultr provider

- pkg/cloudprovider/provider/openstack/provider.go
Currently, the timeout for the OpenStack client defaults to 15 seconds which is quite low. Self-hosted OpenStack environments might take more time than usual based on the networking configuration. Since we always authenticate before performing actions it's fine to increase the default timeout a bit.
Fixes #
/kind chore
```release-note
Default timeout for OpenStack client has been increased to 300 seconds.
```
```documentation
NONE
```
> Increase default timeout for OpenStack provider

- pkg/controller/machine/machine_controller.go
- pkg/controller/machine/metrics.go
Adds 2 new buckets to the `/metrics` endpoint about provisioning
- machine_controller_provisioning_time_seconds 
- machine_controller_deprovisioning_time_seconds
Fixes #1332
/kind feature
As previously discussed in the ticket #1332 here is our announced PR
```release-note
Added machine_controller_provisioning_time_seconds and machine_controller_deprovisioning_time_seconds metrics to the machine controller
```
```documentation
NONE
```
> Add metrics for provisioning nodes

- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/anexia/provider.go
This PR fixes a race condition in the Anexia provider Cleanup method - introduced in https://github.com/kubermatic/machine-controller/pull/1483 - which occurs when a machine is deleted before the instance has been created.
/kind bug
```release-note
Anexia Provider: fixed race condition in `Cleanup` method
```
```documentation
NONE
```
> Anexia Provider: Postpone machine cleanup when instance is still being created

- pkg/controller/machine/machine_controller.go
- pkg/controller/machine/metrics.go
Adds 2 new buckets to the /metrics endpoint about provisioning
- machine_controller_provisioning_time_seconds
- machine_controller_deprovisioning_time_seconds
Fixes #1574 
/kind feature
`golang v1.18` does not have support for `.Abs()` which broke the backport to `release/v1.54` triggered in #1572 
This PR fixes this by using `time.Since()`
```release-note
Added machine_controller_provisioning_time_seconds and machine_controller_deprovisioning_time_seconds metrics to the machine controller
```
```documentation
NONE
```
> Backport metrics node provisioning to v1.54

- pkg/userdata/flatcar/provider.go
- pkg/userdata/flatcar/testdata/cloud-init_v1.22.7.yaml
- pkg/userdata/flatcar/testdata/cloud-init_v1.23.5.yaml
- pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
This is a manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1553
```release-note
Enables "rpc-statd" service on new Anexia Machines using Flatcar with cloud-init to enable NFS functionality required by Anexia CSI driver.
```
> [release/v1.54] Anexia Provider: configure rpc-statd service as kubelet dependency

- examples/hetzner-machinedeployment.yaml
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/hetzner/types/types.go
This PR adds support for disabling the allocation and assignment of public IPv4 and IPv6 by default. Two new fields are introduced(`assignPublicIPv4` and `assignPublicIPv6`) when set, the values are gonna be set and propagated to the hetzner vms. If those are not set, the default behaviour is assigning public IPs. 
Fixes #
/kind feature
```release-note
Support Public IPs assignments for Hetzner cloud 
```
```documentation
None
```
> Support Private IP for Hetzner Cloud

- docs/cloud-provider.md
- examples/aws-machinedeployment.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/clusterv1alpha1machineWithProviderConfig/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/machinesv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
- pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineWithProviderConfig/aws.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
We recently changed the AWS account in which E2E tests are executed, so we need to adjust the VPC ID as well.
The documentation for the instance profile was wrong, since #412 we do not create it automatically anymore. So I had to manually create it by
* creating an IAM role as shown in the deleted code of  #412
* add the two AWS managed policies to that role
* then, because I could not figure out how to do it via the web console, create the instance profile and attach the role to it:
```
aws iam create-instance-profile --instance-profile-name kubernetes-v1
aws iam add-role-to-instance-profile --instance-profile-name kubernetes-v1 --role-name kubernetes-v1
```
**Does this PR introduce a user-facing …
> adjust VPC to the new one after we recently switched AWS accounts

- hack/ci/setup-machine-controller-in-kind.sh
This makes use of https://github.com/xrstf/protokol to dump the logs of machine-controller and OSM during the e2e tests, making them available as build artifacts. I presume this is safe as neither component should log credentials :crossed_fingers: 
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> store MC/OSM logs as artifacts during E2E tests

- examples/machine-controller.yaml
- examples/operating-system-manager.yaml
- pkg/admission/admission.go
The default manifests for the MC/OSM enabled a log level so verbose, it would log entire admission requests and responses to stdout, which contain potentially inline cloud provider credentials. That is, except for development, never intended and so we should not ship "bad" manifests.
/kind bug
```release-note
Reduce default log verbosity from 6 to 4.
```
```documentation
NONE
```
> reduce default log level to prevent credentials from leaking

- pkg/cloudprovider/provider/anexia/provider.go
This PR makes it possible to `Cleanup` Machines which have no instance (because they failed creation e.g. due to invalid configuration).
/kind bug
```release-note
Anexia Provider: fix cleanup of failed machines
```
```documentation
NONE
```
> Anexia Provider: fix cleanup of failed machines

- hack/ci/setup-machine-controller-in-kind.sh
- test/e2e/provisioning/testdata/machinedeployment-vmware-cloud-director.yaml
Fix E2E tests for VMware Cloud Director.
Fixes #
We would like to use the latest available image against main branch for OSM. We use image caching on our CI cluster which also caches the images with `latest` tag. This results in the actual latest image not being pulled and instead we end up using whatever is there in the cache.
To fix this issue, we determine the commit SHA for the last commit on main and then consume the image against it.
```release-note
NONE
```
```documentation
NONE
```
> Fix E2E tests for VMware Cloud Director

- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
- test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Since we have enabled the GA images for RHEL, in addition of having a default RHEL image added as part of the cloud provider controller, we don't need to include a custom iam for RHEL machines. 
Fixes #
/kind cleanup
```release-note
None
```
```documentation
None
```
> Remove custom AMI from rhel os

- pkg/cloudprovider/provider/openstack/provider.go
**What this PR does / why we need it**:  
My earlier RP #1526 did not fix the problem (details below).
Fixes #1526
**What type of PR is this?** 
/kind bug
It seems I managed to fool myself (and others) by using errors.Is. From errors.Is doc - "An error is considered to match a target if it is equal to that target..." which means even if there is an error with matching type errors.Is will be false unless its the same error.
The errors.Is is good to use with globally defined (using const / var), exported errors whereas in machine controller default-not-found error is a struct that also wraps some request/response information. Hence for different requests default-not-found error's value is different.
**Does this PR …
> fix not found check: errors.As for type match whereas errors.Is for value equality

- examples/gce-machinedeployment.yaml
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/gce/provider.go
- pkg/cloudprovider/provider/gce/service.go
- pkg/cloudprovider/provider/gce/types/types.go
Currently, it is not possible to create gce instances in a different gcp project than the one that is specified in the service token, as we derive the project id from it. This PR changes this behaviour so users can share a service account across different projects and explicitly specify in which project the machine should be created.
Fixes https://github.com/kubermatic/machine-controller/issues/1082
/kind feature
/kind api-change
```release-note
None
```
```documentation
None
```
> Refactor gcp client creating

- test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
The ARM tests complain about `eu-central-1a` and suggest to use `eu-central-1b`. Let's give it a try.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Use eu-central-1b for AWS arm tests

- pkg/controller/nodecsrapprover/controller.go
- pkg/controller/nodecsrapprover/controller_test.go
Since Kubernetes 1.27, CSRs do not necessarily contain `key encipherment` usage anymore (see https://github.com/kubernetes/kubernetes/issues/109077). This PR makes it so that the machine-controller does not refuse to approve those CSRs.
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> relax CSR validation to support Kubernetes 1.27

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
Update Go to 1.19.9 on release/v1.56 branch
/kind feature
```release-note
machine-controller is now built with Go 1.19.9
```
```documentation
NONE
```
> [release/v1.56] Update Go to 1.19.9

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
Update Go to 1.18.10 on release/v1.54 branch. This is the final Go 1.18 release.
/kind feature
```release-note
machine-controller is now built with Go 1.18.10
```
```documentation
NONE
```
> [release/v1.54] Update Go to 1.18.10

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
Update Go to 1.20.4.
/kind feature
```release-note
machine-controller is now built with Go 1.20.4
```
```documentation
NONE
```
> Update Go to 1.20.4

- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/reconcile_context.go
Add dns server configuration to vm definition
/kind feature
```release-note
Anexia Provider: Enable up to 4 custom dns entries
```
```documentation
NONE
```
> Anexia Provider: Configure dns servers

- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/reconcile_context.go
Backport for https://github.com/kubermatic/machine-controller/pull/1637
Fixes #
/kind feature
```release-note
Anexia Provider: Enable up to 4 custom dns entries
```
```documentation
NONE
```
> [release/v1.56] Anexia Provider: Configure dns servers

- README.md
Historically, machine-controller relied on user data plugins to generate configurations(cloud-config) for worker machines. Each operating system requires its own user-data plugin. These configs are then injected into the worker nodes using provisioning utilities such as [cloud-init](https://cloud-init.io) or [ignition](https://coreos.github.io/ignition). Eventually, the nodes are bootstrapped.
Over time, it has been observed that this workflow has certain limitations.
- Machine Controller expects **ALL** the supported user-data plugins to exist and be ready. User might only be interested in a subset of the available operating systems. For example, user might only want to work with `ubuntu`.
- The user-data plugins have templates defined …
> Deprecate user data plugins

- Makefile
- README.md
- cmd/webhook/main.go
- examples/machine-controller.yaml
- hack/ci/setup-machine-controller-in-kind.sh
Use cert-manager for certificates for machine-controller webhooks.
Fixes #
/kind chore
```release-note
[ACTION REQUIRED] The default values for webhook flags `tls-cert-path` and `tls-key-path` have been changed to `/tmp/cert/tls.crt` and `/tmp/cert/tls.key` respectively. This is a result of updating it to use certificates generated from cert-manager. 
```
```documentation
NONE
```
> Switch to cert-manager for certificates

- README.md
- docs/cloud-provider.md
- pkg/cloudprovider/provider.go
After discussions on SIG Cluster Management, this is the short-term change we have come up with to clarify that some providers have been contributed by the community and don't get the same maintenance care from the development team as others (because we cannot test them).
This PR also moves the providers into a dedicated `communityProviders` map to codify the distinction, but from a user perspective, nothing changes.
It's a follow-up to #1622.
Fixes #
/kind documentation
```release-note
Clarify provider status for Linode, Vultr and OpenNebula as community providers
``` …
> Add documentation for community providers

- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
Provisioning a VM without defining a `Network` in the `providerConfig` object results in a nil pointer exception. This bug got introduced by https://github.com/kubermatic/machine-controller/pull/1637
/kind bug
We'd love to get a backport of these changes in v1.54
```release-note
Anexia Provider: Fix nil pointer exception when providing no network configuration
```
```documentation
NONE
```
> Fix empty network config handling

- examples/vsphere-datastore-cluster-machinedeployment.yaml
- examples/vsphere-machinedeployment.yaml
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/provider_test.go
- pkg/cloudprovider/provider/vsphere/rule.go
- pkg/cloudprovider/provider/vsphere/types/types.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
This PR introduces vmware anti affinity rule creation, per machine.
To ensure a concurrent safe usage of the vsphere api, the create or update operation are synced via mutex which is only unlocked if the api returns the desired change or a timeout appears. 
This feature can be enabled/disabled by setting: `vmAntiAffinity: true` in the cloud provider spec.
Required Permissions:
AutoDeploy:
- Rule:
- Create
- Delete
- Edit
Host:
- Inventory:
-  Modify cluster
Docs required for the updated permissions.
Fixes #1340 
/kind feature
```release-note
Add VMs to an Anti-Affinity …
```
> Add vmware anti-affinity for machine sets

- hack/ci/setup-kind-cluster.sh
This ensures we do not accidentally get a more recent version than we can handle, as `k8s.io/kube-openapi` quickly required Go 1.19/generics. See for example the 2 different kube-openapi versions cloned in https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_machine-controller/1654/pull-machine-controller-e2e-kubevirt/1664813514599960576
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.54] pin cluster-exposer to a Go 1.18 compatible release

- go.mod
- go.sum
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/controller/machine/machine_controller.go
- test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
**Manual backport of https://github.com/kubermatic/machine-controller/pull/1645**
Allow external CCMs to handle failing node objects before MC takes any action.
It prevents race condition between MC and CCM.
The PR introduces a `handleNodeFailuresWithExternalCCM` function that:
>handleNodeFailuresWithExternalCCM reacts to node status discovery of CCM's node lifecycle controller.
>If an instance at cloud provider is not found then it waits till CCM deletes node objects, that allows:
>   - create a new instance at cloud provider
>   - initialize a new node object - the object should not be reused between instance creation
>     for example, instance foo that got deleted and recreated should initialize a completely new node object
>     instead of …
> [release/v1.54] Allow external CCMs to handle node objects before MC

- docs/vsphere.md
- examples/vsphere-datastore-cluster-machinedeployment.yaml
- examples/vsphere-machinedeployment.yaml
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/network.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/provider_test.go
- pkg/cloudprovider/provider/vsphere/types/types.go
This PR adds support for configuring multiple networks for VMs on vSphere. The field `vmNetName` is considered deprecated and `networks` should be used instead. In case both network and vmNetName are specified, the validating webhooks will reject the machine deployment.
Fixes #1671
/kind feature
```release-note
* Support for configuring multiple networks for vSphere.
* [Action Required] The field `vmNetName` is considered deprecated for vSphere and `networks` should be used instead.
```
```documentation
NONE
```
> Support for configuring multiple NICs for vSphere

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
Add support for OCI VM image source for `docker` and `oci-archive` implemented by [CDI](https://github.com/kubevirt/containerized-data-importer/blob/v1.55.2/staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go#L174-L177).
see also: https://github.com/kubermatic/kubermatic/issues/12341
/kind feature
```release-note
kubevirt: support OCI VM image source
```
```documentation
TBD
```
> KubeVirt: support for OCI VM image source

- .prow/verify.yaml
The `pull-machine-controller-license-validation` was failing with:
```
go: downloading github.com/Azure/go-autorest/autorest/validation v0.3.1
github.com/kubermatic/machine-controller/pkg/admission imports
golang.org/x/crypto/ssh imports
golang.org/x/crypto/curve25519 imports
crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/local/go/src/crypto/ecdh)
```
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.54] Fix CI job for license validation

- pkg/cloudprovider/provider/vsphere/provider.go
In case user has specified `DatastoreCluster` for a machine deployment on vSphere, we should use that as the `datastore` in cloud-config so that the disks attached to the VM are placed accordingly.
Fixes #
/kind bug
```release-note
vSphere: Fix a bug where datastore cluster value was not being propagated to the cloud-config
```
```documentation
NONE
```
> Propagate datastore cluster for vSphere to cloud-config

- go.mod
- go.sum
- pkg/apis/cluster/v1alpha1/conversions/conversions_test.go
- pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec_test.go
The `github.com/ghodss/yaml` package is no longer actively maintained. There are numerous inquiries about the project's status on its issue tracker: https://github.com/ghodss/yaml/issues. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.
`github.com/ghodss/yaml` is only used in tests files so we can safely replace it and remove 1 extra dependency.
/kind cleanup
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

- hack/ci/setup-kind-cluster.sh
Socat was removed from kind v0.20.0 through https://github.com/kubernetes-sigs/kind/pull/3155.
Fixes #
/kind chore
```release-note
NONE
```
``` documentation
NONE
```
> Install socat explicitly in `kind` cluster

- examples/vultr-machinedeployment.yaml
- go.mod
- go.sum
- pkg/cloudprovider/provider/vultr/provider.go
- pkg/cloudprovider/provider/vultr/types/types.go
There has been a bug introduced because of vultr wherein the tags on instances are eventually consistent due to which machine controller is led to believe that the instance was not created as we poll instance based on label and tags. This PR wait for complete creation of the instance so that eventual fetches to get machine are more deterministic
Additionally, there is the support for Vultr bare metal instances
And suppport for specifying VPC v1/v2 for instances has been added in accordance to https://www.vultr.com/api/#tag/instances/operation/create-instance and https://www.vultr.com/api/#tag/baremetal/operation/create-baremetal
Fixes #1704
/kind bug
/kind feature
**Special notes for …
> Fix isssue of creation of multiple vultr instance due to eventual consistency

- pkg/cloudprovider/provider/aws/provider.go
Pin flatcar on AWS to 3510.2.8 since the latest version 3602.2.0 is broken. 
Reference: https://github.com/kubermatic/kubermatic/issues/12690
Fixes #
/kind bug
```release-note
Pin flatcar on AWS to 3510.2.8
```
```documentation
TBD
```
> Pin flatcar on AWS to 3510.2.8

- pkg/cloudprovider/provider/aws/provider.go
This reverts commit e6de2fe75fb141c6d8a937e0756f1376e0e792f9 since this issue is [resolved in OSM](https://github.com/kubermatic/operating-system-manager/pull/314) now and we don't need to pin the image for AWS anymore.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Revert "Pin flatcar to 3510.2.8 (#1711)"

- examples/operating-system-manager.yaml
- hack/ci/setup-kind-cluster.sh
- hack/ci/setup-machine-controller-in-kind.sh
- pkg/cloudprovider/provider/aws/provider.go
This reverts commit b3fe8a253386349fd57fb6652e07f6dcf7de1c6d since this issue is [resolved in OSM](https://github.com/kubermatic/operating-system-manager/pull/314) now and we don't need to pin the image for AWS anymore.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.57] Revert "Pin flatcar to 3510.2.8 (#1712)"

- examples/operating-system-manager.yaml
- hack/ci/setup-kind-cluster.sh
- hack/ci/setup-machine-controller-in-kind.sh
- pkg/cloudprovider/provider/aws/provider.go
This reverts commit 1937295d5f9b4fa503aed2af84a3b7d952daf6d6 since this issue is [resolved in OSM](https://github.com/kubermatic/operating-system-manager/pull/314) now and we don't need to pin the image for AWS anymore.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.56] Revert "Pin flatcar to 3510.2.8 (#1713)"

- examples/operating-system-manager.yaml
- hack/ci/setup-kind-cluster.sh
- hack/ci/setup-machine-controller-in-kind.sh
- pkg/cloudprovider/provider/aws/provider.go
This reverts commit b3607e1011b9fe14e60bcf0d20098a1254826589 since this issue is [resolved in OSM](https://github.com/kubermatic/operating-system-manager/pull/314) now and we don't need to pin the image for AWS anymore.
Fixes #
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> [release/v1.54] Revert "Pin flatcar to 3510.2.8 (#1714)"

- docs/operating-system.md
- test/e2e/provisioning/all_e2e_test.go
Hetzner has deprecated their CentOS 7 image. CentOS 7 was/is the only release we ever supported and so this now means that there is no CentOS support at all anymore on Hetzner.
Fixes #
/kind cleanup
```release-note
Removed support for centos with Hetzner
```
```documentation
NONE
```
> Drop centos support for Hetzner

- .golangci.yml
- pkg/admission/machines.go
- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/gce/instance.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/opennebula/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vmwareclouddirector/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vultr/provider.go
- pkg/controller/machine/controller.go
- pkg/providerconfig/types/types.go
machine-controller will inject provider-id for the machines that are created against cloud providers that don't have in-tree or external CCM support. The generated providerID will be configured on the machine and node respectively.
Fixes #1552
/kind feature
```release-note
Machine-controller will inject provider-id for the machines that are created against cloud providers that don't have in-tree or external CCM support
```
```documentation
NONE
```
> Configure provider-id for the machines/nodes

- .golangci.yml
- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- hack/update-fixtures.sh
- hack/verify-licenses.sh
Upgrade to Go 1.21.3.
Fixes #
/kind feature
```release-note
Machine-controller is now built using Go 1.21.3
```
```documentation
NONE
```
> Upgrade to Go 1.21.3

- pkg/cloudprovider/provider/aws/provider.go
The e2e dualstack tests started to fail consistently
https://public-prow.loodse.com/job-history/gs/prow-dev-public-data/pr-logs/directory/pre-kubermatic-dualstack-e2e-aws-canal
```
2023-11-22T13:18:27.476Z	info	wait/wait.go:85	Waiting: 3 of 4 nodes are ready (unready: [])	{"provider": "aws", "cni": "canal", "ipfamily": "IPv4+IPv6", "cluster": "dualstack-e2e-7tr4m"}
2023-11-22T13:18:57.469Z	info	wait/wait.go:85	Waiting: failed to list nodes: client rate limiter Wait returned an error: context deadline exceeded	{"provider": "aws", "cni": "canal", "ipfamily": "IPv4+IPv6", "cluster": "dualstack-e2e-7tr4m"}
cloud_providers_dualstack_test.go:455: Not all nodes did get ready: context deadline exceeded; last error was: failed to list nodes: client rate …
```
> aws: fix rocky linux description filter

- docs/operating-system.md
- pkg/cloudprovider/provider/gce/config.go
- test/e2e/provisioning/all_e2e_test.go
Add Flatcar Linux support for GCE.
Reference: https://www.flatcar.org/docs/latest/installing/cloud/gcp/
xref https://github.com/kubermatic/kubermatic/issues/12728
/kind feature
```release-note
Flatcar is now supported on GCE
```
```documentation
TBD
```
> Flatcar Support for GCE

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- examples/operating-system-manager.yaml
- hack/update-fixtures.sh
- hack/verify-licenses.sh
This bumps Prow jobs for the `main` branch to use a build image that includes Go 1.21.5.
Towards https://github.com/kubermatic/release/issues/22
/kind chore
```release-note
Machine Controller is now built using Go 1.21.5
```
```documentation
NONE
```
> Update Prow jobs to build image with Go 1.21.5

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- examples/operating-system-manager.yaml
- hack/update-fixtures.sh
- hack/verify-licenses.sh
This bumps Prow jobs for the `release/v1.58` branch to use a build image that includes Go 1.21.5.
Towards https://github.com/kubermatic/release/issues/22
/kind chore
```release-note
Machine Controller is now built using Go 1.21.5
```
```documentation
NONE
```
> [release/v1.58] Update Prow jobs to build image with Go 1.21.5

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
- hack/verify-licenses.sh
This bumps Prow jobs for the `release/v1.57` branch to use a build image that includes Go 1.20.12.
Towards https://github.com/kubermatic/release/issues/22
/kind chore
```release-note
Machine Controller is now built using Go 1.20.12
```
```documentation
NONE
```
> [release/v1.57] Update Prow jobs to build image with Go 1.20.12

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
This is important for live migration because only `RWX` volumes can be live migrated
https://kubevirt.io/user-guide/operations/live_migration/#limitations
see also: https://github.com/kubermatic/kubermatic/issues/12860
/kind feature
```release-note
kubevirt: allow setting storage volume access types
```
```documentation
TBD
```
> kubevirt: allow setting storage volume access types

- test/e2e/provisioning/helper.go
E2E tests are failing due to lower spot price:
```
SpotMaxPriceTooLow: Your Spot request price of 0.02 is lower than the minimum required Spot request fulfillment price of 0.0216.
```
Reference: 
- https://github.com/kubermatic/machine-controller/pull/1750#issuecomment-1873412795
- https://github.com/kubermatic/machine-controller/pull/1753#pullrequestreview-1805561738
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> AWS: increase spot instance price

- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/types/types.go
Adds a field to check if a IP reservation is still valid, if the IP is no longer valid a new one is requested.
This fixes a bug where we use a IP reservation that expired already for a VM, if the VM provisioning failed, which then leads to a race condition. In which we wait for the VM provisioning to finish, but it can't due the IP being no longer useable, but we also never request a new IP in that case.
/kind bug
Please backport to version v1.57
```release-note
Anexia: Fix IP reservation related race condition.
```
```documentation
NONE
```
> Anexia: Adds field to check if a IP reservation is still valid

- cmd/webhook/main.go
- pkg/admission/admission.go
Refactor the webhook to use the controller-runtime provided webhook.Server instead of a plain HTTP server. The biggest benefit this brings, is it automatically loading changed certificate files instead of forever using the ones present when the server was started.
I'm not quite sure, I'll label this as feature but the webhook server not reloading changed certificates could also be seen as a bug.
/kind feature
This could have been implemented by using the controller-runtime CertWatcher manually, but that would've been more code and aligning machine-controller with the ecosystem-provided standards seems worth it.
**Does this PR introduce a user-facing change? Then add your Release Note …
> webhook: refactor to use controller-runtime server

- .golangci.yml
- pkg/admission/machines.go
- pkg/cloudprovider/provider/anexia/instance.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/gce/instance.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/opennebula/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/vmwareclouddirector/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vultr/provider.go
- pkg/controller/machine/controller.go
- pkg/providerconfig/types/types.go
Manual backport of #1723 
/kind feature
```release-note
Machine-controller will inject provider-id for the machines that are created against cloud providers that don't have in-tree or external CCM support
```
```documentation
NONE
```
> [release/v1.57] Configure provider-id for the machines/nodes 

- .prow/provider-vsphere.yaml
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/rule.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-anti-affinity.yaml
Fixes concurrency issues with the vSphere anti-affinity feature. I've also added an E2E test to properly test the feature.
Fixes #1774
/kind bug
```release-note
vSphere: fix anti-affinity DRS configuration for VMs
```
```documentation
NONE
```
> Fix vSphere anti-affinity

- .prow/provider-vsphere.yaml
- pkg/cloudprovider/provider/vsphere/helper.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vsphere/rule.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere-anti-affinity.yaml
This is a manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1779
```release-note
vSphere: fix anti-affinity DRS configuration for VMs
```
/kind bug
> [release/v1.57] Fix vSphere anti-affinity

- pkg/controller/util/machine.go
When fetching the MachineDeployment against Machine, to propagate user data, we were incorrectly assuming that the namespace would be `kube-system`. This is wrong since users can create MD/MS/Machine in any namespace.
Fixes #
/kind bug
```release-note
Fixes a bug where namespace kube-system was hardcoded for finding the MachineDeployment against a Machine
```
```documentation
NONE
```
/cherry-pick release/v1.59
> Fix namespace for Machinesets

- examples/anexia-machinedeployment.yaml
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/types/types.go
We found some old patches that are probably still worth adding and I combined them with a new feature here in this PR:
* use `pkg/cloudprovider/util.HttpClient` to enable request/response logging
* fix handling for 404 responses when deleting a VM
* add config attribute to specify the CPU performance type
/kind bug
/kind feature
Since this is all localized in the Anexia provider and all just small changes, I figured there's no harm in combining that into a single PR.
```release-note
Anexia: you can now configure the CPU performance type
```
I extended the example `MachineDeployment` in …
> Anexia: various patches (request/response logging, CPU performance type, 404 fix on delete)

- pkg/cloudprovider/provider/aws/provider.go
`*Rocky-8-EC2-8*.x86_64` doesn't work anymore and we need to drop `-8*` https://github.com/kubermatic/kubeone/blob/main/examples/terraform/aws/variables.tf#L220
Fixes #
/kind chore
```release-note
NONE
```
```documentation
NONE
```
> Update AMI filter for rocky linux

- hack/ci/setup-kind-cluster.sh
- pkg/cloudprovider/provider/aws/provider.go
This is a manual backport of #1803.
/kind chore
```release-note
Update AWS AMI filter for rocky linux 8
```
```documentation
NONE
```
> [release/v1.59] Update AMI filter for rocky linux (#1803)

- examples/operating-system-manager.yaml
- pkg/cloudprovider/provider/aws/provider.go
This is a manual backport of #1803.
/kind chore
```release-note
Update AWS AMI filter for rocky linux 8
```
```documentation
NONE
```
> [release/v1.57] Update AMI filter for rocky linux (#1803) / Bump OSM to 1.3.6

- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/aws/provider.go
- pkg/cloudprovider/provider/azure/provider.go
- pkg/cloudprovider/provider/baremetal/provider.go
- pkg/cloudprovider/provider/digitalocean/provider.go
- pkg/cloudprovider/provider/equinixmetal/provider.go
- pkg/cloudprovider/provider/gce/config.go
- pkg/cloudprovider/provider/hetzner/provider.go
- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/linode/provider.go
- pkg/cloudprovider/provider/nutanix/provider.go
- pkg/cloudprovider/provider/opennebula/provider.go
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/scaleway/provider.go
- pkg/cloudprovider/provider/vmwareclouddirector/provider.go
- pkg/cloudprovider/provider/vsphere/provider.go
- pkg/cloudprovider/provider/vultr/provider.go
No need for this check in the `getConfig()` function
```	
if provSpec.Value == nil {
return nil, nil, fmt.Errorf("machine.spec.providerconfig.value is nil")
}
```
because it already exists in `providerconfigtypes.GetConfig()` function
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> Delete provSpec redundant check in MC providers

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/ci/calico.yaml
- hack/update-fixtures.sh
- hack/verify-licenses.sh
This PR is to update Go version to 1.22.4.
Related to https://github.com/kubermatic/infra/pull/2707
Fixes #
/kind chore
```release-note
Update Go version to 1.22.4
```
```documentation
NONE
```
> Bump Go version to 1.22.4

- pkg/cloudprovider/provider/hetzner/provider.go
This should make it possible to use operating systems on Hetzner Cloud, that are not natively supported, by using custom images (snapshots).
A side-effect of this commit is, that images returned by `getNameForOs()` are now also validated against the Hetzner API.
For reference: #1817
Requirements to use custom operating systems:
1. Create a snapshot of the operating system you want to use on Hetzner Cloud, e.g. using https://github.com/apricote/hcloud-upload-image/
2. Add a new `OperatingSystemProfile`
3. Set the image in `MachineDeployment` to the name of the snapshot created in step 1
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Hetzner: Skip operating system validation if custom image is provided

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
- hack/verify-licenses.sh
This PR is to update the Go version to 1.22.5
Related to https://github.com/kubermatic/infra/pull/2765
Fixes #
/kind chore
```release-note
Update Go version to 1.22.5
```
```documentation
NONE
```
> Bump Go version to 1.22.5

- README.md
- pkg/controller/machine/controller.go
- pkg/providerconfig/types/types.go
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
1.27 has reached EOL https://kubernetes.io/releases/#release-v1-27
Fixes #
/kind cleanup
```release-note
Remove support for Kubernetes v1.27
```
```documentation
TBD
```
> Remove Kubernetes 1.27 support

- docs/cloud-provider.md
- pkg/cloudprovider/provider/openstack/provider.go
- pkg/cloudprovider/provider/openstack/provider_test.go
- pkg/cloudprovider/provider/openstack/types/types.go
This adds support for enabling config drive for OpenStack VMs. When enabled, metadata for machines is stored on a configuration drive instead of the metadata service.
Towards #1773 
/kind feature
```release-note
OpenStack: Support enabling config drive
```
```documentation
NONE
```
> OpenStack: Support enabling config drive

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
The Tinkerbell provider should provision bare metal machine deployment if the hardware has no metadata nor the metadata state is empty. This indicates that, the machine isn't yet provisioned nor staged. 
Fixes #
/kind bug
```release-note
None
```
```documentation
None
```
> Fix Hardware Metadata Condition for Tinkerbell Provider 

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/hardware.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/types/types.go
In Tinkerbell a workflow brings together [Hardware](https://tinkerbell.org/docs/concepts/hardware) and a [Template](https://tinkerbell.org/docs/concepts/templates) for execution.. The status field of the workflow can be used to determine the current state of the workflow and to identify any issues that may have occurred during the execution of it. Thus, it is important to keep track of those workflows even if they were executed to keep track of the provisioning processes. This PR makes the workflows of a hardware unique and it opens up the possibility to run a workflow multiple times and treat them as an idempotent process which can't be resumed in terms of failures. Those workflows must be deleted in two situations: 
1- The workflow has a pending …
> Refactor bare metal provider machine cleanup

- pkg/cloudprovider/provider/aws/provider.go
The latest Ubuntu 22.04 images have IMDSv2 enabled as a default. By default, the limit of hops of PUT requests to metadata service is 2. The instance metadata service is not reachable from the container network in case if further hops are required.
We came across this issue while working with Cilium as CNI. The issue has been documented [here](https://github.com/cilium/cilium/issues/25232).
Although, the issue mentions a workaround to make it work with Cilium. Fixing it just for a single component is not ideal since a tool like `machine-controller` shouldn't judge how the underlying network or programs hosted on the machines provisioned by it are configured. Hence, we went with a more generic fix for this, i.e. to set the [HTTP PUT response hop …
> AWS: Increase HttpPutResponseHopLimit to 3 for EC2 instances

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- hack/update-fixtures.sh
- hack/verify-licenses.sh
- pkg/cloudprovider/provider/alibaba/provider.go
- pkg/controller/util/machine_deployment.go
This bumps all Prowjobs to Go 1.23.
/kind chore
```release-note
Update to Go 1.23.0
```
```documentation
NONE
```
> bump to Go 1.23.0

- Dockerfile
- Makefile
Follow-up to #1838.
```release-note
NONE
```
```documentation
NONE
```
> bump Dockerfile to golang 1.23.0

- .prow/provider-aws.yaml
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
- test/e2e/provisioning/testdata/machinedeployment-digitalocean.yaml
CentOS 7 has reached end-of-life and the E2E tests are not functional any longer. Perhaps the CentOS 7 repositories are not functional any longer.
We need to completely clean up CentOS support from machine-controller, but this is the first step to unblock other PRs because of the failing E2E tests.
```release-note
NONE
```
```documentation
NONE
```
/assign @xrstf
> Remove CentOS tests

- examples/anexia-machinedeployment.yaml
- pkg/cloudprovider/provider/anexia/helper_test.go
- pkg/cloudprovider/provider/anexia/network_provisioning.go
- pkg/cloudprovider/provider/anexia/provider.go
- pkg/cloudprovider/provider/anexia/provider_test.go
- pkg/cloudprovider/provider/anexia/resolve_config.go
- pkg/cloudprovider/provider/anexia/types/types.go
Can now create multiple network interfaces, each with multiple addresses (one from each configured prefix), easily allowing Machines to have e.g. an IPv4 and IPv6 address.
/kind feature
We had an internal review already, which you see in the PR of our fork: https://github.com/anexia-it/machine-controller/pull/23
Might add some context if something looks odd.
```release-note
Anexia: extend network configuration, allowing multiple interfaces and multiple IPs per interface
```
```documentation
NONE
```
> Anexia: extend network configuration to allow multi-interface and multi-IP

- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Some parameters on the vSphere side are temporarily changed. This PR ensures that the vSphere E2E tests can pass.
```release-note
NONE
```
```documentation
NONE
```
> Fix vSphere E2E tests

- pkg/cloudprovider/provider/equinixmetal/provider.go
Adds "kubermatic" to the packngo User-Agent. This will help in usage and debug detail gathering.
This is also done in the Linode and Scaleway providers.
Related: https://github.com/kubermatic/kubermatic/pull/13629
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> add kubermatic to packngo User-Agent

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
Enabling the live migration of KubeVirt VMs by default. This would enable us to get a static ip address when using KubeOVN as a CNI. Another PR would actually fine tune this feature based on machine deployment configs.
Fixes #
/kind feature
```release-note
allow live migration by default
```
```documentation
None
```
> Add static up support for KubeVirt in KubeOVN

- OWNERS
- OWNERS_ALIASES
_Officially_ adding @kubermatic/sig-cluster-management as the code owner for machine-controller. We are retaining the `machine-controller-maintainers` section since there is a possibility that someone who doesn't belong to sig-cluster-management might still be a maintainer of MC as this project is a bit more open and can overlap with multiple SIGs. For example, sig-networking through https://github.com/kubermatic/machine-controller/pull/1849, which makes total sense to me.
**UPDATE:** After review, this PR simply removes the `machine-controller-maintainers` and adds Navid to `sig-cluster-management`
Fixes #
/kind chore
I'm not adding or removing …
> Add sig-cluster-management as code owners

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/use-storage-as-storage-target.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
Currently, machine controller only supports the creation of KubeVirt Data Volumes using PVCs without specifying what storage profile will be used which is quite important for some CSI drivers. 
Fixes #
/kind feature
This PR was tested manually with KubeVirt and two machine have been created and they were reflected correctly on the VMs: 
```shell
spec:
dataVolumeTemplates:
- metadata:
creationTimestamp: null
name: dv-test-557f6b6c88-2z7g2
spec:
source:
http:
url: http://remote/host/os
storage:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 25Gi
storageClassName: nfs
```
**Does this PR introduce a user-facing change? Then add your Release …
> Support Different Storage Targets for KubeVirt Provider 

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/location-zone-and-region-aware.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
Support for the two labels `topology.kubernetes.io/region` and `topology.kubernetes.io/zone` labels where they can deployed on both Node level(The kubelet or the external cloud-controller-manager populates this with the information from the cloud provider) and on PVC level(topology-aware volume provisioners will automatically set node affinity constraints on a PersistentVolume.). 
A zone represents a logical failure domain. It is common for Kubernetes clusters to span multiple zones for increased availability and a region represents a larger domain, made up of one or more zones. 
Fixes #
/kind feature
**Does this PR introduce a user-facing change? …
> Support topology aware zones and regions in KubeVirt

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/kubeovn-provider-network.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/use-storage-as-storage-target.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
KubeOvn has some features that can be used along side with KubeVirt. One of those features is subnet and vpc support. This PR supports the KubeOVN VPC and Subnet as a provider network in KubeVirt.
Fixes #
/kind feature
```release-note
Support KubeOVN as a provider network in KubeVirt
```
```documentation
None
```
> Support KubeVirt Provider Network

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
This PR will fix the following issues: 
- Restarting the host automatically in order to boot with new operating system and execute cloud-init scripts 
- The `decode-cloud-init-file` action was hardcoded based on the first reconciled hardware object, we fix it by using placeholder `{{.hardware_name}}` 
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix: Add reboot action and fix decode cloud-init bug 

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
This PR will fix a tiny bug. After provisioning the baremetal server successfully, the generated cloud-init script require manual interaction to execute correctly 
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> Fix: Configure Cloud-Init Script to execute automatically

- README.md
- test/e2e/provisioning/all_e2e_test.go
- test/e2e/provisioning/helper.go
Active support for Kubernetes v1.28 is over and maintenance support ends on 28 Oct 2024. 
https://endoflife.date/kubernetes
Fixes #
/kind cleanup
```release-note
Support for Kubernetes v1.28 has been removed
```
```documentation
NONE
```
> Drop support for Kubernetes v1.28

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/kubeovn-provider-network.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/use-storage-as-storage-target.yaml
This PR set the default kuebvirt storage target from PVC to Storage in order to leverage multiple CSI drivers in the infra cluster instead if using k8s PVC setting which might lead to different issues, such as access mode, volume binding mode, etc... In addition to that, it can read and set the volume access mode to the data volume spec based on the CDI storage profile. 
Fixes #
/kind feature
Tested manually and worked as expected.
```release-note
Support `dataVolumeTemplateSpec.dataVolumeSpec.Storage` and configure DataVolume based onn CDI StorageProfile
``` …
> Refactor kubervirt provider storage

- go.mod
- go.sum
- pkg/cloudprovider/provider/equinixmetal/provider.go
This replaces one Go package with another.
part of https://github.com/kubermatic/kubermatic/issues/13631
/kind feature
```release-note
Use official Equinix SDK instead of deprecated packethost/packngo.
```
```documentation
None
```
> replace packethost/packngo with equinix SDK

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/kubeovn-provider-network.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
- pkg/cloudprovider/provider/kubevirt/testdata/use-storage-as-storage-target.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
As the title reads, support and default to true for the KubeVirt VM Network Multi-Queue.
Fixes #
/kind feature
```release-note
support network multi queue in KubeVirt VM
```
```documentation
none
```
> Support VM Network Multi-Queue in KubeVirt Provider

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/types/types.go
Support sending the Basic Auth information to the data volume importing process using CDI secret ref.
Fixes #
/kind feature
```release-note
KubeVirt CDI Datavolume Secret Ref Support
```
```documentation
None
```
> Support KubeVirt CDI Datavolume Secret Ref

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
This PR will fix the decode fail when we use kubeconfig from envar. 
Fixes #
/kind bug
```release-note
Fix decoding kubeconfig from the variable environment in the Tinkerbell provider.
```
```documentation
NONE
```
> Fix decode kubeconfig from envar

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
Add support for specifying the main partition number for OS installation in bare-metal servers via the 
`hardware.kubermatic.io/partition-number` annotation in Tinkerbell Hardware Objects.
Fixes #
/kind feature
```release-note
Support added for specifying the main OS partition number in baremetal provider machines using the `hardware.kubermatic.io/partition-number` annotation.
```
```documentation
NONE
```
> Add partition number annotation

- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
- pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
Enable OSImageURL templating in workflows to support different OS images for each hardware server, as machine-controller creates templates only once.
Fixes #
```release-note
NONE
```
```documentation
NONE
```
> baremetal: Templating OSImage links through Tinkerbell workflow objects

- cmd/machine-controller/main.go
- pkg/cloudprovider/provider/anexia/types/types.go
- pkg/controller/machinedeployment/metrics.go
- add machine deployment metrics
```
machine_deployment_available_replicas{name="",namespace=""} 0
machine_deployment_ready_replicas{name="",namespace=""} 0
machine_deployment_replicas{name="",namespace=""} 0
machine_deployment_updated_replicas{name="",namespace=""} 0
```
Fixes #1767 
/kind feature
```release-note
Add collector to expose machine deployment metrics
```
```documentation
NONE
```
> feat(metrics): add machine deployment metrics

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/eviction-strategy-live-migrate.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
Currently, the KubeVirt VMs which are created using machine controller have an eviction strategy of `External` . With `EvictionStrategy: External`, kubevirt will create a PDB for the VMI which blocks eviction, and it will also set the `vmi.Status.EvacuationNodeName` on the vmi's status. When a VMI is being evicted, we need a way to have that eviction blocked so the cluster api related controllers can properly drain the k8s node running within the VMI before the VMI is torn down.
However, in some scenarios, users would like to be able to migrate VMs without blocking the migration by machine controller thus we would like to enable the users to decide which eviction strategy they would like to use.
Fixes #
**What type …
> Support kubevirt evection strategy in kv provider

- pkg/cloudprovider/provider.go
- pkg/cloudprovider/provider/external/provider.go
- pkg/controller/machine/controller.go
- pkg/providerconfig/types/types.go
This PR introduces a new provider called external, which takes care of the machine deployment lifecycle from a machine controller point of view. Another external service should be responsible for creating and orchestrating that cloud instance and sync these changes back to the machine object(e.g: adding labels, remove finalizers upon deleting etc...)
Fixes #
/kind feature
```release-note
Add support for external cloud providers 
```
```documentation
None
```
> Support External Cloud Provider

- test/e2e/provisioning/helper.go
This PR aims to fix the e2e tests for vsphere, specifically the provisioning for Ubuntu.
Fixes #
```release-note
None
```
```documentation
None
```
> Change Ubuntu template for Vsphere e2e tests

- go.mod
- pkg/cloudprovider/provider/kubevirt/provider.go
This pr fixes the validation of kubevirt virtual machines for dedicated cpus. With the current check the validation will fail when vcpus are configured because `c.Resources.Cpu()`  will never be nil because at least the format is set in the struct. 
Fixes #
/kind bug
```release-note
NONE
```
```documentation
NONE
```
> fix kubevirt cpu check + update sdk version in go.mod

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
- hack/verify-licenses.sh
This PR is to bump Go version to 1.23.7.
Fixes #
/kind chore
```release-note
machine-controller is now built using Go 1.23.7
```
```documentation
NONE
```
> Bump Go version to 1.23.7

- pkg/cloudprovider/provider/kubevirt/provider.go
- pkg/cloudprovider/provider/kubevirt/provider_test.go
- pkg/cloudprovider/provider/kubevirt/testdata/dedicated-vcpus.yaml
- pkg/cloudprovider/provider/kubevirt/types/types.go
This is a manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1906 and https://github.com/kubermatic/machine-controller/pull/1912
```release-note
A new field `cloudProviderSpec.virtualMachine.template.vcpus` was added to kubevirt provider. When `vcpus.cores` is set, the cpus for the virtual machine will be configured in `spec.template.spec.domain.cpu` instead of setting resource requests and limits explicit. The webhook validation will fail if both `vcpus` and `cpus` are configured for a machine.
```
/assign soer3n
> [release/v1.61] Cherry pick 1906 to release/v1.61

- pkg/admission/machines.go
- pkg/cloudprovider/provider/kubevirt/provider.go
The new KubeVirt CSI driver expects the tenant cluster nodes should have an annotation that determines the tenant cluster  namespace in the infra cluster. This PR reads the namespace value from the machine deployment spec and adds it to the node annotations. 
Fixes #
/kind chore
```release-note
Support KubeVirt cluster namespace annotations for KubeVirt worker nodes
```
```documentation
None
```
> Add ClusterNamespace Annotations to Worker Nodes 

- Makefile
- hack/ci/setup-machine-controller-in-kind.sh
If SDK and main module tags are on the same commit, GIT_TAG could be "sdk/v...", which is not semver anymore and would break anything. This PR is the therefore the equivalent of https://github.com/kubermatic/kubermatic/pull/14636, ensuring only main version tags are considered.
/kind cleanup
```release-note
NONE
```
```documentation
NONE
```
> Handle SDK version tags

- .prow/e2e-features.yaml
- .prow/postsubmits.yaml
- .prow/provider-alibaba.yaml
- .prow/provider-anexia.yaml
- .prow/provider-aws.yaml
- .prow/provider-azure.yaml
- .prow/provider-digitalocean.yaml
- .prow/provider-equinix-metal.yaml
- .prow/provider-gcp.yaml
- .prow/provider-hetzner.yaml
- .prow/provider-kubevirt.yaml
- .prow/provider-linode.yaml
- .prow/provider-nutanix.yaml
- .prow/provider-openstack.yaml
- .prow/provider-scaleway.yaml
- .prow/provider-vmware-cloud-director.yaml
- .prow/provider-vsphere.yaml
- .prow/verify.yaml
- Dockerfile
- Makefile
- hack/update-fixtures.sh
- hack/verify-licenses.sh
This PR is to bump Go version to 1.24.4. which contains several CVE fixes. 
Fixes #
/kind chore
```release-note
machine-controller is now built using Go 1.24.4
```
```documentation
NONE
```
> Bump Go version to 1.24.4

- pkg/admission/machinedeployments_validation.go
- pkg/admission/util.go
- pkg/cloudprovider/provider/vmwareclouddirector/helper.go
- pkg/cloudprovider/provider/vmwareclouddirector/provider.go
- sdk/cloudprovider/vmwareclouddirector/types.go
- test/e2e/provisioning/testdata/machinedeployment-vmware-cloud-director.yaml
This pr adds the ability to create machines in vmware cloud director with multiple nics using different networks. This is especially useful when you want to use a additional nic for storage
-
/kind feature
This change just adds the nic to the vm, for the configuration there is a osm pr https://github.com/kubermatic/operating-system-manager/pull/471
```release-note
Added the option to provision vmware cloud director nodes with multiple networks/nics
```
```documentation
TBD
```
> Add support to provisioning vcloud workers with multiple nics/networks
